Set up CI with Azure Pipelines
aau-giraf/weekplanner-OLDUI pull request #1
Opened 2019-02-15 14:14 UTC by boginw

2019-02-19 07:44 UTC, TobiasPalludan commented
Will do review with @kvisdaowner

2019-02-22 08:52 UTC, Lrss requested changes
Nu hvor dette merge flytter build systemet til Azure fra gitlab-runner kan vi godt slette .gitlab-ci.yml filen.

2019-02-22 08:55 UTC, Hylet commented on azure-pipelines.yml
> +    restoreSolution: '**/*.sln'
Er der nogen fordele ved at anvende wildcards frem for at benytte selve stien til filen? Gælder samme for linje 29.

2019-02-22 10:15 UTC, boginw commented on azure-pipelines.yml
> +    restoreSolution: '**/*.sln'
`**/*.sln` is now changed to `WeekPlanner.sln`, as this is more specific. As for line 29, there is only one file that would match, and it would not be unreasonable to assume that the WeekPlanner project should only produce one Android app. We can we, therefore, wait to change line 29, until necessary.

2019-02-22 10:16 UTC, boginw commented
@Lrss, the changes requested are now implemented

2019-02-22 10:17 UTC, Lrss approved these changes

2019-02-22 10:46 UTC, boginw commented
@Hylet, awaiting review

2019-02-22 11:06 UTC, Hylet approved these changes

2019-02-22 11:10 UTC, merged