Show activity and mark as done
aau-giraf/weekplanner-OLDUI pull request #143
Opened 2019-04-10 08:00 UTC by LukasRH

This closes #75 and #45 
Screen to view information about an activity and mark it as done.
The reason this PR solves two issues is that both issues are about the same screen.

![qemu-system-x86_64_2019-04-10_09-45-22](https://user-images.githubusercontent.com/16747705/55861695-2f0b0d00-5b77-11e9-9311-40cb4c4f518e.png)
![qemu-system-x86_64_2019-04-10_09-46-33](https://user-images.githubusercontent.com/16747705/55861710-37634800-5b77-11e9-8a28-dc9301c65c5a.png)

2019-04-10 08:48 UTC, TobiasPalludan commented
@aau-giraf/sw609f19 you have been assigned this. Here's your checklist. I marked @Tricky12321 as the reviewer, but you might change it as you like.
Please use the following checklist. Feel free to check it off as you go along.
**Code Design**
- [ ] Is the code in the right place? (Both in terms of folder structure and class structure)
- [ ] Could this code, to the best of your knowledge, have reused existing code?
- [ ] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [ ] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**
- [ ] Are names meaningful and self-documenting?
- [ ] Is it understandable, by reading the code, what it does?
- [ ] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [ ] Is it understandable, by reading the tests, what they do?
- [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
- [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [ ] Are error messages in the code understandable?
- [ ] Are confusing sections of code covered by comments?

**Functionality**
For this part, open the app, and test:
- [ ] Are the features that the code claims to implement, actually implemented?
- [ ] Does it look like the code has bugs?
- [ ] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**
- [ ] Are UI messages, that the user might meet, actually helpful?
- [ ] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [ ] Is there well written code in this? Remember to tell the developer!

2019-04-10 08:49 UTC, TobiasPalludan commented
@aau-giraf/sw611f19 you have been assigned this. Here's your checklist. I marked @scarress as the reviewer, but you might change it as you like.
Please use the following checklist. Feel free to check it off as you go along.
**Code Design**
- [ ] Is the code in the right place? (Both in terms of folder structure and class structure)
- [ ] Could this code, to the best of your knowledge, have reused existing code?
- [ ] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [ ] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**
- [ ] Are names meaningful and self-documenting?
- [ ] Is it understandable, by reading the code, what it does?
- [ ] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [ ] Is it understandable, by reading the tests, what they do?
- [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
- [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [ ] Are error messages in the code understandable?
- [ ] Are confusing sections of code covered by comments?

**Functionality**
For this part, open the app, and test:
- [ ] Are the features that the code claims to implement, actually implemented?
- [ ] Does it look like the code has bugs?
- [ ] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**
- [ ] Are UI messages, that the user might meet, actually helpful?
- [ ] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [ ] Is there well written code in this? Remember to tell the developer!

2019-04-10 08:52 UTC, Moesgaarda commented
Is it possible to make the button gradient, as described in [the design guide](https://aau-giraf.github.io/wiki/design_guide/buttons.html)?

2019-04-10 09:00 UTC, Moesgaarda commented
I have been informed that the button will be fixed with #85, please make an issue stating that this needs to be fixed later on.

2019-04-10 09:44 UTC, Tricky12321 commented
Should there be a way to 'unmark' an activity done? That does not seem like an option?

2019-04-10 09:51 UTC, LukasRH commented
> Should there be a way to 'unmark' an activity done? That does not seem like an option?

This was not part of the issue or portrayed in the prototypes.
Not sure if that should be implemented here or a new issue should be made for it, @Moesgaarda ?

2019-04-10 09:54 UTC, Tricky12321 requested changes
I have some comments for the code :)

2019-04-10 09:54 UTC, Tricky12321 commented on .gitignore
> +>>>>>>> 19f0282d7581d8def972164077ae78534389a242
Why have you made changes to the gitignore file?

2019-04-10 09:54 UTC, Tricky12321 commented on lib/main.dart
Strange edit, since you have nothing to do with the login screen?

2019-04-10 09:54 UTC, Tricky12321 commented on lib/models/activity_model.dart
>      @required this.pictogram,
Why is there empty comments?

2019-04-10 09:54 UTC, Tricky12321 commented on lib/blocs/activity_bloc.dart
> +}
Please do only use triple /// for class comments, and double // for inside classes

2019-04-10 09:54 UTC, Tricky12321 commented on lib/screens/weekplan_screen.dart
>  class WeekplanScreen extends StatelessWidget {
Why the sudden change in commenting style?

2019-04-10 09:54 UTC, Tricky12321 commented on test/blocs/weekplans_bloc_test.dart
>    test('Should dispose weekModels stream', async((DoneFn done) {
Random ekstra line?

2019-04-10 09:54 UTC, Tricky12321 commented on test/screens/show_activity_screen_test.dart
> +  });
This expect can be much simpler by using 
`expect(find.byType(GirafAppBar), findsOneWidget);`

2019-04-10 10:01 UTC, LukasRH commented on lib/main.dart
We have used the main file to gain access to our screen for testing purposes. The change of where the login screen is located came as a result of merging develop into the branch

2019-04-10 10:05 UTC, Tricky12321 commented on lib/main.dart
Okay

2019-04-10 10:05 UTC, LukasRH commented on lib/models/activity_model.dart
>      @required this.pictogram,
Was added as linter complained, this is not our model and were not sure what to write. but I have added some simple comments

2019-04-10 10:09 UTC, LukasRH commented on lib/screens/weekplan_screen.dart
>  class WeekplanScreen extends StatelessWidget {
This is not our comment, this is a comment from the group who made the weekplan screen. I dont know why there are changes to it here.

2019-04-10 10:09 UTC, HaZzM22 commented on test/screens/show_activity_screen_test.dart
> +  });
This have been fixed

2019-04-10 10:19 UTC, Tricky12321 requested changes

2019-04-10 10:19 UTC, Tricky12321 commented on .gitignore
> -android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
You still have changes to the gitignore

2019-04-10 10:19 UTC, Tricky12321 commented on lib/models/activity_model.dart
>      @required this.pictogram,
Constructor should only be // not ///

2019-04-10 10:19 UTC, Tricky12321 commented on lib/screens/show_activity_screen.dart
> +  ShowActivityScreen(this._weekModel, this._activity, this._girafUser,
// not /// inside the class. This goes for this entire file

2019-04-10 10:19 UTC, Tricky12321 commented on pubspec.yaml
>    rflutter_alert: ^1.0.2
Why have you downgraded auto_size_text?

2019-04-10 10:22 UTC, LukasRH commented on .gitignore
> -android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
Yes, we removed the lines that were added. I don't know how you want us to remove them without making a change.

2019-04-10 10:24 UTC, Tricky12321 commented on .gitignore
> -android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
These lines are part of the git ignore, these are some you removed

2019-04-10 10:31 UTC, Alechj commented on .gitignore
> -android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
Resolved.

2019-04-10 10:56 UTC, Tricky12321 submitted a review, later dismissed

2019-04-10 10:58 UTC, Tricky12321 commented
The weekplan screen is not updated with status about activities being completed

2019-04-10 10:58 UTC, Moesgaarda commented
> 
> 
> > Should there be a way to 'unmark' an activity done? That does not seem like an option?
> 
> This was not part of the issue or portrayed in the prototypes.
> Not sure if that should be implemented here or a new issue should be made for it, @Moesgaarda ?

If it's easy to implement here, it would be cool if you do so - otherwise create an issue for it.

2019-04-10 11:23 UTC, Alechj commented
> > > Should there be a way to 'unmark' an activity done? That does not seem like an option?
> > 
> > 
> > This was not part of the issue or portrayed in the prototypes.
> > Not sure if that should be implemented here or a new issue should be made for it, @Moesgaarda ?
> 
> If it's easy to implement here, it would be cool if you do so - otherwise create an issue for it.

We will implement it straight away.

2019-04-10 11:24 UTC, Alechj commented
> The weekplan screen is not updated with status about activities being completed

Making the weekplan screen reflects changes the state of activities is a seperate issue, ill make sure to make an issue request.

2019-04-10 11:40 UTC, LukasRH commented
It is now possible to undo
![qemu-system-x86_64_2019-04-10_13-36-46](https://user-images.githubusercontent.com/16747705/55875731-19591000-5b96-11e9-979f-18eaacc455b7.png)

2019-04-10 11:45 UTC, Moesgaarda commented
The design is PO approved, good job!

2019-04-10 11:48 UTC, Tricky12321 submitted a review, later dismissed

2019-04-10 12:30 UTC, Moesgaarda commented
> 
> 
> > The weekplan screen is not updated with status about activities being completed
> 
> Making the weekplan screen reflect changes of the state of activities is a seperate issue, ill make sure to make an issue request.

This is not a separate issue, it may not be explicitly stated in the user story, but it so tightly linked that it does not make sense to split it into two issues at this point.

2019-04-10 12:53 UTC, Alechj commented
> > > The weekplan screen is not updated with status about activities being completed
> > 
> > 
> > Making the weekplan screen reflect changes of the state of activities is a seperate issue, ill make sure to make an issue request.
> 
> This is not a separate issue, it may not be explicitly stated in the user story, but it so tightly linked that it does not make sense to split it into two issues at this point.

Alright, this was not clear to us from the issue, but we are looking into it now. Ill bring it up to the next retrospective meeting.

2019-04-10 13:28 UTC, ralled96 commented
We are working on updating the weekplan screen, so that is shows the checkmark aswell. We will let you know when it is ready for reviews.

2019-04-11 11:39 UTC, LukasRH commented
Marking an activity as done is now reflected on the weekplan screen. 
![qemu-system-x86_64_2019-04-11_13-29-05](https://user-images.githubusercontent.com/16747705/55954519-30b00000-5c5f-11e9-8ae0-bb2812e89da1.png)

2019-04-11 11:42 UTC, LukasRH commented
@Moesgaarda @Tricky12321 @scarress The PR has now been changed to the requested changes and is ready for review again.

2019-04-11 13:48 UTC, scarress requested changes
I have build and tested the feature, from what I could see it worked as it should.
However there are some issues in the BLoC, it does not actually behave as a BLoC.
This could cause some issues in how and when Flutter decides to update the screens, so it would be preferable if it utilized streams for this.
There are some small things with the tests as well, but I think they will fixed if the streams are implemented.
Other than that it looks good.
If you need some help, you can ask us in group room 1.220.

2019-04-11 13:48 UTC, scarress commented on lib/screens/show_activity_screen.dart
> +        /*OutlineButton( // The cancel button is prepared under, a check should just be made to check if the user is a guardian
This should be removed.

2019-04-11 13:48 UTC, scarress commented on lib/screens/show_activity_screen.dart
> +            aspectRatio: 10.0 / 10.0,
should this division be here?

2019-04-11 13:48 UTC, scarress commented on lib/blocs/activity_bloc.dart
> +import 'package:weekplanner/blocs/bloc_base.dart';
This code does not use the BLoC pattern, nor the statefull/stateless pattern.
The state need to be exposed in streams.

2019-04-11 13:48 UTC, scarress commented on lib/blocs/activity_bloc.dart
> +  void dispose() {}
If you add streams, remember to dispose of them here.

2019-04-11 13:48 UTC, scarress commented on lib/screens/show_activity_screen.dart
> +class ShowActivityScreen extends StatefulWidget {
Is there a reason for this widgits being stateful?
I think the state should be stored in the BLoC.

2019-04-12 08:53 UTC, Tricky12321 requested changes
There are no tests, that actually press on buttons and see if the buttons works. This has to be made before i will accept the tests. The tests only tests if stuff render, not if stuff works.

I have some other comments for the code as well, which can be seen below

2019-04-12 08:53 UTC, Tricky12321 commented on lib/blocs/activity_bloc.dart
> +  }
Why is there a load function?

Why can't this be in the constructor?

2019-04-12 08:53 UTC, Tricky12321 commented on test/screens/show_activity_screen_test.dart
> +
Why is there an empty setupApiCalls method?

2019-04-12 08:53 UTC, Tricky12321 commented on test/screens/show_activity_screen_test.dart
> +    setupApiCalls();
Why do you call a method that does nothing?

2019-04-12 08:53 UTC, Tricky12321 commented on test/screens/show_activity_screen_test.dart
> +class MockNavigatorObserver extends Mock implements NavigatorObserver {}
This class is created, but it does not seem to be used?

2019-04-12 08:53 UTC, Tricky12321 commented on test/screens/show_activity_screen_test.dart
> +import '../blocs/activity_bloc_test.dart';
One test cannot be dependent on another test. This is very bad code style

2019-04-12 08:53 UTC, Tricky12321 commented on test/blocs/activity_bloc_test.dart
> +  final UsernameModel user = UsernameModel(id: '50', name: null, role: null);
Please rename this user to a mockUser so its clear that this is mocked

2019-04-12 08:53 UTC, Tricky12321 commented on test/screens/show_activity_screen_test.dart
> +  final List<ActivityModel> activities = <ActivityModel>[
Same here, please use mockActivities so its clear this is mocked

2019-04-12 08:53 UTC, Tricky12321 commented on test/screens/show_activity_screen_test.dart
> +    await tester.pumpWidget(MaterialApp(
Here you just set the state of the Activity, but this does not test if the button works?

2019-04-12 08:53 UTC, Tricky12321 commented on test/screens/show_activity_screen_test.dart
> +    expect(find.byKey(const Key('IconComplete')), findsNothing);
This method does only test if the state is normal before the screen is rendered, not if it is changed when the state is changed while the screen is rendered, this test is not sufficient.

2019-04-12 08:53 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +    await tester.pumpWidget(MaterialApp(home: WeekplanScreen(weekModel, user)));
Same here, you set the state before the screen is rendered, what about changing the state after the screen is rendered?

2019-04-12 08:53 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +  });
Here you use a key to find IconComplete, but keys should only be used for a unique widget, as i understand there is multiple checkmarks, meaning that there is multiple keys of 'IconComplete'

2019-04-12 08:53 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +  });
Same here about 'IconComplete' Key

2019-04-15 12:44 UTC, HaZzM22 commented on lib/blocs/activity_bloc.dart
> +  }
If we had to use the parameters in the constructor how would we then use dependency injection correctly?

2019-04-15 12:50 UTC, HaZzM22 commented on test/screens/show_activity_screen_test.dart
> +import '../blocs/activity_bloc_test.dart';
In the bloc test we created a MockWeekApi which we wanna use in the screen. We are not dependent on the tests in the bloc_test however we use the same mock API. This has also been done in other screen tests.

2019-04-15 12:53 UTC, HaZzM22 commented on test/screens/weekplan_screen_test.dart
> +  });
What method would you recommend to test this differently?

2019-04-16 06:44 UTC, Tricky12321 commented on lib/blocs/activity_bloc.dart
> +  }
Dependency injection can be done anywhere and does not have to be in the constructor, it can be just as a getter

2019-04-16 06:46 UTC, Tricky12321 commented on test/screens/show_activity_screen_test.dart
> +import '../blocs/activity_bloc_test.dart';
I would like PO review on this, because i would argue the MockWeekApi should't be referenced this way

2019-04-16 06:52 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +  });
Its probably fine

2019-04-16 06:54 UTC, Tricky12321 requested changes
There is a single comment, and than you have not actually fixed some of the comments, but just "resolved" them

2019-04-16 06:54 UTC, Tricky12321 commented on test/screens/show_activity_screen_test.dart
> +    await tester.pump(Duration.zero);
Why do you `tester.pump(Duration.zero)`?
you dont HAVE to put a duration, you can just do `tester.pump();`

2019-04-16 06:56 UTC, Tricky12321 commented on test/screens/show_activity_screen_test.dart
> +    await tester.tap(find.byKey(const Key('CompleteStateToggleButton')));
Same here, why Duration.zero?

2019-04-16 07:10 UTC, HaZzM22 commented on test/screens/show_activity_screen_test.dart
> +    await tester.pump(Duration.zero);
sorry about that, we thought that it was necessary.

2019-04-16 07:16 UTC, HaZzM22 commented on test/screens/weekplan_screen_test.dart
> +    await tester.pumpWidget(MaterialApp(home: WeekplanScreen(weekModel, user)));
The state is set before the screen is rendered to test the two cases were the activity have been set to completed in a different screen and vice versa. A different test in the show activity screen tests changing the state after the screen is rendered.

2019-04-16 07:29 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +  });
I would recommend making the IconComplete part as a widget, and finding it by type

2019-04-16 07:32 UTC, MrTasty commented
> 
> 
> There is a single comment, and than you have not actually fixed some of the comments, but just "resolved" them

We only resolved the comments that we applied fixes to. What comments are you referring to that wasn't resolved?

2019-04-16 07:43 UTC, LukasRH commented on lib/blocs/activity_bloc.dart
> +  }
Yes, but if we add more parameters to the constructor, how should we define it in bootstrap and so on so that we can use get the bloc with dependency injection as well as give it the values...

2019-04-16 08:28 UTC, Tricky12321 commented on lib/blocs/activity_bloc.dart
> +  }
Yes, i see this. This is good then

2019-04-16 08:32 UTC, Tricky12321 commented
> > There is a single comment, and than you have not actually fixed some of the comments, but just "resolved" them
> 
> We only resolved the comments that we applied fixes to. What comments are you referring to that wasn't resolved?

You still have not written tests for pressing a pictogram to see if your screen renderes then, and your tests still call the methods in some places, and not pressing the buttons. The tests if the methods work are irrelevant when you have the buttons, which is the ones you should be testing.

Everything that is clickable, should have a test.

2019-04-16 08:34 UTC, Tricky12321 requested changes
Never mind, my bad, GitHub showed no changes were made, but they were.

2019-04-16 08:34 UTC, Tricky12321 commented on test/screens/show_activity_screen_test.dart
> +
This is still empty? and you resolved it?

2019-04-16 08:34 UTC, Tricky12321 commented on test/screens/show_activity_screen_test.dart
> +    setupApiCalls();
You will call this

2019-04-16 08:46 UTC, Tricky12321 commented
There is also a small bug with pictograms that are not square, the 'checkmark' is not at the center of the pictogram

![IMG_13F9079F3EFB-1](https://user-images.githubusercontent.com/10461592/56195233-d46d2780-6034-11e9-8f80-7189fef8e14a.jpeg)

2019-04-16 08:52 UTC, MrTasty commented
> 
> 
> There is also a small bug with pictograms that are not square, the 'checkmark' is not at the center of the pictogram
> 
> ![IMG_13F9079F3EFB-1](https://user-images.githubusercontent.com/10461592/56195233-d46d2780-6034-11e9-8f80-7189fef8e14a.jpeg)

![billede](https://user-images.githubusercontent.com/14176903/56195689-bbb14180-6035-11e9-88a1-7c71dcb87455.png) Fixed.

2019-04-16 09:04 UTC, MrTasty commented on test/screens/show_activity_screen_test.dart
> +import '../blocs/activity_bloc_test.dart';
@Moesgaarda could the PO group take a look at this? 🥇

2019-04-16 09:17 UTC, Tricky12321 requested changes
These are the rest of my requested changes, i do not believe there are more than this.

2019-04-16 09:17 UTC, Tricky12321 commented on test/blocs/activity_bloc_test.dart
> +  }));
This test should press a button and not call a method

2019-04-16 09:17 UTC, Tricky12321 commented on test/blocs/activity_bloc_test.dart
> +  }));
This test should press a button and not call a method

2019-04-16 09:17 UTC, Tricky12321 commented on test/blocs/activity_bloc_test.dart
> +
Why do you Mock the WeekApi if you do not change anything? There is nothing there is mocked about it, so why mock it in the first place?

2019-04-16 09:17 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
>  }
There is no tests here to test if clicking on a pictogram, shows your new screen.

2019-04-16 12:45 UTC, jenspetur94 commented on test/screens/show_activity_screen_test.dart
> +import '../blocs/activity_bloc_test.dart';
We agree with @tricky12321.
A test should not depend on another test.

2019-04-16 14:52 UTC, LukasRH commented on test/blocs/activity_bloc_test.dart
> +  }));
This is a test in the bloc and there is no button to test on. The test you want can be found in show_activity_screen_test.dart

2019-04-16 14:53 UTC, LukasRH commented on test/blocs/activity_bloc_test.dart
> +  }));
This is a test in the bloc and there is no button to test on. The test you want can be found in show_activity_screen_test.dart

2019-04-16 15:02 UTC, LukasRH commented on test/blocs/activity_bloc_test.dart
> +
This is done so we can use the weekapi in the test without having to give it an http as parameter. 
In setupApiCalls the update function is mocked.

2019-04-16 15:42 UTC, LukasRH commented on test/screens/show_activity_screen_test.dart
> +import '../blocs/activity_bloc_test.dart';
Then I think that an issue should be created with the purpose to correct these changes in the other test files. As we are not the only group who have done this. One example is the weekplan screen test, which currently depends on pictogram_bloc_test and weekplan_bloc_test

2019-04-17 06:47 UTC, Tricky12321 commented on test/blocs/activity_bloc_test.dart
> +
If you dont change anything about the API, there is no reason to mock it. You can mock the update function without mocking it

2019-04-17 06:54 UTC, Tricky12321 commented on test/screens/show_activity_screen_test.dart
> +import '../blocs/activity_bloc_test.dart';
That should be done then

2019-04-17 06:55 UTC, Tricky12321 commented on test/blocs/activity_bloc_test.dart
> +  }));
I see, then its fine

2019-04-17 07:20 UTC, jenspetur94 commented on test/screens/show_activity_screen_test.dart
> +import '../blocs/activity_bloc_test.dart';
yes i saw that. we are currently looking into it

2019-04-17 12:17 UTC, LukasRH commented on test/screens/weekplan_screen_test.dart
>  }
It have been chosen not to make integration test

2019-04-17 12:25 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
>  }
But it is quite easy to do...

2019-04-17 12:29 UTC, Tricky12321 requested changes
I think you should do the integration tests, since its as simple as running the code, and checking using `find.byType(ScreenName)`

2019-04-17 12:29 UTC, Tricky12321 commented on test/blocs/activity_bloc_test.dart
> +  WeekApi weekApi;
You changed this to WeekApi, but in the other file its still MockWeekApi, please make it identical

2019-04-17 12:29 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +
You have added this again, this is not needed

2019-04-17 20:04 UTC, Tricky12321 commented
When an issue has been opened regarding the integration test, i will approve this :)

2019-04-18 11:32 UTC, MrTasty commented
> 
> 
> When an issue has been opened regarding the integration test, i will approve this :)

We have opened issue #160 now :)

2019-04-18 14:26 UTC, Tricky12321 approved these changes

2019-04-20 08:20 UTC, Moesgaarda commented
Design is approved! 👍

2019-04-20 08:20 UTC, Tekrus approved these changes

2019-04-21 06:48 UTC, scarress approved these changes

2019-04-23 07:04 UTC, merged