Extracted API to its own repo
aau-giraf/weekplanner-OLDUI pull request #147
Opened 2019-04-10 10:20 UTC by boginw

This closes #95. See [this](https://github.com/aau-giraf/api_client) to keep up with the API client. This PR contains only deletions and updated references, so it should be pretty quick.

I'd like to comment, that the only thing that was done to make the tests pass which mock the API (which was the reason why this PR was reverted), was to update the imports of those files (since `package:weekplanner/providers/api/*` no longer exists)

2019-04-10 12:46 UTC, ralled96 requested changes
The 'new' API returns an exception instead of null when there is no weekplans. 
As we talked about on Slack, this is fixed by handling the exception:

On line 46, in weekplan_bloc.dart it is fixed by adding this:
`_api.week.getNames(_user.id).listen(_weekNameModelsList.add, 
      onError: (Object exception) => getAllWeekInfo(null));`

2019-04-10 14:19 UTC, boginw commented
@ralled96 this has now been fixed

2019-04-10 14:27 UTC, ralled96 submitted a review, later dismissed

2019-04-11 11:25 UTC, TobiasPalludan commented on lib/screens/weekplan_screen.dart
> +/// The WeekplandScreen is used to display a week
```suggestion
/// The WeekplanScreen is used to display a week
```

2019-04-11 11:39 UTC, TobiasPalludan commented on lib/models/response_model.dart
> -import 'package:weekplanner/models/enums/error_key.dart';
This file was deleted, but it wasn't added to the api_client repository. Is that on purpose?

2019-04-11 11:40 UTC, boginw commented on lib/models/response_model.dart
> -import 'package:weekplanner/models/enums/error_key.dart';
https://github.com/aau-giraf/api_client/blob/master/lib/models/enums/error_key.dart

2019-04-11 11:46 UTC, TobiasPalludan approved these changes

2019-04-11 11:55 UTC, ralled96 approved these changes

2019-04-11 11:55 UTC, merged