Flutter/feature 051
aau-giraf/weekplanner-OLDUI pull request #164
Opened 2019-04-24 07:55 UTC by swuf

This closes #51.
![pullreq2](https://user-images.githubusercontent.com/26706527/56642037-e83d0d00-6676-11e9-8c49-d1c232f7f91b.png)

2019-04-24 11:33 UTC, Jacob6565 commented
@aau-giraf/sw610f19 you have been assigned this. Here's your checklist. I marked @Moesgaarda as the reviewer, but you might change it as you like.
Please use the following checklist. Feel free to check it off as you go along.
**Code Design**
- [ ] Is the code in the right place? (Both in terms of folder structure and class structure)
- [ ] Could this code, to the best of your knowledge, have reused existing code?
- [ ] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [ ] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**
- [ ] Are names meaningful and self-documenting?
- [ ] Is it understandable, by reading the code, what it does?
- [ ] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [ ] Is it understandable, by reading the tests, what they do?
- [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
- [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [ ] Are error messages in the code understandable?
- [ ] Are confusing sections of code covered by comments?

**Functionality**
For this part, open the app, and test:
- [ ] Are the features that the code claims to implement, actually implemented?
- [ ] Does it look like the code has bugs?
- [ ] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**
- [ ] Are UI messages, that the user might meet, actually helpful?
- [ ] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [ ] Is there well written code in this? Remember to tell the developer!

2019-04-24 11:34 UTC, Jacob6565 commented
@aau-giraf/sw613f19 you have been assigned this. Here's your checklist. I marked @ralled96 as the reviewer, but you might change it as you like.
Please use the following checklist. Feel free to check it off as you go along.
**Code Design**
- [ ] Is the code in the right place? (Both in terms of folder structure and class structure)
- [ ] Could this code, to the best of your knowledge, have reused existing code?
- [ ] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [ ] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**
- [ ] Are names meaningful and self-documenting?
- [ ] Is it understandable, by reading the code, what it does?
- [ ] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [ ] Is it understandable, by reading the tests, what they do?
- [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
- [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [ ] Are error messages in the code understandable?
- [ ] Are confusing sections of code covered by comments?

**Functionality**
For this part, open the app, and test:
- [ ] Are the features that the code claims to implement, actually implemented?
- [ ] Does it look like the code has bugs?
- [ ] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**
- [ ] Are UI messages, that the user might meet, actually helpful?
- [ ] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [ ] Is there well written code in this? Remember to tell the developer!

2019-04-24 11:44 UTC, Tekrus requested changes
Very minor comments in GUI text, generally it seems correct and very nicely documented.

2019-04-24 11:44 UTC, Moesgaarda commented on lib/screens/new_weekplan_screen.dart
> +        appBar: GirafAppBar(title: 'Ny Ugeplan'),
```suggestion
        appBar: GirafAppBar(title: 'Ny ugeplan'),
```

2019-04-24 11:44 UTC, Moesgaarda commented on lib/screens/new_weekplan_screen.dart
> +        'Gem Ugeplan',
```suggestion
        'Gem ugeplan',
```

2019-04-24 11:44 UTC, Moesgaarda commented on lib/screens/new_weekplan_screen.dart
> +                        'Vælg Skabelon',
```suggestion
                        'Vælg skabelon',
```

2019-04-24 12:17 UTC, Tricky12321 requested changes
I have some comments, and there is no integration tests, that try to click the 'create weekplan' button, and click the pictogram button to see the pictogram search. This is something that is missing, which should be implemented.


The design looks good, and i found no bugs. I want to see the integration tests, and the comments i made resolved :) 

Also what about deleting week plans? are this a separate issue, or should this also be implemented with this PR? If it is not for this PR than a issue should be created and referenced

2019-04-24 12:17 UTC, Tricky12321 commented on lib/blocs/new_weekplan_bloc.dart
> +  /// Gives the ability to create a new weekplan.
This comment should be rewritten

2019-04-24 12:17 UTC, Tricky12321 commented on lib/blocs/new_weekplan_bloc.dart
> +      sink.add(input.isNotEmpty && input.length <= 32);
Why should the input be less than 32? What if i want a title longer than 32?

2019-04-24 12:17 UTC, Tricky12321 commented on lib/blocs/new_weekplan_bloc.dart
> +      sink.add(year != null && year >= 1000 && year <= 9999);
Should it be possible to do years in the past?

2019-04-24 12:17 UTC, Tricky12321 commented on lib/screens/new_weekplan_screen.dart
> +                              ? 'Titel skal være mellem 1 og 32 tegn'
Here it is again, why 32?

2019-04-24 12:17 UTC, Tricky12321 commented on lib/screens/new_weekplan_screen.dart
> +                      // Handle when a weekplan is made from a template
The comment should be before what it describes not after

2019-04-24 12:17 UTC, Tricky12321 commented on test/screens/new_weekplan_screen_test.dart
> +import '../test_image.dart';
You should never refer to other files containing information. test_image.dart is okay, but the others you will have to duplicate the code.

2019-04-24 12:17 UTC, Tricky12321 commented on lib/blocs/new_weekplan_bloc.dart
> +      sink.add(year != null && year >= 1000 && year <= 9999);
Maybe implementing that a weekplan cannot be created in a year that is before the current date?

2019-04-24 12:17 UTC, Tricky12321 commented on lib/blocs/new_weekplan_bloc.dart
> +  void initialize(UsernameModel user) {
Is this needed? Can this be moved to the constructor?

2019-04-24 12:25 UTC, swuf commented on lib/blocs/new_weekplan_bloc.dart
> +      sink.add(input.isNotEmpty && input.length <= 32);
We will remove the 32 character limit since the back-end and database don't seem to have a limit either.

2019-04-24 12:36 UTC, swuf commented on lib/blocs/new_weekplan_bloc.dart
> +      sink.add(year != null && year >= 1000 && year <= 9999);
We are thinking about changing this so the year of the weekplan will be current year +- 1, to avoid issues around new year (week 52/53 can extend into the following year).

2019-04-24 12:45 UTC, Tricky12321 commented on lib/blocs/new_weekplan_bloc.dart
> +      sink.add(year != null && year >= 1000 && year <= 9999);
True, this is a good consideration, but i think it should be implemented to not allow years other than in the future, or if the week is 52 or 53 allow the previous year

2019-04-24 12:49 UTC, swuf commented on lib/screens/new_weekplan_screen.dart
> +                      // Handle when a weekplan is made from a template
Fixed.

2019-04-24 12:49 UTC, swuf commented on lib/screens/new_weekplan_screen.dart
> +                              ? 'Titel skal være mellem 1 og 32 tegn'
Fixed.

2019-04-24 13:02 UTC, swuf commented on lib/blocs/new_weekplan_bloc.dart
> +  void initialize(UsernameModel user) {
We don't think this is possible unfortunately. This is because the NewWeekplanBloc is registered as a singleton and therefore only gets instantiated once, but won't necessarily be used with only one user.  The bloc is a singleton because the entered data should remain after changing to the pictogram search screen and back again.

2019-04-24 13:03 UTC, swuf commented on lib/blocs/new_weekplan_bloc.dart
> +      sink.add(year != null && year >= 1000 && year <= 9999);
We would prefer not to implement it this way since the year and the week number are validated individually.

2019-04-24 16:09 UTC, Tricky12321 commented on lib/blocs/new_weekplan_bloc.dart
> +  void initialize(UsernameModel user) {
Then it is okay :)

2019-04-24 16:09 UTC, Tricky12321 commented on lib/blocs/new_weekplan_bloc.dart
> +      sink.add(year != null && year >= 1000 && year <= 9999);
This is okay than :)

2019-04-24 19:41 UTC, swuf commented on lib/blocs/new_weekplan_bloc.dart
> +  /// Gives the ability to create a new weekplan.
Done.

2019-04-24 19:42 UTC, swuf commented on test/screens/new_weekplan_screen_test.dart
> +import '../test_image.dart';
Okay noted and fixed.

2019-04-24 20:14 UTC, Tricky12321 requested changes
There are some comments to the changes, and there are still no integration tests

2019-04-24 20:14 UTC, Tricky12321 commented on lib/blocs/new_weekplan_bloc.dart
> +          year != null && year >= currentYear - 1 && year <= currentYear + 1);
This means that i cannot do weekplans for 2021 since we are in 2019, this should properly be possible

2019-04-24 20:14 UTC, Tricky12321 commented on lib/screens/new_weekplan_screen.dart
> +                              ? 'Titel skal bestå af mindst et tegn'
'Title må ikke være tom' it should be 'Titel skal bestå af mindst et tegn'

2019-04-24 20:14 UTC, Tricky12321 commented on test/screens/new_weekplan_screen_test.dart
> +    expect(find.text('Titel skal bestå af mindst et tegn'), findsOneWidget);
Again, title must not be empty

2019-04-24 20:14 UTC, Tricky12321 commented on test/screens/new_weekplan_screen_test.dart
> +        findsOneWidget);
Should be "og være i fremtiden"

2019-04-24 20:14 UTC, Tricky12321 commented on test/screens/new_weekplan_screen_test.dart
> +        findsNothing);
Should be "og være i fremtiden"

2019-04-24 20:31 UTC, swuf commented on lib/blocs/new_weekplan_bloc.dart
> +          year != null && year >= currentYear - 1 && year <= currentYear + 1);
So what would you suggest no upper limit or something like year 9999? (:

2019-04-24 20:37 UTC, swuf commented on lib/screens/new_weekplan_screen.dart
> +                              ? 'Titel skal bestå af mindst et tegn'
What about 'Titel feltet må ikke være tomt'?

2019-04-25 05:36 UTC, Moesgaarda commented on lib/screens/new_weekplan_screen.dart
> +                              ? 'Titel skal bestå af mindst et tegn'
I'd prefer "Titelfeltet må ikke være tomt" or "Titel skal udfyldes"

2019-04-25 05:54 UTC, Tekrus requested changes

2019-04-25 05:54 UTC, Moesgaarda commented on lib/blocs/new_weekplan_bloc.dart
> +          year != null && year >= currentYear - 1 && year <= currentYear + 1);
Year 9999 would be fine, only allowing one year from now is a bit weird

2019-04-25 05:54 UTC, Moesgaarda commented on lib/screens/new_weekplan_screen.dart
> +                                  'og være inden for et år af i dag'
This one should be updated when you guys update the implementation above

2019-04-25 05:54 UTC, Moesgaarda commented on lib/blocs/new_weekplan_bloc.dart
> +
```suggestion
```

2019-04-25 06:30 UTC, Tricky12321 requested changes
Great to see integration test, only a small comment

2019-04-25 06:30 UTC, Tricky12321 commented on test/screens/new_weekplan_screen_test.dart
> +    await tester.pump();
There should be no need to pump twice, if this is needed consider using pumpAndSettle instead

2019-04-25 06:31 UTC, Tricky12321 commented on lib/blocs/new_weekplan_bloc.dart
> +          year != null && year >= currentYear - 1 && year <= currentYear + 1);
Yes no upper limit (year 9999 is fine)

2019-04-25 07:24 UTC, swuf commented on test/screens/new_weekplan_screen_test.dart
> +    await tester.pump();
one pump didn't work, pumpAndSettle did the job though, thanks (:

2019-04-25 07:34 UTC, Hylet commented on test/screens/new_weekplan_screen_test.dart
> +        findsNothing);
how about "År skal angives som fire cifre, og være indeværende år eller efter"?

2019-04-25 07:51 UTC, swuf commented on lib/blocs/new_weekplan_bloc.dart
> +          year != null && year >= currentYear - 1 && year <= currentYear + 1);
The upper limit is now 9999 (:

2019-04-25 07:52 UTC, swuf commented on lib/screens/new_weekplan_screen.dart
> +                              ? 'Titel skal bestå af mindst et tegn'
We have changed the message to: "Titel skal angives".

2019-04-25 07:56 UTC, swuf commented on lib/blocs/new_weekplan_bloc.dart
> +
Fixed.

2019-04-25 08:25 UTC, jenspetur94 requested changes

2019-04-25 08:25 UTC, jenspetur94 commented on lib/blocs/new_weekplan_bloc.dart
> +      sink.add(year != null && year >= currentYear - 1 && year <= 9999);
year should be between 1000 and 9999. 
There is no reason to have this limitation.

2019-04-25 08:25 UTC, jenspetur94 commented on lib/screens/new_weekplan_screen.dart
> +                                  'og være i fremtiden'
Again there is no reason why it should be in the future. 
Also in your bloc current year -1 is also valid which is not in the future. So this error message is misleading.

2019-04-25 08:55 UTC, swuf commented on lib/blocs/new_weekplan_bloc.dart
> +      sink.add(year != null && year >= currentYear - 1 && year <= 9999);
This is now implemented (:

2019-04-25 08:55 UTC, swuf commented on lib/screens/new_weekplan_screen.dart
> +                                  'og være i fremtiden'
The error message has been changed to 'År skal angives som fire cifre'.

2019-04-25 09:00 UTC, jenspetur94 approved these changes

2019-04-25 09:00 UTC, Tekrus approved these changes
Design is approved

2019-04-25 09:23 UTC, Tricky12321 approved these changes

2019-04-25 09:25 UTC, merged