Flutter/feature 085
aau-giraf/weekplanner-OLDUI pull request #168
Opened 2019-04-24 11:32 UTC by ChristianBroS

This closes #85 

![Button_states](https://user-images.githubusercontent.com/26706644/56656070-d4080880-6694-11e9-8c8e-3146309a011e.png)

2019-04-24 11:38 UTC, Jacob6565 commented
@aau-giraf/sw602f19 you have been assigned this. Here's your checklist. I marked @Jacob6565 as the reviewer, but you might change it as you like.
Please use the following checklist. Feel free to check it off as you go along.
**Code Design**
- [ ] Is the code in the right place? (Both in terms of folder structure and class structure)
- [ ] Could this code, to the best of your knowledge, have reused existing code?
- [ ] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [ ] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**
- [ ] Are names meaningful and self-documenting?
- [ ] Is it understandable, by reading the code, what it does?
- [ ] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [ ] Is it understandable, by reading the tests, what they do?
- [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
- [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [ ] Are error messages in the code understandable?
- [ ] Are confusing sections of code covered by comments?

**Functionality**
For this part, open the app, and test:
- [ ] Are the features that the code claims to implement, actually implemented?
- [ ] Does it look like the code has bugs?
- [ ] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**
- [ ] Are UI messages, that the user might meet, actually helpful?
- [ ] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [ ] Is there well written code in this? Remember to tell the developer!

2019-04-24 11:38 UTC, Jacob6565 commented
@aau-giraf/sw612f19 you have been assigned this. Here's your checklist. I marked @thomaslhansen as the reviewer, but you might change it as you like.
Please use the following checklist. Feel free to check it off as you go along.
**Code Design**
- [ ] Is the code in the right place? (Both in terms of folder structure and class structure)
- [ ] Could this code, to the best of your knowledge, have reused existing code?
- [ ] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [ ] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**
- [ ] Are names meaningful and self-documenting?
- [ ] Is it understandable, by reading the code, what it does?
- [ ] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [ ] Is it understandable, by reading the tests, what they do?
- [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
- [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [ ] Are error messages in the code understandable?
- [ ] Are confusing sections of code covered by comments?

**Functionality**
For this part, open the app, and test:
- [ ] Are the features that the code claims to implement, actually implemented?
- [ ] Does it look like the code has bugs?
- [ ] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**
- [ ] Are UI messages, that the user might meet, actually helpful?
- [ ] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [ ] Is there well written code in this? Remember to tell the developer!

2019-04-24 11:45 UTC, Tekrus submitted a review, later dismissed
Design is approved and looks very similar to design guide, very nice.

2019-04-25 07:25 UTC, User12837985123 requested changes

2019-04-25 07:25 UTC, Jacob6565 commented on lib/widgets/giraf_button_widget.dart
> +/// The design of the button follows the design guide on the Giraf wiki:
I don't know if these types of comments are necessary, I don't think it should a comment in the code but more in a report or alike :)

2019-04-25 07:25 UTC, Jacob6565 commented on lib/widgets/giraf_button_widget.dart
> +  @override
The standard is to not use statefull widgets but stateless, I don't know if the case is that you can' do it stateless.

2019-04-25 07:25 UTC, Jacob6565 commented on lib/widgets/giraf_button_widget.dart
> +    return null;
Wouldn't it be better to simply return some standard button instead with a default text and icon. I don't know if returning null can cause any troubles, if it can't then this is fine, otherwise, return a default.

2019-04-25 07:25 UTC, Jacob6565 commented on test/widgets/giraf_button_widget_test.dart
> +}
Would it be possible to test that the button has the correct colors when being either Default, Pressed, or Disabled?

2019-04-25 07:43 UTC, TrineHolmager commented on test/widgets/giraf_button_widget_test.dart
> +}
We would have done that, but it does not seem possible at the moment. See this: https://github.com/flutter/flutter/issues/28753

2019-04-25 07:53 UTC, TrineHolmager commented on lib/widgets/giraf_button_widget.dart
> +  @override
We have thought about it, we made it stateful since the button is changing state, but because the state only has something to do with the look of the button, stateful is preferable.

2019-04-25 08:27 UTC, swuf commented on lib/widgets/giraf_button_widget.dart
> +    return null;
Returning null doesn't cause any errors. We don't know what the default text and icon should be, if we returned that instead. (:

2019-04-25 10:32 UTC, Jacob6565 commented on test/widgets/giraf_button_widget_test.dart
> +}
Fair enough

2019-04-25 10:33 UTC, Jacob6565 commented on lib/widgets/giraf_button_widget.dart
> +    return null;
Perfect :)

2019-04-25 10:37 UTC, Jacob6565 commented on lib/widgets/giraf_button_widget.dart
> +  @override
Nice, just had to make sure you had thought about it.

2019-04-25 10:52 UTC, thomaslhansen submitted a review, later dismissed

2019-04-25 10:59 UTC, swuf commented on lib/widgets/giraf_button_widget.dart
> +/// The design of the button follows the design guide on the Giraf wiki:
It's now removed.

2019-04-25 11:06 UTC, User12837985123 approved these changes

2019-04-25 11:09 UTC, thomaslhansen approved these changes

2019-04-25 11:09 UTC, Tekrus approved these changes

2019-04-25 11:11 UTC, merged