Feature 157
aau-giraf/weekplanner-OLDUI pull request #172
Opened 2019-04-24 13:38 UTC by KVISDAOWNER

Solves #157 and #112 (they overlap).

2019-04-24 13:43 UTC, Jacob6565 commented
@aau-giraf/sw610f19 you have been assigned this. Here's your checklist. I marked @Moesgaarda as the reviewer, but you might change it as you like.
Please use the following checklist. Feel free to check it off as you go along.
**Code Design**
- [ ] Is the code in the right place? (Both in terms of folder structure and class structure)
- [ ] Could this code, to the best of your knowledge, have reused existing code?
- [ ] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [ ] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**
- [ ] Are names meaningful and self-documenting?
- [ ] Is it understandable, by reading the code, what it does?
- [ ] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [ ] Is it understandable, by reading the tests, what they do?
- [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
- [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [ ] Are error messages in the code understandable?
- [ ] Are confusing sections of code covered by comments?

**Functionality**
For this part, open the app, and test:
- [ ] Are the features that the code claims to implement, actually implemented?
- [ ] Does it look like the code has bugs?
- [ ] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**
- [ ] Are UI messages, that the user might meet, actually helpful?
- [ ] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [ ] Is there well written code in this? Remember to tell the developer!

2019-04-24 13:43 UTC, Jacob6565 commented
@aau-giraf/sw613f19 you have been assigned this. Here's your checklist. I marked @ralled96 as the reviewer, but you might change it as you like.
Please use the following checklist. Feel free to check it off as you go along.
**Code Design**
- [ ] Is the code in the right place? (Both in terms of folder structure and class structure)
- [ ] Could this code, to the best of your knowledge, have reused existing code?
- [ ] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [ ] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**
- [ ] Are names meaningful and self-documenting?
- [ ] Is it understandable, by reading the code, what it does?
- [ ] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [ ] Is it understandable, by reading the tests, what they do?
- [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
- [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [ ] Are error messages in the code understandable?
- [ ] Are confusing sections of code covered by comments?

**Functionality**
For this part, open the app, and test:
- [ ] Are the features that the code claims to implement, actually implemented?
- [ ] Does it look like the code has bugs?
- [ ] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**
- [ ] Are UI messages, that the user might meet, actually helpful?
- [ ] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [ ] Is there well written code in this? Remember to tell the developer!

2019-04-25 07:50 UTC, AlsenDev submitted a review, later dismissed
Looks good! Approved from here. 

A small note though: It would be nice in the future, if the password field of the dialog was cleared when confirming or closing the dialog.

2019-04-25 08:54 UTC, jenspetur94 requested changes
I left some comments.
We also encountered a bug where if you press the "bekræft" button multiple times it also sometimes pop the screens behind the dialog. So you can start in a weekplan and end up in choose citizen screen if you press the button enough times.

2019-04-25 08:54 UTC, jenspetur94 commented on lib/blocs/auth_bloc.dart
> +  bool loginStatus = false;
should this be a stream instead?

2019-04-25 08:54 UTC, jenspetur94 commented on lib/blocs/auth_bloc.dart
> +                       () => reactToLoginAttempt(context), 2000);
Couldn't you create a new method: reactToLoginAttemptFromPopUp that doesn't prompts the user with "Forkert brugernavn og/eller adgangskode" but instead "Forkert adgangskode"?

2019-04-25 10:04 UTC, Jacob6565 commented on lib/blocs/auth_bloc.dart
> +  bool loginStatus = false;
It is only used internally in that class, so I made it private.

2019-04-25 10:08 UTC, Jacob6565 commented on lib/blocs/auth_bloc.dart
> +                       () => reactToLoginAttempt(context), 2000);
> 
> 
> Looks good! Approved from here.
> 
> A small note though: It would be nice in the future, if the password field of the dialog was cleared when confirming or closing the dialog.

This is a known issue and have already been added as an issue here on GitHub :)

2019-04-25 10:09 UTC, Jacob6565 commented
> 
> 
> Looks good! Approved from here.
> 
> A small note though: It would be nice in the future, if the password field of the dialog was cleared when confirming or closing the dialog.

This is already a known issue and have been added to GitHub :)

2019-04-25 10:49 UTC, jenspetur94 commented on lib/blocs/auth_bloc.dart
> +  bool loginStatus = false;
👍

2019-05-03 07:57 UTC, jenspetur94 requested changes
My old comment about it popping multiple screens seems to be fixed. But encountered a new bug which i don't know if you are aware of.
It does not work to change back to guardian mode from citizen mode anymore. But it works on develop

2019-05-06 10:51 UTC, jenspetur94 submitted a review, later dismissed

2019-05-06 11:47 UTC, ralled96 requested changes
Der ser ud til at være et delay efter man trykker login? Her er hvordan det er på **branchen**.
![branch157gif](https://user-images.githubusercontent.com/24311910/57223074-24705600-7005-11e9-9849-9e533cfadfeb.gif)

Og sådan her er det på **develop**.
![developgif](https://user-images.githubusercontent.com/24311910/57223125-48339c00-7005-11e9-89b2-2170fd4419b0.gif)

2019-05-07 09:35 UTC, jenspetur94 approved these changes

2019-05-08 09:41 UTC, ralled96 approved these changes

2019-05-08 09:48 UTC, Tekrus approved these changes
Design is approved.

2019-05-08 09:50 UTC, merged