Switche between guardian and citizen mode
aau-giraf/weekplanner-OLDUI pull request #190
Opened 2019-04-25 13:55 UTC by sipman

This closes #132.

2019-04-26 06:29 UTC, sipman commented
# PO Demo
![feature_132_PO_demo](https://user-images.githubusercontent.com/6494644/56787596-51e72380-67fd-11e9-9c4c-5c3fda2a3367.gif)

2019-04-26 07:07 UTC, KVISDAOWNER commented
@aau-giraf/sw609f19 you have been assigned this. Here's your checklist. I marked @Tricky12321 as the reviewer, but you might change it as you like.
Please use the following checklist. Feel free to check it off as you go along.
**Code Design**
- [ ] Is the code in the right place? (Both in terms of folder structure and class structure)
- [ ] Could this code, to the best of your knowledge, have reused existing code?
- [ ] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [ ] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**
- [ ] Are names meaningful and self-documenting?
- [ ] Is it understandable, by reading the code, what it does?
- [ ] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [ ] Is it understandable, by reading the tests, what they do?
- [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
- [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [ ] Are error messages in the code understandable?
- [ ] Are confusing sections of code covered by comments?

**Functionality**
For this part, open the app, and test:
- [ ] Are the features that the code claims to implement, actually implemented?
- [ ] Does it look like the code has bugs?
- [ ] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**
- [ ] Are UI messages, that the user might meet, actually helpful?
- [ ] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [ ] Is there well written code in this? Remember to tell the developer!

2019-04-26 07:07 UTC, KVISDAOWNER commented
@aau-giraf/sw613 you have been assigned this. Here's your checklist. I marked @LukasRH as the reviewer, but you might change it as you like.
Please use the following checklist. Feel free to check it off as you go along.
**Code Design**
- [ ] Is the code in the right place? (Both in terms of folder structure and class structure)
- [ ] Could this code, to the best of your knowledge, have reused existing code?
- [ ] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [ ] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**
- [ ] Are names meaningful and self-documenting?
- [ ] Is it understandable, by reading the code, what it does?
- [ ] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [ ] Is it understandable, by reading the tests, what they do?
- [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
- [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [ ] Are error messages in the code understandable?
- [ ] Are confusing sections of code covered by comments?

**Functionality**
For this part, open the app, and test:
- [ ] Are the features that the code claims to implement, actually implemented?
- [ ] Does it look like the code has bugs?
- [ ] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**
- [ ] Are UI messages, that the user might meet, actually helpful?
- [ ] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [ ] Is there well written code in this? Remember to tell the developer!

2019-04-26 07:37 UTC, MStenkaer commented
As a citizen you should not be able to reorder activities.

2019-04-26 07:40 UTC, MrTasty commented
As a citizen you should not be able to go back to the citizen select screen, as this is only intended for the guardian.

2019-04-26 07:48 UTC, MrTasty commented
I don't think a citizen should be able to choose a weekplan. Isn't this only intended for the guardian?
A citizen should probably be restricted to view their own selected weekplan.

2019-04-26 08:14 UTC, Tricky12321 requested changes
Some changes

Even tough i am in citizen mode, i can change weekplan and change citizen, i do not think this should be possible, since i am no longer in Guardian mode. The back button on the weekplan should not be visible. 

Some of the tests contain a lot of code, and i would like them to be put into smaller tests, they test "too much" the tests should only try isolated features


Here is an example of how the confirm dialog could look like:
![58444046_278717726337519_14076845506953216_n](https://user-images.githubusercontent.com/10461592/56793295-f96b5280-680b-11e9-9c26-9f0d059edd30.jpg)


I would also like some comments in some of the tests, since they are not 100% self explanatory.

2019-04-26 08:14 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +              .byWidgetPredicate((Widget widget) => widget is GirafAppBar)
use find.byType(GirafAppBar) instead of byWidgetPredicate, it is smaller, and gives the same result

2019-04-26 08:14 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +        );
use find.byType

2019-04-26 08:14 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +                (Widget widget) => widget is AlertDialog
use find.byType

2019-04-26 08:14 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +
unnecessary blank lines

2019-04-26 08:14 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +
unnecessary blank lines

2019-04-26 08:14 UTC, Tricky12321 commented on lib/blocs/toolbar_bloc.dart
> +              confirmButtonText: 'Ok',
This should be "Skift" since this is the action being made

2019-04-26 08:14 UTC, Tricky12321 commented on lib/blocs/toolbar_bloc.dart
> +                  AssetImage('assets/icons/accept.png')),
This icon should properbly be the Guardian/citizen change icon instead

2019-04-26 08:14 UTC, Tricky12321 commented on lib/blocs/toolbar_bloc.dart
> +              confirmButtonIcon: const ImageIcon(
Add a description to the confirm dialog that describes what is going to happen. Maybe "Vil du skifte til borger tilstand?"

2019-04-26 08:14 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +            );
please change true to isTrue, since this is the correct to use with expect

2019-04-26 08:14 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +              .evaluate()
Use find.byType instead of WidgetPredicate

2019-04-26 08:14 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +          expect(mode == WeekplanMode.citizen, true);
Change this to expect expect(WeekplanMode.citizen, equals(mode));

2019-04-26 08:14 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +        expect(widget.appBarIcons.length == 1, true);
use equals here instead
expect(widget.appBarIcons.length, equals(1));

2019-04-26 08:14 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +          .byWidgetPredicate((Widget widget) => widget is GirafAppBar)
use `find.byType(GirafAppBar)`

2019-04-26 08:14 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +        expect(widget.appBarIcons.length > 1, true);
Use `expect(widget.appBarIcons.length, greaterThan(1));`

2019-04-26 08:14 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +                true
use isTrue

2019-04-26 08:14 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +            expect(widget.appBarIcons.length > 1, true);
Use `expect(widget.appBarIcons.length, greaterThan(1));`

2019-04-26 08:14 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +          .byWidgetPredicate((Widget widget) => widget is GirafAppBar)
use byType

2019-04-26 08:14 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +        expect(button, findsOneWidget);
This should be a test of its own, Testing to see if the IconChangeToGuardian is on the screen

2019-04-26 08:14 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +        expect(dialog, findsOneWidget);
There should be a test that just tests if the dialog is shown

2019-04-26 08:14 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +        expect(passField, findsOneWidget);
There should be a test that just tests if the passField is shown

2019-04-26 08:14 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +        expect(okBtn, findsOneWidget);
There should be a test, that tests if the okBtn works, not that it is shown, this is a test for the ConfirmDialog, and is already tested.

2019-04-26 08:14 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +              .widget;
There should be no need to use first here, since there should only ever be one. Try to use the byType instead of predicate

2019-04-26 08:14 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +            expect(widget.appBarIcons.length == 1, true);
Use expect equals(1)

2019-04-26 08:14 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +        authBloc.mode.skip(2).listen((WeekplanMode mode) async {
A comment here to describe why you use skip(2)

2019-04-26 08:34 UTC, sipman commented on test/screens/weekplan_screen_test.dart
> +              .widget;
This is needed to get the actual widget out neither

```Dart
final GirafAppBar widget = find
              .byType(GirafAppBar)
              .widget;
``` 
or

```Dart
final GirafAppBar widget = find
              .byType(GirafAppBar)
              .evaluate()
              .widget;
```

works.

2019-04-26 08:35 UTC, Tricky12321 commented on test/screens/weekplan_screen_test.dart
> +              .widget;
Okay :)

2019-04-26 11:35 UTC, sipman commented
Regarding the "back button" that allows the citizen to change week:

It is a known issue that the PO has asked to be a new issue in the upcomming sprint see #169

2019-04-26 11:42 UTC, sipman commented
@Tricky12321 I still need to fix the issue with the new "drag'n'drop" and disable it as citizen, so please wait for that before starting a new review

2019-04-30 08:06 UTC, jenspetur94 submitted a review, later dismissed

2019-04-30 09:14 UTC, Tricky12321 requested changes
Some of the changes are related to pictogram search, this is a separate issue. PO made it clear to have different pull requests for each issue

2019-04-30 09:14 UTC, Tricky12321 commented on lib/blocs/pictogram_bloc.dart
> +      });
Should this be a seperate issue?

2019-04-30 09:14 UTC, Tricky12321 commented on test/screens/pictogram_search_screen_test.dart
> +    await tester.pump(const Duration(milliseconds: 11000));
This is also related to the pictogram search, this has nothing to do with the Switch between Guardian and Citizen

2019-04-30 09:14 UTC, Tricky12321 commented on test/screens/pictogram_search_screen_test.dart
> +    await tester.pump(const Duration(milliseconds: 11000));
This is also related to the pictogram search, this has nothing to do with the Switch between Guardian and Citizen

2019-04-30 09:14 UTC, Tricky12321 commented on test/screens/pictogram_search_screen_test.dart
> +    await tester.pump(const Duration(milliseconds: 11000));
This is also related to the pictogram search, this has nothing to do with the Switch between Guardian and Citizen

2019-04-30 09:14 UTC, Tricky12321 commented on test/screens/pictogram_search_screen_test.dart
> +  });
This is also related to the pictogram search, this has nothing to do with the Switch between Guardian and Citizen

2019-04-30 10:48 UTC, Tricky12321 approved these changes

2019-05-01 08:24 UTC, LukasRH approved these changes

2019-05-01 08:58 UTC, jenspetur94 approved these changes

2019-05-01 09:40 UTC, merged