feature 057
aau-giraf/weekplanner-OLDUI pull request #192
Opened 2019-04-25 14:37 UTC by LukasRH

Closes #57 
Solves #187
As a guardian I would like to be able to remove an activity from the week plan so that cancelled activities can be removed from the citizens plan.

![qemu-system-x86_64_2019-04-25_16-32-47](https://user-images.githubusercontent.com/16747705/56744110-2a01ac80-6778-11e9-9221-b25d8efcb0a1.png)
![qemu-system-x86_64_2019-04-25_16-32-52](https://user-images.githubusercontent.com/16747705/56744112-2bcb7000-6778-11e9-950a-cb43ed649ba0.png)
![qemu-system-x86_64_2019-04-25_16-32-57](https://user-images.githubusercontent.com/16747705/56744118-2cfc9d00-6778-11e9-871b-217d4b8153b0.png)
![qemu-system-x86_64_2019-04-25_16-33-01](https://user-images.githubusercontent.com/16747705/56744123-2ec66080-6778-11e9-9cc0-76dddf6ea3ae.png)

2019-04-26 07:57 UTC, Jacob6565 commented
@aau-giraf/sw602f19 you have been assigned this. Here's your checklist. I marked @TobiasPalludan as the reviewer, but you might change it as you like.
Please use the following checklist. Feel free to check it off as you go along.
**Code Design**
- [ ] Is the code in the right place? (Both in terms of folder structure and class structure)
- [ ] Could this code, to the best of your knowledge, have reused existing code?
- [ ] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [ ] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**
- [ ] Are names meaningful and self-documenting?
- [ ] Is it understandable, by reading the code, what it does?
- [ ] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [ ] Is it understandable, by reading the tests, what they do?
- [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
- [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [ ] Are error messages in the code understandable?
- [ ] Are confusing sections of code covered by comments?

**Functionality**
For this part, open the app, and test:
- [ ] Are the features that the code claims to implement, actually implemented?
- [ ] Does it look like the code has bugs?
- [ ] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**
- [ ] Are UI messages, that the user might meet, actually helpful?
- [ ] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [ ] Is there well written code in this? Remember to tell the developer!

2019-04-26 07:57 UTC, Jacob6565 commented
@aau-giraf/sw612f19 you have been assigned this. Here's your checklist. I marked @thomaslhansen as the reviewer, but you might change it as you like.
Please use the following checklist. Feel free to check it off as you go along.
**Code Design**
- [ ] Is the code in the right place? (Both in terms of folder structure and class structure)
- [ ] Could this code, to the best of your knowledge, have reused existing code?
- [ ] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [ ] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**
- [ ] Are names meaningful and self-documenting?
- [ ] Is it understandable, by reading the code, what it does?
- [ ] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [ ] Is it understandable, by reading the tests, what they do?
- [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
- [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [ ] Are error messages in the code understandable?
- [ ] Are confusing sections of code covered by comments?

**Functionality**
For this part, open the app, and test:
- [ ] Are the features that the code claims to implement, actually implemented?
- [ ] Does it look like the code has bugs?
- [ ] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**
- [ ] Are UI messages, that the user might meet, actually helpful?
- [ ] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [ ] Is there well written code in this? Remember to tell the developer!

2019-04-26 09:00 UTC, andpaacoke submitted a review, later dismissed
PO approved 👍 It looks like you also are solving the mark/edit mode issue #59 in this PR

2019-04-26 09:05 UTC, boginw requested changes

2019-04-26 09:05 UTC, boginw commented on lib/blocs/activity_bloc.dart
> +      print(weekModel.days[0].activities[0].state);
Remove this print

2019-04-26 09:05 UTC, boginw commented on lib/blocs/toolbar_bloc.dart
> +    icons ??= <AppBarIcon, VoidCallback>{
even though this is a very smart operator, one should refrain from it, as it makes the code more difficult for others to read

2019-04-26 09:05 UTC, boginw commented on lib/blocs/toolbar_bloc.dart
> +    /*if (icons == null) {
no code comments in source

2019-04-26 09:05 UTC, boginw commented on lib/blocs/weekplan_bloc.dart
> +    return _markedActivities.value?.contains(activityModel) ?? false;
again with the operators. Readers will appreciate a more verbose structure

2019-04-26 09:05 UTC, boginw commented on lib/screens/weekplan_screen.dart
> +  void handleOnTapActivity(AsyncSnapshot<bool> snapshot, bool isMarked,
This function does not need to take a snapshot of bool, but rather an actual bool.

2019-04-26 09:05 UTC, boginw commented on lib/screens/weekplan_screen.dart
> +      WeekdayModel weekday, AsyncSnapshot<bool> snapshot) {
This function should not use snapshot of bool but rather an actual bool

2019-04-26 09:05 UTC, boginw commented on lib/screens/weekplan_screen.dart
> +      int index, WeekdayModel weekday, AsyncSnapshot<bool> snapshot) {
snapshot of bool is not needed, but rather an actual bool

2019-04-26 09:05 UTC, boginw commented on lib/screens/weekplan_screen.dart
> +  Card buildActivityCard(
should this be public?

2019-04-26 09:05 UTC, boginw commented on lib/widgets/giraf_app_bar_widget.dart
> +  //final List<AppBarIcon> appBarIcons;
commented code

2019-04-26 09:05 UTC, boginw commented on lib/widgets/pictogram_image.dart
> +
what is this documenting?

2019-04-26 09:05 UTC, boginw commented on test/blocs/toolbar_bloc_test.dart
> +    bloc.updateIcons(icons, null);
update icons should be after listen as to be sure that this is the event we are listening to

2019-04-26 09:05 UTC, boginw commented on test/blocs/toolbar_bloc_test.dart
> +    bloc.updateIcons(icons, null);
update icons should be after listen as to be sure that this is the event we are listening to

2019-04-26 09:05 UTC, boginw commented on test/blocs/weekplan_bloc_test.dart
> +    weekplanBloc.addMarkedActivity(activityModel);
event should be fired after `listen` to be sure that this is the event that the listener fires on

2019-04-26 09:05 UTC, boginw commented on test/blocs/toolbar_bloc_test.dart
>        expect(response.length, 1);
done should be in here!

2019-04-26 09:05 UTC, boginw commented on test/blocs/weekplan_bloc_test.dart
> +      expect(markedActivitiesList.length, 1);
this is never executed as the test finishes before this code is reached

2019-04-26 09:05 UTC, boginw commented on test/blocs/weekplan_bloc_test.dart
> +      expect(markedActivitiesList.length, 1);
this is never executed as the test finishes before this code is reached

2019-04-26 09:05 UTC, boginw commented on test/blocs/weekplan_bloc_test.dart
> +    weekplanBloc.addMarkedActivity(firstActivityModel);
event should be fired after `listen` to be sure that this is the event that the listener fires on

2019-04-26 09:05 UTC, boginw commented on test/blocs/weekplan_bloc_test.dart
> +    weekplanBloc.addMarkedActivity(secondActivityModel);
event should be fired after `listen` to be sure that this is the event that the listener fires on

2019-04-26 09:05 UTC, boginw commented on test/blocs/weekplan_bloc_test.dart
> +    weekplanBloc.removeMarkedActivity(firstActivityModel);
event should be fired after `listen` to be sure that this is the event that the listener fires on

2019-04-26 09:05 UTC, boginw commented on test/blocs/weekplan_bloc_test.dart
> +    weekplanBloc.clearMarkedActivities();
event should be fired after `listen` to be sure that this is the event that the listener fires on

2019-04-26 09:05 UTC, boginw commented on test/blocs/weekplan_bloc_test.dart
> +    weekplanBloc.markedActivities
event should be fired after `listen` to be sure that this is the event that the listener fires on

2019-04-26 09:05 UTC, boginw commented on test/blocs/weekplan_bloc_test.dart
> +    weekplanBloc.toggleEditMode();
event should be fired after `listen` to be sure that this is the event that the listener fires on

2019-04-26 09:05 UTC, boginw commented on test/blocs/weekplan_bloc_test.dart
> +    weekplanBloc.setWeek(weekModel, user);
event should be fired after `listen` to be sure that this is the event that the listener fires on

2019-04-26 09:05 UTC, boginw commented on test/blocs/weekplan_bloc_test.dart
> +    weekplanBloc.toggleEditMode();
event should be fired after `listen` to be sure that this is the event that the listener fires on

2019-04-26 09:05 UTC, boginw commented on test/blocs/weekplan_bloc_test.dart
> +    weekplanBloc.toggleEditMode();
event should be fired after `listen` to be sure that this is the event that the listener fires on

2019-04-26 09:05 UTC, boginw commented on test/blocs/weekplan_bloc_test.dart
> +      expect(markedActivitiesList.length, 0);
this is never executed as the test finishes before this code is reached

2019-04-26 09:05 UTC, boginw commented on test/blocs/weekplan_bloc_test.dart
> +      expect(weekplanBloc.isActivityMarked(activity), true);
this is never executed as the test finishes before this code is reached

2019-04-26 09:05 UTC, boginw commented on test/blocs/weekplan_bloc_test.dart
> +      expect(userWeekModel.week.days[Weekday.Monday.index].activities,
this is never executed as the test finishes before this code is reached

2019-04-26 09:05 UTC, boginw commented on test/blocs/weekplan_bloc_test.dart
> +    weekplanBloc.editMode.listen((bool toggle) {
this is never executed as the test finishes before this code is reached

2019-04-26 09:16 UTC, User12837985123 requested changes

2019-04-26 09:16 UTC, User12837985123 commented on lib/blocs/activity_bloc.dart
> +      print(weekModel.days[0].activities[0].state);
Is this a leftover from previous debugging?

2019-04-26 09:16 UTC, User12837985123 commented on lib/blocs/toolbar_bloc.dart
> +    }*/
Shouldn't this code be deleted? Otherwise write why not.

2019-04-26 09:16 UTC, User12837985123 commented on lib/screens/choose_citizen_screen.dart
> +                AppBarIcon.logout: null
I tested it, and since you already set AppBarIcon.logout to null in toolbar_bloc.dart on line 29, you shouldn't have to do it here. But maybe I missed a corner case.

2019-04-26 09:16 UTC, User12837985123 commented on test/blocs/weekplan_bloc_test.dart
> +    api.week = weekApi;
Is this needed considering "api.week = MockWeekApi();" in line 64?

2019-04-26 09:16 UTC, User12837985123 commented on test/blocs/weekplan_bloc_test.dart
> +    final ActivityModel activityModel = ActivityModel(
The tests are in general understandable, but this setup part could maybe need a comment. Just describing what is done.

2019-04-26 09:16 UTC, Jacob6565 commented on test/screens/weekplan_screen_test.dart
> +    await tester.pump();
Consider using pumpAndSettle() instead of multiple pumps.

2019-04-26 09:18 UTC, llundbo commented on lib/blocs/weekplan_bloc.dart
> +    return _markedActivities.value?.contains(activityModel) ?? false;
Replaced with an if statement

2019-04-26 09:26 UTC, llundbo commented on lib/screens/weekplan_screen.dart
> +  Card buildActivityCard(
changed to private

2019-04-26 09:28 UTC, MrTasty commented on lib/screens/choose_citizen_screen.dart
> +                AppBarIcon.logout: null
In the toolbar_bloc, on line 27-29 the Icons are only set to null if no AppBarIcons is sent to the function. We have made it more readable in a future commit.

2019-04-26 10:09 UTC, User12837985123 submitted a review, later dismissed

2019-04-26 10:38 UTC, MrTasty commented on lib/blocs/toolbar_bloc.dart
> +    icons ??= <AppBarIcon, VoidCallback>{
We tried changing it to icons == null, but this causes linter to fail.

![image](https://user-images.githubusercontent.com/14176903/56802406-3e997f80-6820-11e9-86dc-279b6db266fb.png)

2019-04-26 11:31 UTC, boginw commented on lib/blocs/toolbar_bloc.dart
> +    icons ??= <AppBarIcon, VoidCallback>{
Alright, maybe we might look into this in the future

2019-04-26 11:33 UTC, User12837985123 submitted a review, later dismissed

2019-04-26 11:34 UTC, boginw submitted a review, later dismissed

2019-04-26 11:34 UTC, boginw commented on lib/blocs/weekplan_bloc.dart
> +        week.weekNumber, week).listen((WeekModel onData) => null);
```suggestion
        week.weekNumber, week).listen((WeekModel onData) {});
```

2019-04-30 07:53 UTC, Alechj commented
After the merge from develop a bug presented itself where the appbar does not have the required buttons. We are looking into this right away.

2019-04-30 09:25 UTC, User12837985123 submitted a review, later dismissed

2019-04-30 09:45 UTC, andpaacoke requested changes
It would be nice if the bottom bar had the same colors as the top bar. It uses linear gradient colors which can also be seen in the design guide

2019-04-30 10:20 UTC, andpaacoke submitted a review, later dismissed
PO approved 👍

2019-04-30 12:05 UTC, User12837985123 submitted a review, later dismissed

2019-05-01 09:46 UTC, boginw submitted a review, later dismissed

2019-05-01 09:46 UTC, boginw commented on android/app/.classpath
> +	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-11/"/>
why is this included? Are we sure that all users have eclipse in their classpath?

2019-05-01 09:46 UTC, boginw commented on lib/blocs/weekplan_bloc.dart
> +  /// The stream that emits the current chosen weekplan
"currently" is the correct spelling

2019-05-01 09:46 UTC, boginw commented on lib/blocs/weekplan_bloc.dart
> +    /// Updates the weekplan in the database
no triple-slash-comments in methods. They should only be used for members

2019-05-01 09:46 UTC, boginw commented on lib/screens/weekplan_screen.dart
> +  /// The WeekplanBloc that contains the current chosen weekplan
"currently" is the correct spelling

2019-05-01 09:46 UTC, boginw commented on lib/screens/weekplan_screen.dart
> +          AppBarIcon.settings: null,
The empty callback should be safer

```suggestion
          AppBarIcon.settings: () {},
```

2019-05-01 09:46 UTC, boginw commented on lib/screens/weekplan_screen.dart
> +          AppBarIcon.logout: null
```suggestion
          AppBarIcon.logout: () {}
```

2019-05-01 09:46 UTC, boginw commented on lib/screens/weekplan_screen.dart
> +                  0.33,
1/3f would be more readable

2019-05-01 09:46 UTC, boginw commented on lib/screens/weekplan_screen.dart
> +                  0.66
2/3f would be more readable

2019-05-01 09:46 UTC, boginw commented on lib/screens/weekplan_screen.dart
> +                  Color.fromRGBO(254, 215, 108, 1),
shouldn't these colors be standardized somewhere? Or aren't the already?

2019-05-01 09:46 UTC, boginw commented on lib/screens/weekplan_screen.dart
> +                  Color.fromRGBO(253, 187, 85, 1),
shouldn't these colors be standardized somewhere? Or aren't the already?

2019-05-01 09:46 UTC, boginw commented on lib/screens/weekplan_screen.dart
> +                /// Shows dialog to confirm/cancel deletion
no triple-slash-comments in methods. They should only be used for members

2019-05-01 09:46 UTC, boginw commented on lib/screens/weekplan_screen.dart
> +                /// Closes the dialog box
no triple-slash-comments in methods. They should only be used for members

2019-05-01 09:46 UTC, boginw commented on lib/screens/weekplan_screen.dart
> +                      return _dragTargetPictogram(
for readability use else, even though strictly not necessary.

2019-05-01 09:46 UTC, boginw commented on lib/screens/weekplan_screen.dart
> +    if (activityState == ActivityState.Completed) {
this is somewhat confusing to read. I think I'd like a ternary selection more

2019-05-01 09:46 UTC, boginw commented on test/blocs/weekplan_bloc_test.dart
> +    // Add the ActivityModel to the list of marked activities.
What are you commenting?

2019-05-01 09:46 UTC, boginw commented on test/blocs/weekplan_bloc_test.dart
> +      expect(markedActivitiesList.length, 1);
this is still not fixed

2019-05-01 09:46 UTC, boginw commented on test/blocs/weekplan_bloc_test.dart
> +      expect(markedActivitiesList.length, 0);
this is still not fixed

2019-05-01 09:46 UTC, boginw commented on test/blocs/weekplan_bloc_test.dart
> +      expect(weekplanBloc.isActivityMarked(activity), true);
still not fixed

2019-05-01 09:46 UTC, boginw commented on test/blocs/weekplan_bloc_test.dart
> +    weekplanBloc.setWeek(weekModel, user);
still not fixed

2019-05-01 09:46 UTC, boginw commented on test/blocs/weekplan_bloc_test.dart
> +      expect(userWeekModel.week.days[Weekday.Monday.index].activities,
still not fixed

2019-05-01 09:46 UTC, boginw commented on test/blocs/weekplan_bloc_test.dart
> +    weekplanBloc.toggleEditMode();
still not fixed

2019-05-01 09:46 UTC, boginw commented on test/blocs/weekplan_bloc_test.dart
> +      expect(toggle, false);
this is never executed as the test finishes before this code is reached

2019-05-02 07:32 UTC, Alechj commented on lib/screens/weekplan_screen.dart
> +                  Color.fromRGBO(254, 215, 108, 1),
We agree that it should probably be standardized somewhere as it is currently not. This should probably be a seperate issue however.

2019-05-02 07:32 UTC, Alechj commented on lib/screens/weekplan_screen.dart
> +                  Color.fromRGBO(253, 187, 85, 1),
Same as above

2019-05-02 09:04 UTC, Alechj commented on test/blocs/weekplan_bloc_test.dart
> +    weekplanBloc.setWeek(weekModel, user);
The event we are testing is fired under the listener, we are testing the weekplanBloc.deleteMarkedActivities(); event and not the weekplanBloc.setWeek(weekModel, user);
We have however added async to this test as we discovered it was missing.

2019-05-02 11:34 UTC, boginw approved these changes

2019-05-02 11:34 UTC, boginw commented on lib/screens/weekplan_screen.dart
> +                  Color.fromRGBO(254, 215, 108, 1),
If you could create that issue, that would be great

2019-05-02 11:34 UTC, boginw commented on lib/screens/weekplan_screen.dart
> +                  Color.fromRGBO(253, 187, 85, 1),
If you could create that issue, that would be great

2019-05-02 11:40 UTC, User12837985123 approved these changes

2019-05-02 11:42 UTC, MrTasty commented
Issue regarding colours has been created. #226

2019-05-02 11:45 UTC, andpaacoke approved these changes

2019-05-02 11:46 UTC, merged