Feature 165
aau-giraf/weekplanner-OLDUI pull request #208
Opened 2019-04-26 11:25 UTC by TrineHolmager

This closes #165 
![image](https://user-images.githubusercontent.com/26706578/56804624-b8346c00-6826-11e9-89b5-b8d1e21f89ea.png)

2019-04-28 08:12 UTC, Tekrus submitted a review, later dismissed

2019-04-29 09:00 UTC, jenspetur94 requested changes
Shouldn't it merge into develop instead of the release branch ?

2019-05-01 08:56 UTC, jenspetur94 approved these changes

2019-05-01 08:57 UTC, Tekrus approved these changes
Design is approved again. 👺

2019-05-01 09:49 UTC, boginw approved these changes

2019-05-01 10:49 UTC, merged