Release fix 182
aau-giraf/weekplanner-OLDUI pull request #212
Opened 2019-04-29 11:44 UTC by Tricky12321

This fixed issue #182

2019-04-29 12:28 UTC, Jacob6565 commented
@aau-giraf/sw610f19 you have been assigned this. Here's your checklist. I marked @Moesgaarda as the reviewer, but you might change it as you like.
Please use the following checklist. Feel free to check it off as you go along.
**Code Design**
- [ ] Is the code in the right place? (Both in terms of folder structure and class structure)
- [ ] Could this code, to the best of your knowledge, have reused existing code?
- [ ] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [ ] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**
- [ ] Are names meaningful and self-documenting?
- [ ] Is it understandable, by reading the code, what it does?
- [ ] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [ ] Is it understandable, by reading the tests, what they do?
- [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
- [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [ ] Are error messages in the code understandable?
- [ ] Are confusing sections of code covered by comments?

**Functionality**
For this part, open the app, and test:
- [ ] Are the features that the code claims to implement, actually implemented?
- [ ] Does it look like the code has bugs?
- [ ] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**
- [ ] Are UI messages, that the user might meet, actually helpful?
- [ ] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [ ] Is there well written code in this? Remember to tell the developer!

2019-04-29 12:28 UTC, Jacob6565 commented
@aau-giraf/sw609f19 you have been assigned this. Here's your checklist. I marked @MStenkaer as the reviewer, but you might change it as you like.
Please use the following checklist. Feel free to check it off as you go along.
**Code Design**
- [ ] Is the code in the right place? (Both in terms of folder structure and class structure)
- [ ] Could this code, to the best of your knowledge, have reused existing code?
- [ ] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [ ] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**
- [ ] Are names meaningful and self-documenting?
- [ ] Is it understandable, by reading the code, what it does?
- [ ] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [ ] Is it understandable, by reading the tests, what they do?
- [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
- [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [ ] Are error messages in the code understandable?
- [ ] Are confusing sections of code covered by comments?

**Functionality**
For this part, open the app, and test:
- [ ] Are the features that the code claims to implement, actually implemented?
- [ ] Does it look like the code has bugs?
- [ ] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**
- [ ] Are UI messages, that the user might meet, actually helpful?
- [ ] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [ ] Is there well written code in this? Remember to tell the developer!

2019-04-29 12:32 UTC, MStenkaer commented on lib/blocs/weekplan_bloc.dart
> +    _userWeek.add(UserWeekModel(week, user));
Why is this added?

2019-04-29 12:47 UTC, MStenkaer requested changes
There seems to be a bug:
1. Mark an activity as marked.
2. Leave the weekplan.
3. Reopen the weekplan, and the activity is unchecked again.

Also all of the used dependencies has been changed to older versions in pubspec.

2019-04-30 08:30 UTC, jenspetur94 requested changes
we left a small comment with some commented out code.
when this and the bug is fixed we will approve

2019-04-30 08:30 UTC, jenspetur94 commented on test/blocs/weekplan_bloc_test.dart
> +      //verify(api.week.update(any, any, any, any));
Code shouldn't be commented out. It should be fixed or removed

2019-05-01 09:05 UTC, jenspetur94 submitted a review, later dismissed

2019-05-02 06:51 UTC, MStenkaer commented on lib/blocs/weekplan_bloc.dart
> +    _userWeek.add(UserWeekModel(week, user));
Now it is back

2019-05-02 08:17 UTC, TobiasPalludan commented on lib/blocs/weekplan_bloc.dart
> +    _userWeek.add(UserWeekModel(week, user));
It has now been back more times than Eminem. However, this time we won't hear from it again.

But I guess they also said that about Eminem.

2019-05-02 08:32 UTC, MStenkaer approved these changes

2019-05-02 08:59 UTC, jenspetur94 approved these changes

2019-05-02 09:03 UTC, Tekrus approved these changes
Since there's no new design part, this is approved. 👍

2019-05-02 11:29 UTC, merged