Flutter/feature 198
aau-giraf/weekplanner-OLDUI pull request #236
Opened 2019-05-07 10:37 UTC by HaZzM22

Closes #198 

![ezgif-1-0b9125626827](https://user-images.githubusercontent.com/23081828/57293366-cdca5100-70c4-11e9-8842-018e742ad28b.gif)

2019-05-07 11:14 UTC, Jacob6565 commented
@aau-giraf/sw602f19 you have been assigned this. Here's your checklist. I marked @Jacob6565 as the reviewer, but you might change it as you like.
Please use the following checklist. Feel free to check it off as you go along.
**Code Design**
- [ ] Is the code in the right place? (Both in terms of folder structure and class structure)
- [ ] Could this code, to the best of your knowledge, have reused existing code?
- [ ] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [ ] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**
- [ ] Are names meaningful and self-documenting?
- [ ] Is it understandable, by reading the code, what it does?
- [ ] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [ ] Is it understandable, by reading the tests, what they do?
- [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
- [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [ ] Are error messages in the code understandable?
- [ ] Are confusing sections of code covered by comments?

**Functionality**
For this part, open the app, and test:
- [ ] Are the features that the code claims to implement, actually implemented?
- [ ] Does it look like the code has bugs?
- [ ] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**
- [ ] Are UI messages, that the user might meet, actually helpful?
- [ ] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [ ] Is there well written code in this? Remember to tell the developer!

2019-05-07 11:14 UTC, Jacob6565 commented
@aau-giraf/sw612f19 you have been assigned this. Here's your checklist. I marked @thomaslhansen as the reviewer, but you might change it as you like.
Please use the following checklist. Feel free to check it off as you go along.
**Code Design**
- [ ] Is the code in the right place? (Both in terms of folder structure and class structure)
- [ ] Could this code, to the best of your knowledge, have reused existing code?
- [ ] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [ ] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**
- [ ] Are names meaningful and self-documenting?
- [ ] Is it understandable, by reading the code, what it does?
- [ ] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [ ] Is it understandable, by reading the tests, what they do?
- [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
- [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [ ] Are error messages in the code understandable?
- [ ] Are confusing sections of code covered by comments?

**Functionality**
For this part, open the app, and test:
- [ ] Are the features that the code claims to implement, actually implemented?
- [ ] Does it look like the code has bugs?
- [ ] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**
- [ ] Are UI messages, that the user might meet, actually helpful?
- [ ] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [ ] Is there well written code in this? Remember to tell the developer!

2019-05-07 11:50 UTC, B97theFallen submitted a review, later dismissed

2019-05-07 12:00 UTC, B97theFallen submitted a review, later dismissed

2019-05-07 12:57 UTC, User12837985123 requested changes

2019-05-07 12:57 UTC, User12837985123 commented on test/blocs/weekplans_bloc_test.dart
> +  test('Adds a weekmodel to a list of marked weekmodels', async((DoneFn done) {
Måske overser jeg noget, men kan ikke helt se at der bliver tilføjet/markeret en marked weekmodel. Det ligner blot at i tester at der er 1 marked weekmodel, men kan ikke lige se hvor i angiver den som marked.

2019-05-07 12:57 UTC, Jacob6565 commented on test/blocs/weekplans_bloc_test.dart
> +    bloc.clearMarkedWeekModels();
Burde man ikke først tjekke at markedWeekModelsList.length == 0 efter at have kaldt bloc.clearMarkedWeekModels?

2019-05-07 13:16 UTC, B97theFallen commented on lib/blocs/weekplans_bloc.dart
> +          return a.name.compareTo(b.name);
Ser ud som om i sorterer efter navnet, men det virker ikke til at den gør det i min emulator.
De er dog konsistente med hvor de placeres i forhold til hinanden.
![](https://i.imgur.com/dzT21hE.png)
Jeg har pullet siden sidste commit (commit 2c06493b783a0a85fd0733d206f154091bd54d74)

2019-05-07 13:19 UTC, LukasRH commented on lib/blocs/weekplans_bloc.dart
> +          return a.name.compareTo(b.name);
Ideen med det var også bare at få dem til at stå på den samme måde hver gang.
Så der er ikke tænkt over en konkret sotering, det er nok et andet issue.

2019-05-07 13:22 UTC, B97theFallen commented on lib/blocs/weekplans_bloc.dart
> +          return a.name.compareTo(b.name);
Okay, det er fint så.

2019-05-08 07:20 UTC, HaZzM22 commented on lib/blocs/weekplans_bloc.dart
> +          return a.name.compareTo(b.name);
Vi fikser det :D

2019-05-08 07:24 UTC, llundbo commented on test/blocs/weekplans_bloc_test.dart
> +    bloc.clearMarkedWeekModels();
Nej det det er faktisk meningen, at vi lytter hvor vi gør. Listen virker nemlig sådan, at man lytter gennem hele testen, dvs. at efter bloc.clarMarkedWeekModels bliver kaldt så tjekkes der om længden er 0 oppe i Listen :-).

2019-05-08 07:37 UTC, llundbo commented on test/blocs/weekplans_bloc_test.dart
> +  test('Adds a weekmodel to a list of marked weekmodels', async((DoneFn done) {
Der bliver tilføjet en markeret WeekModel på linje 84. Listen fungerer på samme måde som jeg beskrev i min anden comment, så det skulle være i orden.

2019-05-08 07:48 UTC, B97theFallen approved these changes

2019-05-08 07:49 UTC, User12837985123 approved these changes

2019-05-08 09:44 UTC, andpaacoke approved these changes
PO approved 👍

2019-05-08 09:45 UTC, merged