Issue 135
aau-giraf/weekplanner-OLDUI pull request #243
Opened 2019-05-10 10:37 UTC by scarress

#135 
Added the ability to upload pictures to the datebase. (though the pictogram search algorithm cannot always find them)

2019-05-10 10:45 UTC, Tricky12321 commented on lib/screens/upload_image_from_phone_screen.dart
> +  }
Why are you disposing the Bloc streams in the screen and not in the bloc?

You dont have to call dispose manually, this will be done by the garbage collector

2019-05-10 11:41 UTC, Tricky12321 requested changes
The pubspec.lock should not be comitted and the changes to pubspec.xaml should be changed

There are changes to files that are not regarded this issue, and should remain unchanged

2019-05-10 11:41 UTC, Tricky12321 commented on lib/blocs/upload_from_gallery_bloc.dart
> +        break;
Case Public is not needed as the Default case is also Public

2019-05-10 11:41 UTC, Tricky12321 commented on lib/blocs/upload_from_gallery_bloc.dart
> +  }
Maybe a comment why 512 is used at the end of the line

2019-05-10 11:41 UTC, Tricky12321 commented on lib/blocs/upload_from_gallery_bloc.dart
> +      _isUploading.add(false);
There are som TODO's here, they should properbly be solved, if they are solved, then removed.

2019-05-10 11:41 UTC, Tricky12321 commented on lib/bootstrap.dart
> +      return UploadFromGalleryBloc(i.getDependency<Api>());
Indentation

2019-05-10 11:41 UTC, Tricky12321 commented on lib/screens/pictogram_search_screen.dart
> +	  )
Indentation

2019-05-10 11:41 UTC, Tricky12321 commented on lib/screens/upload_image_from_phone_screen.dart
> +      padding: EdgeInsets.only(
Function structure should be the same

2019-05-10 11:41 UTC, Tricky12321 commented on lib/widgets/loading_spinner_widget.dart
> +        return const LoadingSpinnerWidget();
Why is the loading spinner changed?

2019-05-10 11:41 UTC, Tricky12321 commented on pubspec.yaml
> +    path: ../api_client
This should  not be a path but use the url

2019-05-10 11:52 UTC, scarress commented on lib/blocs/upload_from_gallery_bloc.dart
> +        break;
I think this `case` is still need, as if the user changes to `Private` and then back to `Public` the BLoC will not be able to handle it.

2019-05-10 12:10 UTC, scarress commented on lib/blocs/upload_from_gallery_bloc.dart
> +      _isUploading.add(false);
I was hoping that the handling of these todo's could be issues for the next semester. The method works, but if one wants to make a success popup or error popup it can be implemented here. 
But I do not mind removing it if that is better?

2019-05-10 13:17 UTC, Tricky12321 commented on lib/blocs/upload_from_gallery_bloc.dart
> +        break;
Yes it would. if there is no case to catch public, it will just return to default.

2019-05-10 13:17 UTC, Tricky12321 commented on lib/blocs/upload_from_gallery_bloc.dart
> +      _isUploading.add(false);
Then you should use the Proper TODO notation

`// TODO: <Message> <Link to issue>`

2019-05-10 14:18 UTC, Tekrus requested changes

2019-05-10 14:18 UTC, Moesgaarda commented on lib/blocs/upload_from_gallery_bloc.dart
> +      // TODO(scarress):  add proper succeses handling, https://github.com/aau-giraf/weekplanner/issues/245
the proper success should be adding it to the weekplan, is there a reason this isn't implemented?

2019-05-10 14:22 UTC, Moesgaarda commented on lib/screens/upload_image_from_phone_screen.dart
> +          'Tryk for at vælge et billed fra gallariet',
```suggestion
          'Vælg billede fra galleri',
```

2019-05-10 14:27 UTC, Tricky12321 submitted a review, later dismissed

2019-05-13 05:40 UTC, Tekrus requested changes

2019-05-13 05:40 UTC, Moesgaarda commented on lib/blocs/upload_from_gallery_bloc.dart
> +        512)); // 512 choosenas a reasonable input size.
```suggestion
        512)); // 512 bytes chosen as a reasonable input size.
```

2019-05-13 05:40 UTC, Moesgaarda commented on lib/blocs/upload_from_gallery_bloc.dart
> +  /// Checks if the input fieds are filled out
```suggestion
  /// Checks if the input fields are filled out
```

2019-05-13 05:40 UTC, Moesgaarda commented on lib/screens/upload_image_from_phone_screen.dart
> +      appBar: GirafAppBar(title: 'Tilføj fra Galleri'),
```suggestion
      appBar: GirafAppBar(title: 'Tilføj fra galleri'),
```

2019-05-13 07:24 UTC, Tricky12321 submitted a review, later dismissed

2019-05-13 07:36 UTC, Tekrus submitted a review, later dismissed

2019-05-13 07:40 UTC, Tricky12321 submitted a review, later dismissed

2019-05-13 08:20 UTC, jenspetur94 requested changes
you can choose the the picture us saved as either private or public. 
this should be in danish instead so privat or offentligt

2019-05-14 08:53 UTC, Tricky12321 submitted a review, later dismissed

2019-05-14 11:13 UTC, Tekrus approved these changes

2019-05-14 11:14 UTC, Tricky12321 approved these changes

2019-05-14 11:18 UTC, jenspetur94 approved these changes

2019-05-14 11:20 UTC, merged