Feature 157 and 112
aau-giraf/weekplanner-OLDUI pull request #244
Opened 2019-05-10 12:06 UTC by Jacob6565

This closes #157 and #112.

2019-05-10 12:17 UTC, Jacob6565 commented
@aau-giraf/sw609f19 you have been assigned this. Here's your checklist. I marked @Tricky12321 as the reviewer, but you might change it as you like.
Please use the following checklist. Feel free to check it off as you go along.
**Code Design**
- [ ] Is the code in the right place? (Both in terms of folder structure and class structure)
- [ ] Could this code, to the best of your knowledge, have reused existing code?
- [ ] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [ ] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**
- [ ] Are names meaningful and self-documenting?
- [ ] Is it understandable, by reading the code, what it does?
- [ ] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [ ] Is it understandable, by reading the tests, what they do?
- [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
- [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [ ] Are error messages in the code understandable?
- [ ] Are confusing sections of code covered by comments?

**Functionality**
For this part, open the app, and test:
- [ ] Are the features that the code claims to implement, actually implemented?
- [ ] Does it look like the code has bugs?
- [ ] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**
- [ ] Are UI messages, that the user might meet, actually helpful?
- [ ] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [ ] Is there well written code in this? Remember to tell the developer!

2019-05-10 12:17 UTC, Jacob6565 commented
@aau-giraf/sw610f19 you have been assigned this. Here's your checklist. I marked @Moesgaarda as the reviewer, but you might change it as you like.
Please use the following checklist. Feel free to check it off as you go along.
**Code Design**
- [ ] Is the code in the right place? (Both in terms of folder structure and class structure)
- [ ] Could this code, to the best of your knowledge, have reused existing code?
- [ ] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [ ] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**
- [ ] Are names meaningful and self-documenting?
- [ ] Is it understandable, by reading the code, what it does?
- [ ] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [ ] Is it understandable, by reading the tests, what they do?
- [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
- [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [ ] Are error messages in the code understandable?
- [ ] Are confusing sections of code covered by comments?

**Functionality**
For this part, open the app, and test:
- [ ] Are the features that the code claims to implement, actually implemented?
- [ ] Does it look like the code has bugs?
- [ ] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**
- [ ] Are UI messages, that the user might meet, actually helpful?
- [ ] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [ ] Is there well written code in this? Remember to tell the developer!

2019-05-10 14:24 UTC, Moesgaarda commented on lib/blocs/toolbar_bloc.dart
> +                key: Key('WrongUsernameOrPasswordDialog'));
```suggestion
                key: Key('WrongPasswordDialog'));
```

2019-05-10 14:25 UTC, Moesgaarda commented on test/screens/weekplan_screen_test.dart
> +    //authBloc.setMode(WeekplanMode.guardian);
```suggestion

```

2019-05-10 14:27 UTC, Tekrus requested changes

2019-05-10 14:27 UTC, Moesgaarda commented on test/screens/weekplan_screen_test.dart
> +    //authBloc.setMode(WeekplanMode.guardian);
```suggestion

```

2019-05-10 14:27 UTC, Moesgaarda commented on lib/blocs/toolbar_bloc.dart
> +                key: Key('WrongUsernameOrPasswordDialog'));
If this is included, remember to update the tests, it's a super minor thing tho

2019-05-12 10:04 UTC, Tekrus submitted a review, later dismissed

2019-05-12 13:17 UTC, Tricky12321 requested changes
Small changes

2019-05-12 13:17 UTC, Tricky12321 commented on lib/blocs/auth_bloc.dart
> +    _api.account.login(username, password).take(1).listen((bool status) {
take(1) should be removed, it is not needed

2019-05-12 13:17 UTC, Tricky12321 commented on test/widgets/giraf_app_bar_widget_test.dart
> +const String keyOfConfirmButton = 'SwitchToGuardianSubmit';
I would argue to put these variables in to the Main function so they are not global.

2019-05-12 14:26 UTC, Jacob6565 commented on test/widgets/giraf_app_bar_widget_test.dart
> +const String keyOfConfirmButton = 'SwitchToGuardianSubmit';
I can see they aren't even used anymore, so I will just delete them :D

2019-05-12 14:35 UTC, Jacob6565 commented on lib/blocs/auth_bloc.dart
> +    _api.account.login(username, password).take(1).listen((bool status) {
I am a bit interested. How can it then come that it is done in the authenticate method? Or should it also be removed there?

2019-05-12 14:42 UTC, Tricky12321 commented on test/widgets/giraf_app_bar_widget_test.dart
> +const String keyOfConfirmButton = 'SwitchToGuardianSubmit';
Great!

2019-05-12 14:43 UTC, Tricky12321 commented on lib/blocs/auth_bloc.dart
> +    _api.account.login(username, password).take(1).listen((bool status) {
It should also be removed there, it is part of how the API used to work, and is no longer needed anywhere

2019-05-12 18:29 UTC, Tricky12321 approved these changes

2019-05-13 05:34 UTC, Tekrus approved these changes

2019-05-13 05:49 UTC, Moesgaarda commented on lib/blocs/auth_bloc.dart
> +    _api.account.login(username, password).take(1).listen((bool status) {
I've updated it in the authenticate method in PR #247 - seems like that was the only place still using the .take(1)

2019-05-13 05:57 UTC, Eduardsen approved these changes

2019-05-13 06:31 UTC, merged