Flutter/feature 061
aau-giraf/weekplanner-OLDUI pull request #246
Opened 2019-05-10 15:27 UTC by MStenkaer

Solves #61 and #2 

<img width="358" alt="Skærmbillede 2019-05-10 kl  17 24 01" src="https://user-images.githubusercontent.com/26058664/57538309-6de3dc80-7348-11e9-85ec-1e9b24d401ce.png">
<img width="358" alt="Skærmbillede 2019-05-10 kl  17 23 24" src="https://user-images.githubusercontent.com/26058664/57538311-6de3dc80-7348-11e9-8128-1355056f8c4f.png">
<img width="356" alt="Skærmbillede 2019-05-10 kl  17 23 34" src="https://user-images.githubusercontent.com/26058664/57538312-6e7c7300-7348-11e9-9bb3-3c052dc3d87f.png">
<img width="352" alt="Skærmbillede 2019-05-10 kl  17 23 45" src="https://user-images.githubusercontent.com/26058664/57538313-6e7c7300-7348-11e9-886a-3a6f524ba189.png">

2019-05-10 16:50 UTC, LukasRH reviewed
When a timer is done, and you leave and enter the screen again it will be displayed as it has not been started, but it's not possible to start it. 

When you click on the text fields in the add timer dialog the underlying activity screen disappears.

When viewing an activity as a citizen, the timer is not visible, but there are a lot of empty space, maybe make the activity fill out the space if the timer is not there.

And then maybe look at your tests again, as it is possible for some of them to pass without it having gone through all the expect's. Ive just commented on the first one to give you an idea of how to do it.

2019-05-10 16:50 UTC, LukasRH commented on lib/blocs/timer_bloc.dart
> +  Observable<bool> get timerIsRunning => _timerRunningStream.stream;
Public members should be moved to the top

2019-05-10 16:50 UTC, LukasRH commented on lib/blocs/timer_bloc.dart
> +  Observable<bool> get timerIsInstantiated => _timerInstantiatedStream.stream;
Public members should be moved to the top

2019-05-10 16:50 UTC, LukasRH commented on lib/bootstrap.dart
> -import 'package:weekplanner/blocs/copy_activities_bloc.dart';
Why have you removed this line, to import it without `package:weekplanner` later?
We should be consistent with how we do things.

2019-05-10 16:50 UTC, LukasRH commented on lib/bootstrap.dart
> +import 'blocs/copy_activities_bloc.dart';
Imported without `package:weekplanner`

2019-05-10 16:50 UTC, LukasRH commented on lib/screens/show_activity_screen.dart
> +  StreamBuilder<WeekplanMode> buildTimer(BuildContext overallContext) {
Should this be public?

2019-05-10 16:50 UTC, LukasRH commented on lib/screens/show_activity_screen.dart
> +      BuildContext overallContext, AsyncSnapshot<WeekplanMode> modeSnapshot) {
It doesn't look like you use anything else than the data from the snapshot, so you can just take in a WeekplanMode instead of the AsyncSnapshot.

2019-05-10 16:50 UTC, LukasRH commented on lib/screens/show_activity_screen.dart
> +      AsyncSnapshot<WeekplanMode> modeSnapshot) {
Here again, just take in bool and WeekplanMode

2019-05-10 16:50 UTC, LukasRH commented on lib/screens/show_activity_screen.dart
> +  Widget _timerIsNotInitiatedWidget(
This function is 106 lines long, would it be possible to split it more out?

2019-05-10 16:50 UTC, LukasRH commented on lib/widgets/giraf_activity_time_picker_dialog.dart
> +    return SingleChildScrollView(
Why are you using a scrollview here? It doesn't look like it needs it?

2019-05-10 16:50 UTC, LukasRH commented on test/blocs/timer_bloc_test.dart
> +  Observable<ActivityModel> update(ActivityModel activity, String userId) {
In the other tests this has been done using when, but I guess this work too...

2019-05-10 16:50 UTC, LukasRH commented on test/blocs/timer_bloc_test.dart
> +    done();
done should be in the listen. The way it is now, it is possible for the test to pass before the expect have runed.

2019-05-10 16:50 UTC, LukasRH commented on test/blocs/timer_bloc_test.dart
> +    timerMock.load(activityModel, user: mockUser);
you should call the function after you have declared your listen

2019-05-10 16:50 UTC, LukasRH commented on test/screens/weekplan_screen_test.dart
> +import 'package:weekplanner/blocs/timer_bloc.dart';
You import it but you don't use it in any tests.

2019-05-10 16:50 UTC, LukasRH commented on test/screens/weekplan_screen_test.dart
> +    di.registerDependency<TimerBloc>((_) => TimerBloc(api));
You import it but you don't use it in any tests.

2019-05-10 16:56 UTC, MStenkaer commented
> When a timer is done, and you leave and enter the screen again it will be displayed as it has not been started, but it's not possible to start it.
> 
> When you click on the text fields in the add timer dialog the underlying activity screen disappears.
> 
> When viewing an activity as a citizen, the timer is not visible, but there are a lot of empty space, maybe make the activity fill out the space if the timer is not there.
> 
> And then maybe look at your tests again, as it is possible for some of them to pass without it having gone through all the expect's. Ive just commented on the first one to give you an idea of how to do it.

The reason for the second is that the keyboard will overlay the underlying activity which throws a lot of overflow exceptions.

We will have a look at the other.

2019-05-10 17:00 UTC, LukasRH commented
> > When a timer is done, and you leave and enter the screen again it will be displayed as it has not been started, but it's not possible to start it.
> > When you click on the text fields in the add timer dialog the underlying activity screen disappears.
> > When viewing an activity as a citizen, the timer is not visible, but there are a lot of empty space, maybe make the activity fill out the space if the timer is not there.
> > And then maybe look at your tests again, as it is possible for some of them to pass without it having gone through all the expect's. Ive just commented on the first one to give you an idea of how to do it.
> 
> The reason for the second is that the keyboard will overlay the underlying activity which throws a lot of overflow exceptions.
> 
> We will have a look at the other.

Ahh okay, a bit sad, but fine solution then.

2019-05-10 17:07 UTC, MStenkaer commented on lib/widgets/giraf_activity_time_picker_dialog.dart
> +    return SingleChildScrollView(
It is to overcome overflow exceptions.

2019-05-10 17:08 UTC, MStenkaer commented on test/screens/weekplan_screen_test.dart
> +import 'package:weekplanner/blocs/timer_bloc.dart';
It seems like it is not used, but it is used through dependency injection, and some tests is dependent on it.

2019-05-10 17:12 UTC, MStenkaer commented on lib/screens/show_activity_screen.dart
> +      BuildContext overallContext, AsyncSnapshot<WeekplanMode> modeSnapshot) {
It is necessary that we check if the modeSnapshot hasData, so I guess that we need the snapshot.

2019-05-10 17:13 UTC, Tekrus requested changes
Design is almost PO approved, very minor details.

2019-05-10 17:13 UTC, Moesgaarda commented on lib/screens/show_activity_screen.dart
> +                            confirmButtonText: 'stop',
```suggestion
                            confirmButtonText: 'Stop',
```

2019-05-10 17:13 UTC, Moesgaarda commented on lib/screens/show_activity_screen.dart
> +                              title: 'Slet Timer',
```suggestion
                              title: 'Slet timer',
```

2019-05-10 17:19 UTC, MStenkaer commented on test/screens/weekplan_screen_test.dart
> +    di.registerDependency<TimerBloc>((_) => TimerBloc(api));
It seems like it is not used, but it is used through dependency injection, and some tests is dependent on it.

2019-05-10 17:23 UTC, Tekrus submitted a review, later dismissed
Design is now PO approved!

2019-05-10 17:26 UTC, MStenkaer commented on lib/screens/show_activity_screen.dart
> +  Widget _timerIsNotInitiatedWidget(
I know that it is a long function, but it is, kind of, all connected, so there is no clear place to split it up. Can it be allowed this time? :D

2019-05-11 10:33 UTC, LukasRH submitted a review, later dismissed
Looks good, only have minor comments.
When you view an activity without an timer as a citizen there is still a lot of empty space where the would have been. It would be nice to see the activity fill out the entire screen if there are no timer.

2019-05-11 10:33 UTC, LukasRH commented on test/blocs/timer_bloc_test.dart
> +    expect(activityModel.timer.startTime, isNotNull);
Shouldnt these be in the listen? as these are things that happens only then the timer is added?

2019-05-11 10:33 UTC, LukasRH commented on test/blocs/timer_bloc_test.dart
> +    timerMock.initTimer();
Move this to after you have defined your listen

2019-05-11 10:33 UTC, LukasRH commented on lib/screens/show_activity_screen.dart
> +      BuildContext overallContext, AsyncSnapshot<WeekplanMode> modeSnapshot) {
It fine then, but couldn't the same be done with a null check?

2019-05-11 11:51 UTC, LukasRH submitted a review, later dismissed
Looks good now :+1: :1st_place_medal:

2019-05-11 14:35 UTC, swuf submitted a review, later dismissed
If the timer is running and you leave the activity screen and then enter it again, presses pause and then start it again, the timer will move back to where it was before you left the activity screen.
Sorry about being pedantic about the comments😃.

2019-05-11 14:35 UTC, swuf commented on lib/widgets/giraf_activity_time_picker_dialog.dart
> +    );
Don't know if input validation should accept negative numbers?

2019-05-11 14:35 UTC, swuf commented on lib/screens/show_activity_screen.dart
> +                              //the title of the timer widget
```suggestion
                              // The title of the timer widget
```

2019-05-11 14:35 UTC, swuf commented on lib/screens/show_activity_screen.dart
> +                                  //depending on whether a timer is initiated,
```suggestion
                                  // Depending on whether a timer is initiated,
```

2019-05-11 14:35 UTC, swuf commented on lib/screens/show_activity_screen.dart
> +                //if a timer is not initiated, and the app is in citizen mode,
```suggestion
                // If a timer is not initiated, and the app is in citizen mode,
```

2019-05-11 14:35 UTC, swuf commented on lib/screens/show_activity_screen.dart
> +                //nothing is shown
```suggestion
                // nothing is shown
```

2019-05-11 14:35 UTC, swuf commented on lib/screens/show_activity_screen.dart
> +                      //button has different icons and press logic depending on
```suggestion
                      // Button has different icons and press logic depending on
```

2019-05-11 14:35 UTC, swuf commented on lib/screens/show_activity_screen.dart
> +                      //whether the timer is already running.
```suggestion
                      // whether the timer is already running.
```

2019-05-11 14:35 UTC, swuf commented on lib/screens/show_activity_screen.dart
> +                          //a dialog is shown to confirm to stop the timer.
```suggestion
                          // A confirmation dialog is shown to stop the timer.
```

2019-05-11 14:35 UTC, swuf commented on lib/screens/show_activity_screen.dart
> +                //the delete button is only visible when in guardian mode,
```suggestion
                // The delete button is only visible when in guardian mode,
```

2019-05-11 14:35 UTC, swuf commented on lib/screens/show_activity_screen.dart
> +                //since a citizen should not be able to delete the timer.
```suggestion
                // since a citizen should not be able to delete the timer.
```

2019-05-11 14:35 UTC, swuf commented on lib/screens/show_activity_screen.dart
> +                            //a dialog is shown to confirm to delete the timer.
```suggestion
                            // A confirmation dialog is shown to delete the timer.
```

2019-05-11 14:35 UTC, swuf commented on lib/screens/show_activity_screen.dart
> +  /// returns a dialog where time can be decided for an activity(timer)
```suggestion
  /// Returns a dialog where time can be decided for an activity(timer)
```

2019-05-11 14:35 UTC, swuf commented on lib/widgets/giraf_activity_time_picker_dialog.dart
> +///The acitivty time picker dialog is a dialog, asking for a duration input.
```suggestion
/// The acitivty time picker dialog is a dialog, asking for a duration input.
```

2019-05-11 14:35 UTC, swuf commented on lib/widgets/giraf_activity_time_picker_dialog.dart
> +///The duration should be inserted in the textfield, and the user can either
```suggestion
/// The duration should be inserted in the textfield, and the user can either
```

2019-05-11 14:35 UTC, swuf commented on lib/widgets/giraf_activity_time_picker_dialog.dart
> +///cancel the dialog, or confirm to create the timer for the activity.
```suggestion
/// cancel the dialog, or confirm to create the timer for the activity.
```

2019-05-11 14:35 UTC, swuf commented on lib/widgets/giraf_activity_time_picker_dialog.dart
> +  ///The activity time picker takes the activity as input, to insert a timer
```suggestion
  /// The activity time picker takes the activity as input, to insert a timer
```

2019-05-11 14:35 UTC, swuf commented on lib/widgets/giraf_activity_time_picker_dialog.dart
> +  ///to the given activity.
```suggestion
  /// to the given activity.
```

2019-05-11 14:35 UTC, swuf commented on lib/screens/show_activity_screen.dart
> +  ///The widget to show, in the case that a timer has been initiated,
```suggestion
  /// The widget to show, in the case that a timer has been initiated,
```

2019-05-11 14:35 UTC, swuf commented on lib/screens/show_activity_screen.dart
> +  ///showing the progression for the timer in both citizen and guardian mode.
```suggestion
  /// showing the progression for the timer in both citizen and guardian mode.
```

2019-05-11 14:35 UTC, swuf commented on lib/screens/show_activity_screen.dart
> +  ///the widget to show, in the case that a timer has not been initiated
```suggestion
  /// The widget to show, in the case that a timer has not been initiated
```

2019-05-11 14:35 UTC, swuf commented on lib/screens/show_activity_screen.dart
> +  ///for the activity. When in guardian mode, an "addtimer" button is shown,
```suggestion
  /// for the activity. When in guardian mode, an "addTimer" button is shown,
```

2019-05-11 14:35 UTC, swuf commented on lib/screens/show_activity_screen.dart
> +  ///as citizen, nothing is shown.
```suggestion
  /// as citizen, nothing is shown.
```

2019-05-11 14:35 UTC, swuf commented on lib/screens/show_activity_screen.dart
> +  ///the buttons for the timer. Depending on whether the application is in
```suggestion
  /// The buttons for the timer. Depending on whether the application is in
```

2019-05-11 14:35 UTC, swuf commented on lib/screens/show_activity_screen.dart
> +  ///citizen or guardian mode, certain buttons are displayed.
```suggestion
  /// citizen or guardian mode, certain buttons are displayed.
```

2019-05-11 14:35 UTC, swuf commented on lib/screens/show_activity_screen.dart
> +  ///Buttons are: Play/Pause, Stop and delete
```suggestion
  /// Buttons are: Play/Pause, Stop and Delete
```

2019-05-11 15:05 UTC, MStenkaer commented
> If the timer is running and you leave the activity screen and then enter it again, presses pause and then start it again, the timer will move back to where it was before you left the activity screen.
> Sorry about being pedantic about the comments😃.

The reason for the timer starting from when you left the screen is that the database changes has not been introduced on the server, but when the server is updated, this should not be a problem any more.

2019-05-11 15:31 UTC, swuf approved these changes
Good work! 🎉

2019-05-11 15:38 UTC, LukasRH approved these changes
💯

2019-05-11 16:33 UTC, Tekrus approved these changes
PO approved

2019-05-11 17:00 UTC, merged