Feature 200
aau-giraf/weekplanner-OLDUI pull request #303
Opened 2020-02-26 13:38 UTC by ChrisKS

Fixes #200 

Sorts the week plans by week year and week number. 
![GIRAF](https://user-images.githubusercontent.com/32838871/75349716-9d4ae200-58a5-11ea-8d73-8b8733f824aa.png)

2020-02-26 13:52 UTC, holyfailer commented
Hvorfor er uge nr og årtal synlig to gange ? Der skal kun være den nederste

2020-02-26 13:58 UTC, holyfailer requested changes
Hvorfor er uge nr og årtal synlig to gange ? Der skal kun være den nederste
I skal desuden også link jeres issue til pull requesten. Dette gøres til højre under linked issues.

2020-02-26 14:11 UTC, ChrisKS commented
> Hvorfor er uge nr og årtal synlig to gange ? Der skal kun være den nederste

Vi arbejdede på issue'en før de nederste uge- og årstal blev tilføjet. De øverste tal er ugeplanens navn, hvilket vi brugte til at kunne læse uge- og årstal førhen.

2020-02-26 18:53 UTC, EsbenNedergaard commented
Hvorfor har i sorteret dem efter uge nr og års tal når der stod i jeres issue "Right now the week plans are sorted randomly. These should be consistent every time the guardian chooses a citizen. They should be sorted by how **recently they were made, so the newest ones are first.** ", så de vil gerne have de nyeste først

2020-02-27 07:50 UTC, holyfailer commented
Vi snakker nærmerer med kunden omkring dette og får en klargøring.

2020-03-02 11:47 UTC, nicolaibjerring approved these changes

2020-03-04 08:23 UTC, holyfailer approved these changes
Det er testet og virker

2020-03-04 08:31 UTC, melanieselman approved these changes

2020-03-04 08:33 UTC, merged