fixes #264
aau-giraf/weekplanner-OLDUI pull request #312
Opened 2020-03-02 14:12 UTC by MrPekar98

2020-03-03 10:54 UTC, mads-bo commented
@aau-giraf/sw615f20 @aau-giraf/sw617f20

2020-03-03 12:24 UTC, jbjarn17 commented
Vi kan ikke kompile til Android da i mangler nogle commits fra develop branchen.
En rebase fra develop branchen burde løse det problem.

2020-03-03 12:48 UTC, jbjarn17 commented
Umiddelbart har i løst opgaven.

MEN!
Lyden i har valgt bliver også brugt i sammenhæng med knapper. Dette kan eventuelt blive et problem med forståelsen hos børnene.
Men snak med PO gruppen. De må komme med en afklaring.

2020-03-03 12:51 UTC, MrPekar98 commented
@jbjarn17 Der er desværre ikke andre lyde i std library for Dart. Alternativet er at man afspiller en mp3 lyd, men det kræver selvfølgelig, at mp3 filen ligger på enheden.

2020-03-03 13:01 UTC, jbjarn17 commented
@MrPekar98 Det lyder rigtigt nok. Men det er op til PO(@aau-giraf/sw613f20 ) om der skal en anden lyd til. Men det burde ikke være et problem at smide en mp3 fil med. Bare den ikke bliver for stor.

2020-03-03 13:16 UTC, Lortemanden requested changes
The sound is not loud enough and it's the same sound as when pressing the keys. A ding sound commonly used for alarms would be preferred.

2020-03-03 21:31 UTC, Semicolon1071 submitted a review, later dismissed

2020-03-04 07:40 UTC, jbjarn17 submitted a review, later dismissed

2020-03-04 08:31 UTC, jbjarn17 submitted a review, later dismissed

2020-03-04 08:38 UTC, Semicolon1071 submitted a review, later dismissed

2020-03-04 09:00 UTC, jbjarn17 submitted a review, later dismissed

2020-03-04 09:04 UTC, Semicolon1071 submitted a review, later dismissed

2020-03-04 09:21 UTC, jollycola commented on lib/blocs/timer_bloc.dart
> +  final String audioFile = 'dingSound.mp3';
Hvor ligger filen henne?

2020-03-04 09:30 UTC, MrPekar98 commented on lib/blocs/timer_bloc.dart
> +  final String audioFile = 'dingSound.mp3';
På Google Drev. Vi har ikke commited filen, så weekplanner repo'et bliver mega stort når folk committer noget.

2020-03-04 09:30 UTC, MrPekar98 commented on lib/blocs/timer_bloc.dart
> +  final String audioFile = 'dingSound.mp3';
Man skal selv hente den og ligger den ind i assets/folder/.

2020-03-04 09:32 UTC, Lortemanden commented on lib/blocs/timer_bloc.dart
> +  final String audioFile = 'dingSound.mp3';
Hvorfor kan filen ikke være på github?

2020-03-04 09:33 UTC, MrPekar98 commented on lib/blocs/timer_bloc.dart
> +  final String audioFile = 'dingSound.mp3';
Kort sagt, det har jeg fået besked på at gøre.

2020-03-04 09:45 UTC, MrPekar98 commented on lib/blocs/timer_bloc.dart
> +  final String audioFile = 'dingSound.mp3';
Fuck it! Jeg putter det op.

2020-03-04 09:57 UTC, Semicolon1071 approved these changes

2020-03-04 10:00 UTC, jbjarn17 approved these changes

2020-03-04 10:01 UTC, Lortemanden approved these changes
PO group has tested the sound and approves.
Tested on:
Android 29 API
Pixcel C and Samsung galaxy s7

2020-03-04 10:01 UTC, merged