Update weekplan_screen.dart
aau-giraf/weekplanner-OLDUI pull request #313
Opened 2020-03-03 11:15 UTC by jrodel17

Changed to use AutoSizeText() instead of Text() for the Card widget in in weekplan_screen.dart

Fixes #233 
![Udklip](https://user-images.githubusercontent.com/34282060/75770613-9100d200-5d48-11ea-8dac-e831d2f8d776.PNG)

2020-03-03 11:49 UTC, Lortemanden requested changes
The font size is not the same for all the days when we tested on a Samsung galaxy 7 with a smaller screen. On the image mandag and torsdag clearly have a smaller font size than fredag. 
![image](https://user-images.githubusercontent.com/55434783/75772906-1edebc00-5d4d-11ea-9f1b-511227067222.png)

The names of the days also got turned into a single letter when flipping the phone to be upright. This is a problem specially since some of the letters was near unreadable.  

![image](https://user-images.githubusercontent.com/55434783/75772935-28682400-5d4d-11ea-8d32-9fe3356809df.png)

2020-03-03 12:40 UTC, jrodel17 commented
@Lortemanden Thanks. :) The problems with the weekdays turning into single letters is because you tested on a too small screen, we support a minimum of 600x1024 mdpi (ca. 7" tablet). However we can reproduce the problem of different text sizes when flipping a tablet with those sizes and will look further into how we are going to solve this. Below a snapshots of how it looks on a tablet with the minimum screen size, just in case of future reference.

![Screenshot_1583238470](https://user-images.githubusercontent.com/34282060/75776535-79c7e180-5d54-11ea-94b7-7ab1de8e464d.png)

![Screenshot_1583238744](https://user-images.githubusercontent.com/34282060/75776566-83514980-5d54-11ea-8806-0e76e07785c2.png)

2020-03-03 12:54 UTC, giano574 reviewed
Use `AutoSizeGroup` to synchronize text sizes across cards.
And set `contentPadding` to 0.

2020-03-03 12:54 UTC, giano574 commented on lib/screens/weekplan_screen.dart
>            style: const TextStyle(
```suggestion
          contentPadding: const EdgeInserts.all(0),
          style: const TextStyle(
```

2020-03-03 13:05 UTC, giano574 reviewed
> @Lortemanden Thanks. :) The problems with the weekdays turning into single letters is because you tested on a too small screen

EDIT: Sorry, my mistake.
~~This is not the case. 1920x1080, 5" screen in portrait mode exhibits this~~

2020-03-03 14:09 UTC, jrodel17 commented
@giano574 @Lortemanden Suggested changes should be implemented now and if nothing else it should be ready to merge, when approved. :)

2020-03-03 14:22 UTC, giano574 reviewed
![Screenshot_1583244977](https://user-images.githubusercontent.com/17013720/75784132-075dfe00-5d62-11ea-8ec6-b701dae5b878.png)
<sub>Picture on 600x1024 mdpi tablet</sub>

@Lortemanden 
Maybe 'fontSize' in the style should be increased? In the design guide, it says 20/30 in landscape/portrait.

2020-03-03 14:55 UTC, jrodel17 commented
@giano574 @Lortemanden I think maybe this will constitute a new issue, I believe we need to utilize the OrientationBuilder in order to build the widget tree according to the landscape/portrait orientation, to have different minimum text sizes depending on orientation. I tested with our minimum supported resolution size in portrait mode and it cuts off the text for weekdays, because it cannot support both single line and minimum font size of 20 in that resolution. (see image below)

Also it seems weird that landscape mode has a smaller minimum text size than portrait, since it would have room for larger text.
![Screenshot_1583247201](https://user-images.githubusercontent.com/34282060/75787662-55293500-5d67-11ea-9982-3e5cf3c1ac3d.png)

2020-03-03 16:01 UTC, giano574 commented
I meant changing the default size, not the minimum size. Right now it seems to be capped at 16 (which I don't understand where comes from). But yes it might be a new issue to go through all Text widgets and implement landscape/portrait specific sizes

2020-03-04 07:39 UTC, AAU-Phil submitted a review, later dismissed
PO group has reviewd the changes and approve of the dynamic text size with 0 padding.

2020-03-04 07:40 UTC, giano574 approved these changes
Approved

2020-03-04 07:52 UTC, Lortemanden approved these changes
PO group has reviewd the changes and approve of the dynamic text size with 0 padding.

2020-03-04 07:53 UTC, AAU-Phil approved these changes

2020-03-04 07:55 UTC, merged