Feature 228
aau-giraf/weekplanner-OLDUI pull request #342
Opened 2020-03-19 15:30 UTC by elaurs

fixes #228 

We have created a folder with the stylesheet (.dart) containing all the colours using RGB or hex, which can be imported for the standardised colours. All places where there are custom colours have been replaced with references to this stylesheet. The sheet only contains custom colours, where future custom colours can be added.

2020-03-21 14:26 UTC, MrPekar98 submitted a review, later dismissed

2020-03-22 14:54 UTC, Semicolon1071 submitted a review, later dismissed

2020-03-23 08:27 UTC, ghost submitted a review, later dismissed

2020-03-23 10:29 UTC, MrPekar98 submitted a review, later dismissed

2020-03-24 10:59 UTC, Andreas2762 commented on lib/style/custom_color.dart
> +/// Custom colors for the GIRAP project. New colors can be added here.
Spelling of GIRAF

2020-03-24 11:02 UTC, Semicolon1071 requested changes
Missing custom color correction in toolbar_block.dart line 278.
![toolbar_block dart](https://user-images.githubusercontent.com/17194522/77418470-38f94080-6dc7-11ea-9939-b4c68f393621.png)

2020-03-24 11:19 UTC, Semicolon1071 approved these changes

2020-03-24 11:29 UTC, MathiasKRasmussen approved these changes

2020-03-24 11:32 UTC, merged