Feature 317
aau-giraf/weekplanner-OLDUI pull request #343
Opened 2020-03-20 10:01 UTC by Simkortet

fixes #317 

The 'delete', 'cancel', and 'copy' on the weekplan screen are now disabled when no activities are selected. By agreement with the PO group we did this instead of displaying an error message.

2020-03-20 15:57 UTC, Seraph2 commented on lib/widgets/bottom_app_bar_button_widget.dart
> +  final bool isEnabled;
Is a 4 line comment necessary? The other comments are 1 line long.

2020-03-20 15:57 UTC, Seraph2 commented on lib/widgets/bottom_app_bar_button_widget.dart
> +  final Observable<bool> isEnabledStream;
Same here but 3 lines.

2020-03-23 10:53 UTC, TobiasNielsen commented
The grey out of the buttons is a bit unclear in our opinion but is of cause up to PO group to determine.

2020-03-23 10:54 UTC, T-Hauge requested changes
There could be added a screen test for the buttons disable/enable functionality

2020-03-25 10:20 UTC, EsbenNedergaard commented
> There could be added a screen test for the buttons disable/enable functionality

We tried doing this however as discussed in issue #340 there are no real tests for this screen yet, and when we tried to create the tests for our screen we ran into a problem of the WeekplanScreen not being created correctly because the appbar does not seem to contain the EditMode button which is needed for us to be able to write tests. We tried to fix this issue however could not seem to figure out a solution.

2020-03-25 10:21 UTC, EsbenNedergaard commented on lib/widgets/bottom_app_bar_button_widget.dart
> +  final bool isEnabled;
It is necessary otherwise Linter gets angry because the comment is more than 80 characters

2020-03-25 10:21 UTC, EsbenNedergaard commented on lib/widgets/bottom_app_bar_button_widget.dart
> +  final Observable<bool> isEnabledStream;
See above

2020-03-25 10:34 UTC, T-Hauge submitted a review, later dismissed

2020-03-25 10:52 UTC, EsbenNedergaard commented on lib/widgets/bottom_app_bar_button_widget.dart
> +  final bool isEnabled;
I have shortened them down a bit in the latest commit

2020-03-25 10:52 UTC, EsbenNedergaard commented on lib/widgets/bottom_app_bar_button_widget.dart
> +  final Observable<bool> isEnabledStream;
See above

2020-03-25 11:04 UTC, T-Hauge approved these changes

2020-03-26 12:21 UTC, Jakobzs approved these changes

2020-03-26 12:22 UTC, merged