Issue 307
aau-giraf/weekplanner-OLDUI pull request #344
Opened 2020-03-20 13:44 UTC by MrPekar98

fixes #307

2020-03-20 14:56 UTC, elaurs submitted a review, later dismissed

2020-03-23 13:41 UTC, Simkortet requested changes
The issue is not completed. According to the issue the play/pause button icon should change from paused to play when the timer runs out, which it currently does not. 

For the future please avoid refactoring code lines / indentation as it makes it difficult to review code changes.

2020-03-23 13:41 UTC, Simkortet commented on lib/screens/show_activity_screen.dart
> +                                return GirafConfirmDialog(
Consider moving this out in a helper function 'buildConfirmDialog' for readability

2020-03-23 13:41 UTC, Simkortet commented on test/screens/show_activity_screen_test.dart
>  }
Need tests for the new popup dialog window

2020-03-24 06:49 UTC, elaurs submitted a review, later dismissed

2020-03-24 09:12 UTC, Simkortet requested changes
When opening an activity with a timer the play button does not work. Is this intended?

2020-03-24 10:00 UTC, Vino98 requested changes
Timeren virker ved nogle aktiviteter men ikke andre. Den virker ikke ved Borger:Birkenborger1 --> ugeplan : super --> aktivitet under mandag. Den virker ved tirsdag Borger:Birkenborger1 --> ugeplan : super --> aktivitet under tirsdag. Det skal nævnes at hos nogle af os virkede det på tirsdagen under den ugeplan og borger, men ikke på alle pc'ere vi testede timeren på.
hilsen gruppe 9

2020-03-25 07:52 UTC, Simkortet submitted a review, later dismissed
Working as intended

2020-03-26 13:42 UTC, Vino98 submitted a review, later dismissed
Ja det er fikset

2020-03-26 13:50 UTC, Vino98 approved these changes

2020-03-26 14:09 UTC, Simkortet approved these changes

2020-03-26 14:10 UTC, merged