fixes_305
aau-giraf/weekplanner-OLDUI pull request #350
Opened 2020-03-25 13:52 UTC by nicolaibjerring

Fixes #305  

Fixed bug by removing duplicate keys for container widgets. Each time a week plan was marked the
key for the specific week plan was set to 'isSelectedKey'. This resulted in all week plans
having the same key ('isSelectedKey') when marking multiple, which is invalid and threw an exception in the flutter library.

2020-03-26 08:52 UTC, mathiasandresen reviewed
@aau-giraf/sw611f20 you have been assigned this. Here's your checklist. 
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [x] Is the code in the right place? (Both in terms of folder structure and class structure)
- [ ] Could this code, to the best of your knowledge, have reused existing code?
- [ ] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [ ] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**

- [x] Are names meaningful and self-documenting?
- [x] Is it understandable, by reading the code, what it does?
- [x] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [x] Is it understandable, by reading the tests, what they do?
- [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
- [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [ ] Are error messages in the code understandable?
- [ ] Are confusing sections of code covered by comments?

**Functionality**

For this part, open the app, and test:

- [x] Are the features that the code claims to implement, actually implemented?
- [ ] Does it look like the code has bugs?
- [ ] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**

- [ ] Are UI messages, that the user might meet, actually helpful?
- [ ] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [ ] Is there well written code in this? Remember to tell the developer!

2020-03-26 08:52 UTC, mathiasandresen reviewed
@aau-giraf/sw614f20 you have been assigned this. Here's your checklist. 
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [x] Is the code in the right place? (Both in terms of folder structure and class structure)
- [ ] Could this code, to the best of your knowledge, have reused existing code?
- [ ] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [ ] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**

- [ ] Are names meaningful and self-documenting?
- [x] Is it understandable, by reading the code, what it does?
- [x] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [x] Is it understandable, by reading the tests, what they do?
- [x] Do the tests cover sensible cases? Both happy paths and exception paths?
- [x] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [x] Are error messages in the code understandable?
- [ ] Are confusing sections of code covered by comments?

**Functionality**

For this part, open the app, and test:

- [x] Are the features that the code claims to implement, actually implemented?
- [ ] Does it look like the code has bugs?
- [ ] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**

- [ ] Are UI messages, that the user might meet, actually helpful?
- [ ] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [ ] Is there well written code in this? Remember to tell the developer!

2020-03-26 12:51 UTC, EsbenNedergaard requested changes
You seem to be testing the bloc instead of testing the actual screen, see other comments for more details

2020-03-26 12:51 UTC, EsbenNedergaard commented on test/screens/weekplan_selector_screen_test.dart
> +    expect(bloc.getMarkedWeekModels().contains(weekModel1), false);
Not sure that i like that this is one test because you have so many expects in there i would probably make another test where we do this check:
expect(bloc.getMarkedWeekModels().contains(weekModel1), false);
Because that makes debugging a lot easier.

2020-03-26 12:51 UTC, EsbenNedergaard commented on test/screens/weekplan_selector_screen_test.dart
> +    expect(bloc.getMarkedWeekModels().contains(weekModel1), true);
Also i would argue this test is not really correct, because you test the bloc instead of the testing the screen itself by accesing the bloc.getMarkedWeekModels, see if you cannot change this test by looking into what is changed when a week model is marked (if a new type of widget is created) and see if you can find those instead.

2020-03-26 12:51 UTC, EsbenNedergaard commented on test/screens/weekplan_selector_screen_test.dart
> +    expect(bloc.getMarkedWeekModels().contains(weekModel2), false);
Same as above you use the bloc not the screen

2020-03-26 12:51 UTC, EsbenNedergaard commented on test/screens/weekplan_selector_screen_test.dart
> +    expect(bloc.getMarkedWeekModels().contains(weekModel1), false);
same as above

2020-03-30 11:22 UTC, nicolaibjerring commented on test/screens/weekplan_selector_screen_test.dart
> +    expect(bloc.getMarkedWeekModels().contains(weekModel1), true);
We can not test the screen as for as we know.

2020-03-30 11:47 UTC, nicolaibjerring commented on test/screens/weekplan_selector_screen_test.dart
> +    expect(bloc.getMarkedWeekModels().contains(weekModel1), true);
Created a new issue for testing the screen: https://github.com/aau-giraf/weekplanner/issues/355

2020-03-30 11:49 UTC, EsbenNedergaard submitted a review, later dismissed

2020-03-30 12:22 UTC, tdybda17 requested changes

2020-03-30 12:22 UTC, tdybda17 commented on test/screens/weekplan_selector_screen_test.dart
> +  testWidgets('Marking activity and marking it again unmarks it',
```suggestion
  testWidgets('Clicking a marked activity should unmark it',
```

2020-03-30 12:22 UTC, tdybda17 commented on test/screens/weekplan_selector_screen_test.dart
> +    expect(bloc.getMarkedWeekModels().contains(weekModel1), false);
I see no problem with a large test containing multiple expectations

2020-03-30 15:25 UTC, tdybda17 approved these changes

2020-03-31 07:53 UTC, EsbenNedergaard approved these changes

2020-03-31 07:54 UTC, merged