Feature 66
aau-giraf/weekplanner-OLDUI pull request #361
Opened 2020-03-30 15:49 UTC by jbjarn17

Closes #66 

Adds a feature to create a citizen.

2020-03-31 07:51 UTC, jbjarn17 commented
When testing, change the local version of account_api -> register method.
In this method, change the line 42 from 'role': role.toString(), **INTO** 'role': role.toString().split('.').last,

This should only be temporary as this has been changed.

2020-04-14 12:35 UTC, Lortemanden requested changes
Nothing seems to happen when you press gem borger? 
Another thing is that you need to fill out the boxes a specify way before the gem borger button is'net greyed out, but it's really hard to figure out what the rules are. A example is that space is not allowed for usernames. Could there maybe be a message if you fill something out wrong? Like with a wrong year when making a weekplan?

2020-04-17 13:21 UTC, Lortemanden approved these changes

2020-04-18 08:10 UTC, Torpstitution approved these changes

2020-04-20 09:13 UTC, Simon97 approved these changes
Det ser godt ud 👍

2020-04-20 09:18 UTC, merged