Feature 245
aau-giraf/weekplanner-OLDUI pull request #392
Opened 2020-04-08 20:26 UTC by MrPekar98

2020-04-13 10:52 UTC, Laexander commented
I found two problems while testing on an emulator. When I create a new activity and try to add from the gallery, it immediately gives me a message that it succeeded or failed, before taking me to a screen to pick what picture i want for the pictogram. 
And if i use the back button on the bottom left, to return to the "tilføj fra galleri" screen, instead of choosing a picture, all subsequent messages are failed to upload messages regardless of whether the image was updated, until I return to the weekplanner screen and create a new activity again.

I press the "Tryk for at vælge billede" button and can briefly see a message popup before i go to a screen where i can select an image.
![image](https://user-images.githubusercontent.com/17495079/79113602-898a0b00-7d81-11ea-8f6f-e437b6ae8265.png)
Can see the message in the background while it is opening the next screen. 
![image](https://user-images.githubusercontent.com/17495079/79115036-184c5700-7d85-11ea-9a66-f14b28f610c1.png)



The screen for selecting images. By pressing the back button on the bottom left i go back to the previous screen with the message now displayed, even if I didn't pick a picture. 
![image](https://user-images.githubusercontent.com/17495079/79113757-ea194800-7d81-11ea-9399-1491f415427c.png)
![image](https://user-images.githubusercontent.com/17495079/79114001-74fa4280-7d82-11ea-91b9-dd4f80024993.png)

The first time i go through this process after trying to create a new activity it says it was successful.
However if I used the back button without selecting a picture on a previous attempt I get a Upload failed message, even though the upload seemingly succeeded. 
![image](https://user-images.githubusercontent.com/17495079/79114520-c7882e80-7d83-11ea-8934-03c67ce72b4a.png)

Any subsequent attempts, result in a failed message. If I go back to the weekplanner screen and create a new activity again but always choose a picture (and don't use the back button), I always get a success message
![image](https://user-images.githubusercontent.com/17495079/79114735-5301bf80-7d84-11ea-8976-4290233bde78.png)

2020-04-14 06:33 UTC, Laexander requested changes
The problems mentioned in the previous comment still exists. The messages (now only the error message) are still displayed when you press the "Tryk for at vælge billede", and using the back button still locks the system into showing error messages until you return to the weekplanner screen.

2020-04-14 09:26 UTC, Laexander submitted a review, later dismissed

2020-04-14 12:54 UTC, giano574 commented
- I get `NoSuchMethodError: The getter 'isNotEmpty' was called on null.` at `package:weekplanner/blocs/upload_from_gallery_bloc.dart:65` after picking an image (which sometimes crashes the app).
- Pressing the back button while on the "Tilføj from galleri" screen goes back to "Ny ugeplan" screen instead of "Piktogram" screen.
- There are no tests to show that the error message is shown.

Functionality is not implemented correctly. Steps to reproduce:
1. Start app and log in.
2. Select "BirkenBorger1".
3. Press "Tilføj ugeplan".
4. Press "Vælg billede til ugeplan".
5. Press "Tilføj fra galleri".
6. Turn on flight mode.
7. Press "Tryk for at vælge billede".
8. Select an image.
9. Enter a name.
10. Press "Gem billede".
11. **No error message is shown.**
12. Press on the newly added image.
13. Before the native file selection dialogue is shown, the error message is displayed.
14. Press back, and see that the error message is there.

The code for showing the dialogue should be around line 101 in `upload_image_from_phone_screen.dart`

2020-04-14 12:55 UTC, giano574 requested changes
- I get `NoSuchMethodError: The getter 'isNotEmpty' was called on null.` at `package:weekplanner/blocs/upload_from_gallery_bloc.dart:65` after picking an image (which sometimes crashes the app).
- Pressing the back button while on the "Tilføj from galleri" screen goes back to "Ny ugeplan" screen instead of "Piktogram" screen.
- There are no tests to show that the error message is shown.

Functionality is not implemented correctly. Steps to reproduce:
1. Start app and log in.
2. Select "BirkenBorger1".
3. Press "Tilføj ugeplan".
4. Press "Vælg billede til ugeplan".
5. Press "Tilføj fra galleri".
6. Turn on flight mode.
7. Press "Tryk for at vælge billede".
8. Select an image.
9. Enter a name.
10. Press "Gem billede".
11. **No error message is shown.**
12. Press on the newly added image.
13. Before the native file selection dialogue is shown, the error message is displayed.
14. Press back, and see that the error message is there.

The code for showing the dialogue should be around line 101 in `upload_image_from_phone_screen.dart`

2020-04-14 12:55 UTC, giano574 commented on lib/screens/upload_image_from_phone_screen.dart
> +                        if (uploadSuccessSnapshot.hasData &&
This code is in the wrong place

2020-04-15 08:15 UTC, Laexander requested changes
When the pictogram failed to upload, the error is not displayed at the correct time, it will only be displayed if the "gem billede" button is pressed a second time.
Steps to reproduce:

1. Start app and log in.
2. Select "BirkenBorger1".
3. Press "Tilføj ugeplan".
4. Press "Vælg billede til ugeplan".
5. Press "Tilføj fra galleri".
6. Turn on flight mode.
7. Press "Tryk for at vælge billede".
8. Select an image.
9. Enter a name.
10. Press "Gem billede".
11. No error message is shown.
12. Press "Gem billede" again
13. Error message is shown

2020-04-15 13:05 UTC, giano574 reviewed
Not so good that `_checkInternetConnection` is used. If such a feature should exist, it should be a part of the API client.

Also, in this example, an error message will only be shown if there is no internet connection. If an error happens on the server, the user doesn't have the rights to upload, etc., no error will be shown.

My suggestion is something along the lines of this (on the "Gem billede" button):
```dart
onPressed: () async {
  try {
    await _uploadFromGallery.createPictogram();
  } catch(Exception e) {
    // Show error message here.
  }
}
```
This requires changing `_uploadFromGallery.createPictogram()` to return a `Future`. That is quite easy though.

Create a `Completer<PictogramModel> completer` instance as a local variable. In the existing `listen` callback, call `completer.complete(pictogram)` as the last step. In the `onError` callback, call `completer.completeError(error)` as the last step. Return `completer.future` in the last line of the method.

Alternatively, return the `Observable` from the method, change `.listen` to `.map` and change `onError:` to `.doOnError(`. Then in the `onPressed` do
```dart
onPressed: () {
  _uploadFromGallery.createPictogram()
    .listen((_) => true,
    onError: (Object error) {
      // Show error message here.
  });
}
```

2020-04-17 14:47 UTC, giano574 commented on lib/blocs/upload_from_gallery_bloc.dart
> +    }).doOnError((Object error) {
```suggestion
    }).doOnError((Object error, StackTrace trace) {
```

2020-04-17 14:47 UTC, giano574 commented on lib/blocs/upload_from_gallery_bloc.dart
>        _pictogram.add(pictogram);
```suggestion
      return pictogram;
```

2020-04-17 14:47 UTC, giano574 commented on lib/blocs/upload_from_gallery_bloc.dart
> +  final BehaviorSubject<bool> _hasInternet =
```suggestion

```

2020-04-17 14:47 UTC, giano574 commented on lib/blocs/upload_from_gallery_bloc.dart
> +        BehaviorSubject<bool>.seeded(true);
```suggestion

```

2020-04-17 14:47 UTC, giano574 commented on lib/blocs/upload_from_gallery_bloc.dart
>    final PublishSubject<PictogramModel> _pictogram =
```suggestion

```

2020-04-17 14:47 UTC, giano574 commented on lib/blocs/upload_from_gallery_bloc.dart
> +  Observable<bool> get hasInternet => _hasInternet.stream;
```suggestion

```

2020-04-17 14:47 UTC, giano574 commented on lib/blocs/upload_from_gallery_bloc.dart
> +  /// State of upload
```suggestion

```

2020-04-21 07:21 UTC, Laexander submitted a review, later dismissed

2020-04-21 11:46 UTC, giano574 reviewed
Probably autoformat all the files also

2020-04-21 11:46 UTC, giano574 commented on lib/screens/upload_image_from_phone_screen.dart
> +            key: Key('UploadErrorKey'),
```suggestion

```
Not used.

2020-04-21 11:46 UTC, giano574 commented on test/screens/upload_image_from_phone_screen_test.dart
> +        home: UploadImageFromPhone()
```suggestion
        home: UploadImageFromPhone(),
```

2020-04-21 11:46 UTC, giano574 commented on test/screens/upload_image_from_phone_screen_test.dart
> +    expect(find.text('Fejl'), findsOneWidget);
```suggestion
    expect(find.text('Upload af pictogram fejlede.'), findsOneWidget);
```

2020-04-21 11:46 UTC, giano574 commented on lib/screens/upload_image_from_phone_screen.dart
> +        }
```suggestion
        },
```

2020-04-21 12:04 UTC, giano574 approved these changes

2020-04-22 08:16 UTC, Laexander approved these changes

2020-04-22 10:19 UTC, merged