Feature 335
aau-giraf/weekplanner-OLDUI pull request #394
Opened 2020-04-13 07:48 UTC by Lortemanden

Fixes #335

2020-04-17 07:38 UTC, gitkshn requested changes

2020-04-17 07:38 UTC, gitkshn commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +about: If you are makinng a pull request
```suggestion
about: If you are making a pull request
```

2020-04-17 07:38 UTC, gitkshn commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +To the right click link to project. Click on organistations and link to the current giraf project.
```suggestion
To the right click, link to project. Click on organizations and link to the current giraf project. 
```

2020-04-20 09:41 UTC, gitkshn approved these changes

2020-04-27 08:53 UTC, klogeat approved these changes

2020-04-27 08:58 UTC, merged