Feature 65
aau-giraf/weekplanner-OLDUI pull request #421
Opened 2020-04-17 11:44 UTC by elaurs

Fixes #65

2020-04-20 08:35 UTC, mads-bo reviewed
@aau-giraf/sw613f20 you have been assigned this. Here's your checklist.
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] The code does it introduce functionality that is not necessary for solving the problem

**Code Readability and Maintainability**

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] All new functionality is covered by tests
- [ ] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [ ] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

2020-04-20 08:35 UTC, mads-bo reviewed
@aau-giraf/sw614f20 you have been assigned this. Here's your checklist.
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [x] The code is in the right place? (Both in terms of folder structure and class structure)
- [x] This code could not, to the best of my knowledge, have reused existing code
- [x] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [x] The code does it introduce functionality that is not necessary for solving the problem

**Code Readability and Maintainability**

- [x] Names are meaningful and self-documenting
- [x] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] All new functionality is covered by tests
- [x] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [x] The features that the code claims to implement, are actually implemented
- [x] The code does not look like it has bugs
- [x] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [ ] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

2020-04-20 09:11 UTC, Lortemanden requested changes
The setting where the activity is removed doesn't work as intended. It should not be possible for the citizens to click on the activity and enter it after it's been completed. Also the colour that has been put on top of the activity don´t cover it all. 

The greyed out setting works fine. We just think it should be more clearly greyed out.

2020-04-21 13:12 UTC, Simon97 requested changes
Når man vælger at fjerne aktiviteterne, som markering for at de er færdige, kan man stadig se ikonet for at aktiviteten har en timer. Det tænker jeg umiddelbart ikke at man skal kunne? :)

2020-04-21 13:12 UTC, Simon97 commented on lib/screens/settings_screens/completed_activity_icon_selection_screen.dart
> +/// Screen where the user can select how many days to show for a citizen
```suggestion
/// Screen where the icon for completed activity can be chosen
```

2020-04-21 13:12 UTC, Simon97 commented on lib/screens/settings_screens/completed_activity_icon_selection_screen.dart
> +                          _settingsModel.completeMark.index + 1,
Hvorfor er det at der plusses med 1?
Kunne man ikke bare sammenligne den anden parameter til SettingsCheckMarkButton med 0 i stedet? :) Altså så expected i den første checkMark-knap er 0 istedet for 1?

Det samme spørgsmål er relevant for de andre CheckMarkKnapper

2020-04-27 10:40 UTC, elaurs commented
Vi har ikke kunne fjerne stregerne helt fra de fjernede completed ikoner. Det burde dog kun være iOS på den setting med at vise 5 dage, hvor stregerne ikke er væk. Det ser ud til at virke på alle de andre. Vi har lavet et nyt issue til det.

2020-04-28 10:55 UTC, Simon97 approved these changes
Antaget at PO og kunderne synes det er fint er det ligemeget, men jeg synes det virker underligt at citizens skal scrolle i nogle aktiviteter der i princippet ikke er på listen længere. Der kan ende med at være lidt langt ned til de nederste.
Men det må være op til PO, så jeg approver. :)

2020-04-28 11:00 UTC, Lortemanden approved these changes

2020-04-28 11:40 UTC, merged