Feature 348
aau-giraf/weekplanner-OLDUI pull request #424
Opened 2020-04-20 09:39 UTC by Markusjeppesen

Fixes #348

It is now possible for a guardian to select all activities with the press of a button for the given day, and also deselect all activities with the press of a button for the given day.
![weekPlanScreenFix](https://user-images.githubusercontent.com/37399254/79737336-7637ec00-82fb-11ea-8f77-76bf44f997eb.PNG)

2020-04-20 09:43 UTC, mads-bo reviewed
@aau-giraf/sw610f20 you have been assigned this. Here's your checklist.
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] The code does it introduce functionality that is not necessary for solving the problem

**Code Readability and Maintainability**

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] All new functionality is covered by tests
- [ ] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [x] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [x] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [x] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

2020-04-20 09:43 UTC, mads-bo reviewed
@aau-giraf/sw613f20 you have been assigned this. Here's your checklist.
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] The code does it introduce functionality that is not necessary for solving the problem

**Code Readability and Maintainability**

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] All new functionality is covered by tests
- [ ] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [ ] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

2020-04-20 10:00 UTC, Lortemanden requested changes
When using a 600 x 1024 screen in portrait mode the button's overflow and don´t show all the text. A possible solution could be to have two lines in the buttons instead of one and maybe change the text size. We don´t really have any concrete solution, but kinda hope you guys can come up with something.

2020-04-20 10:54 UTC, mathiasandresen commented on lib/widgets/giraf_button_widget.dart
> +    final TextStyle textStyle = TextStyle(color: Colors.black,
```suggestion
    final TextStyle textStyle = TextStyle(color: theme.GirafColors.black,
```
Brug giraf colors

2020-04-20 11:08 UTC, mathiasandresen commented on lib/screens/weekplan_screen.dart
> +import 'package:flutter/cupertino.dart';
What is cupertino used for here?

2020-04-20 11:10 UTC, mathiasandresen commented on lib/screens/weekplan_screen.dart
> -          group: _cardAutoSizeGroup,
what is the reason for removing this?

2020-04-20 11:14 UTC, mathiasandresen commented on lib/screens/weekplan_screen.dart
> -          group: _cardAutoSizeGroup,
nevermind

2020-04-20 11:15 UTC, Markusjeppesen commented on lib/screens/weekplan_screen.dart
> +import 'package:flutter/cupertino.dart';
No idea where it came from. Will be deleted

2020-04-20 11:15 UTC, mathiasandresen reviewed
Most of it looks fine, left a couple comments though

2020-04-20 11:26 UTC, Markusjeppesen commented on lib/screens/weekplan_screen.dart
> -          group: _cardAutoSizeGroup,
We are not able to test the screen if this is not removed, because of how AutoSizeText.group is implemented right. If the group is specified is caused an error when line 616:  await tester.pumpAndSettle(); in week_screen_test.dart is executed.
It is related to the issue https://github.com/leisim/auto_size_text/issues/34

2020-04-21 07:23 UTC, mathiasandresen approved these changes

2020-04-21 14:06 UTC, Lortemanden approved these changes

2020-04-21 14:32 UTC, merged