Feature 325
aau-giraf/weekplanner-OLDUI pull request #442
Opened 2020-04-27 15:08 UTC by aerlin17

Fixes #325 

There is a bug with _displayConflictDialog where it doesn't return from the dialog. This is in CopyResolveBloc when trying to copy a weekplan to the original user and choosing to overwrite. This has been made into issue #???

2020-04-28 07:21 UTC, mads-bo reviewed
@aau-giraf/sw609f20 you have been assigned this. Here's your checklist.
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [x] The code is in the right place? (Both in terms of folder structure and class structure)
- [x] This code could not, to the best of my knowledge, have reused existing code
- [x] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [x] The code does it introduce functionality that is not necessary for solving the problem

**Code Readability and Maintainability**

- [x] Names are meaningful and self-documenting
- [x] It is understandable, by reading the code, what it does
- [x] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [x] All new functionality is covered by tests
- [x] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [ ] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

2020-04-28 07:21 UTC, mads-bo reviewed
@aau-giraf/sw613f20 you have been assigned this. Here's your checklist.
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] The code does it introduce functionality that is not necessary for solving the problem

**Code Readability and Maintainability**

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] All new functionality is covered by tests
- [ ] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [ ] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

2020-04-28 07:22 UTC, aerlin17 commented
Some checks fail after fixing merge conflicts. I'm looking into this

2020-04-28 07:29 UTC, Lortemanden submitted a review, later dismissed

2020-04-28 07:55 UTC, nicolaibjerring commented
The issue states that is should be possible to copy multiple weekplans at once, however this is not how it is implemented (we can see that you specifically test to make sure it is only possible to copy exactly one weekplan). Is this because you have an agreement with the PO group or?

2020-04-28 08:01 UTC, aerlin17 commented
> 
> 
> The issue states that is should be possible to copy multiple weekplans at once, however this is not how it is implemented (we can see that you specifically test to make sure it is only possible to copy exactly one weekplan). Is this because you have an agreement with the PO group or?

Yes, PO specifically wanted it like this

2020-04-28 08:36 UTC, Lortemanden submitted a review, later dismissed

2020-04-28 12:58 UTC, Lortemanden requested changes
If you try to copy to another weekplan to another citizen, but that citizen already has a weekplan for that week it will popup and ask if you want to change or overide it. If you chose to change and change the week or year the weekplan will not be copied to the citizen. Jeg har vedlagt en video hvor jeg viser fejlen.
[Kopier_Uge_bug.zip](https://github.com/aau-giraf/weekplanner/files/4545844/Kopier_Uge_bug.zip)

2020-04-29 08:43 UTC, frederikspang requested changes

2020-04-29 08:43 UTC, frederikspang commented on android/app/build.gradle
> +        applicationId "com.example.weekplanner"
This is a pretty critical "Accidental" change.

2020-04-29 08:43 UTC, frederikspang commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> -To the right, click link to project. Click on organizations and link to the current giraf project.
?

2020-04-29 08:43 UTC, frederikspang commented on ios/Flutter/Debug.xcconfig
> -#include "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
?

2020-04-29 08:43 UTC, frederikspang commented on ios/Flutter/Release.xcconfig
> -#include "Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig"
?

2020-04-29 08:43 UTC, frederikspang commented on ios/Runner.xcworkspace/contents.xcworkspacedata
> -   </FileRef>
?

2020-04-29 08:43 UTC, frederikspang commented on lib/bootstrap.dart
> +import 'blocs/copy_resolve_bloc.dart';
Please follow `package:weekplanner` standard as above.

2020-04-29 08:43 UTC, frederikspang commented on lib/screens/choose_citizen_screen.dart
> +import 'new_citizen_screen.dart';
Please follow package:weekplanner standard as above.

2020-04-29 08:43 UTC, frederikspang commented on lib/widgets/settings_widgets/settings_section_colorThemeButton.dart
> +}
Fjernet newline?

2020-04-29 08:43 UTC, frederikspang commented on lib/widgets/settings_widgets/settings_theme_display_box.dart
> +}
Fjernet icons?

2020-04-29 08:43 UTC, frederikspang commented on pubspec.yaml
> -  material_design_icons_flutter: ^3.2.3895
Bruger vi ikke disse ikoner længere?

2020-04-29 08:43 UTC, frederikspang commented on test/screens/weekplan_selector_screen_test.dart
> -  testWidgets('Should not have Redigér and Slet buttons outside edit mode',
Er det meningen at I har slettet en del tests her?

2020-04-29 11:30 UTC, Lortemanden requested changes
Now when you try to copy a weekplan to a citizen where there already is a weekplan with the same week and year there is no prompt to change the weekplan. Instead it just copies the weekplan onto the citizen. 

The "ændr" popup should still be present.

2020-05-07 13:09 UTC, Lortemanden submitted a review, later dismissed

2020-05-08 07:42 UTC, nicolaibjerring commented
We found a bug when testing the feature, where when you copy a week plan to another citizen it sometimes removes or adds activities from/to the copied week plan, e.g. it is not the same content that is copied. Attached is a recording of the bug. 
[copyBug.zip](https://github.com/aau-giraf/weekplanner/files/4597615/copyBug.zip)

2020-05-08 08:30 UTC, nicolaibjerring submitted a review, later dismissed
We found a bug when testing the feature, where when you copy a week plan to another citizen it sometimes removes or adds activities from/to the copied week plan, e.g. it is not the same content that is copied. Attached is a recording of the bug.
[copyBug.zip](https://github.com/aau-giraf/weekplanner/files/4597929/copyBug.zip)

2020-05-11 07:51 UTC, frederikspang submitted a review, later dismissed

2020-05-11 09:30 UTC, Markusjeppesen requested changes

2020-05-11 09:30 UTC, Markusjeppesen commented on test/screens/copy_to_citizens_screen_test.dart
> +      'Test whether the it copies to citizesn when pressing the accept key',
```suggestion
      'Test whether it copies to citizens when pressing the accept button',
```

2020-05-11 09:44 UTC, Markusjeppesen approved these changes

2020-05-11 09:47 UTC, Lortemanden approved these changes

2020-05-11 09:49 UTC, merged