Feature 222
aau-giraf/weekplanner-OLDUI pull request #501
Opened 2020-05-06 11:39 UTC by mads-bo

2020-05-07 10:52 UTC, mads-bo reviewed
@aau-giraf/sw612f20 you have been assigned this. Here's your checklist.
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [x] The code is in the right place? (Both in terms of folder structure and class structure)
- [x] This code could not, to the best of my knowledge, have reused existing code
- [x] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [x] The code does it introduce functionality that is not necessary for solving the problem

**Code Readability and Maintainability**

- [x] Names are meaningful and self-documenting
- [x] It is understandable, by reading the code, what it does
- [x] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [x] All new functionality is covered by tests
- [x] It is understandable, by reading the tests, what they do
- [x] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [x] Error messages in the code are understandable
- [x] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [x] The features that the code claims to implement, are actually implemented
- [x] The code does not look like it has bugs
- [x] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [x] UI messages, that the user might meet, are actually helpful
- [x] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

2020-05-07 10:52 UTC, mads-bo reviewed
@aau-giraf/sw613f20 you have been assigned this. Here's your checklist.
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [x] The code is in the right place? (Both in terms of folder structure and class structure)
- [x] This code could not, to the best of my knowledge, have reused existing code
- [x] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [x] The code does it introduce functionality that is not necessary for solving the problem

**Code Readability and Maintainability**

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] All new functionality is covered by tests
- [ ] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [x] The features that the code claims to implement, are actually implemented
- [x] The code does not look like it has bugs
- [x] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [x] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

2020-05-07 11:31 UTC, holyfailer submitted a review, later dismissed

2020-05-07 11:35 UTC, KasperAAU commented on lib/blocs/timer_bloc.dart
> +      BehaviorSubject<List<int>>.seeded(<int>[0, 0, 0]);
Der er her lavet en liste med 3 indexes, men på linje 51-52 der bliver der omtalt at der kun bruges index 0 og 1?
Bliver det tredje index brugt?

2020-05-07 11:52 UTC, KasperAAU commented
Det virker til der mangler tests ift. time_representation_screen.dart

2020-05-07 12:43 UTC, mads-bo commented on lib/blocs/timer_bloc.dart
> +      BehaviorSubject<List<int>>.seeded(<int>[0, 0, 0]);
Vi har rettet det til, tidligere havde vi kun minutter og sekunder

2020-05-07 12:49 UTC, aerlingsson submitted a review, later dismissed

2020-05-07 12:49 UTC, holyfailer submitted a review, later dismissed

2020-05-07 12:56 UTC, Lortemanden requested changes
The icons on the screen where you chose the time representation are too big. They block some of the grey lines as shown in the picture below. This was tested with a screen size off 600x1024, which is our minimum supported screen size. 
![image](https://user-images.githubusercontent.com/55434783/81296984-f8057480-9072-11ea-9896-67ac42843d4c.png)

2020-05-11 09:52 UTC, mads-bo commented
Det seneste commit fixes #507

2020-05-11 11:06 UTC, aerlingsson submitted a review, later dismissed

2020-05-12 11:24 UTC, Lortemanden requested changes
The icons look fine in the settings menu. 
There is a problem with the digital clock. When you go to a activity with a digital clock it is set to no time as shown in the picture below.
![image](https://user-images.githubusercontent.com/55434783/81680398-4d66ca80-9453-11ea-90ef-e05cffb37ec4.png)

When the timer is then started it shows what the timer is and starts to count down as excepted.
![image](https://user-images.githubusercontent.com/55434783/81680513-75eec480-9453-11ea-958a-5caa4032cb33.png)

If you try to reset the clock it does not change the count to what it was originally and just shows where its stopped. If you then push play it resets the clock and starts to count down.  
![image](https://user-images.githubusercontent.com/55434783/81680608-a8002680-9453-11ea-9845-024999866b39.png)

A last thing is that the representation of the digital clock shown on a activity when viewing a week is chopped so you cant see the 1. 
![image](https://user-images.githubusercontent.com/55434783/81680728-dda50f80-9453-11ea-9bac-842e058ada75.png)

2020-05-12 12:17 UTC, Lortemanden submitted a review, later dismissed

2020-05-13 04:39 UTC, aerlingsson submitted a review, later dismissed

2020-05-13 09:48 UTC, Lortemanden approved these changes

2020-05-13 09:49 UTC, holyfailer approved these changes

2020-05-13 09:51 UTC, aerlingsson approved these changes

2020-05-13 09:55 UTC, merged