Fix 340
aau-giraf/weekplanner-OLDUI pull request #520
Opened 2020-05-11 11:21 UTC by EsbenNedergaard

Fixes #340

2020-05-11 11:41 UTC, mads-bo reviewed
@aau-giraf/sw612f20 you have been assigned this. Here's your checklist.
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [x] The code is in the right place? (Both in terms of folder structure and class structure)
- [x] This code could not, to the best of my knowledge, have reused existing code
- [x] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [x] The code does it introduce functionality that is not necessary for solving the problem

**Code Readability and Maintainability**

- [x] Names are meaningful and self-documenting
- [x] It is understandable, by reading the code, what it does
- [x] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [x] All new functionality is covered by tests
- [x] It is understandable, by reading the tests, what they do
- [x] The tests covers sensible cases. Both happy paths and exception paths
- [x] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [x] Error messages in the code are understandable
- [x] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [x] The features that the code claims to implement, are actually implemented
- [x] The code does not look like it has bugs
- [x] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [x] UI messages, that the user might meet, are actually helpful
- [x] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [x] There is well written code in this. Remember to tell the developer!

2020-05-11 11:41 UTC, mads-bo reviewed
@aau-giraf/sw615f20 you have been assigned this. Here's your checklist.
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] The code does it introduce functionality that is not necessary for solving the problem

**Code Readability and Maintainability**

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] All new functionality is covered by tests
- [ ] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [ ] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

2020-05-11 12:11 UTC, aerlingsson requested changes

2020-05-11 12:11 UTC, aerlingsson commented on test/mock_data.dart
> +// TODO(eneder17): få tjekket vi ikke bruger add() nogle steder
Er den her TODO lavet?

2020-05-11 12:11 UTC, aerlingsson commented on pubspec.lock
> +  flutter: ">=1.12.13+hotfix.5 <2.0.0"
Er de her version opdateringer nødvendige og har I tjekket at det ikke skaber konflikt på develop?

2020-05-11 12:14 UTC, jbjarn17 requested changes
I can't add an activity/pictogram to a week plan on your branch.
To be sure I went to the develop branch, where I was able to do it.

2020-05-11 13:31 UTC, EsbenNedergaard commented on pubspec.lock
> +  flutter: ">=1.12.13+hotfix.5 <2.0.0"
Tror det er et uheld at det er pushet ændrer det lige tilbage

2020-05-11 13:36 UTC, EsbenNedergaard commented on test/mock_data.dart
> +// TODO(eneder17): få tjekket vi ikke bruger add() nogle steder
Tror ikke vi bruger den nogle steder, men har lige mocket den aligevel for en sikkerheds skyld

2020-05-11 17:10 UTC, EsbenNedergaard commented
> I can't add an activity/pictogram to a week plan on your branch.
> To be sure I went to the develop branch, where I was able to do it.

I seem to have fixed it now

2020-05-12 06:41 UTC, jbjarn17 approved these changes

2020-05-12 07:12 UTC, aerlingsson approved these changes

2020-05-12 13:45 UTC, merged