Feature 416
aau-giraf/weekplanner-OLDUI pull request #522
Opened 2020-05-12 10:07 UTC by fors0

fixes #416

2020-05-12 10:55 UTC, mads-bo reviewed
@aau-giraf/sw607f20 you have been assigned this. Here's your checklist.
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] The code does it introduce functionality that is not necessary for solving the problem

**Code Readability and Maintainability**

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] All new functionality is covered by tests
- [ ] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [ ] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

2020-05-12 10:55 UTC, mads-bo reviewed
@aau-giraf/sw610f20 you have been assigned this. Here's your checklist.
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] The code does it introduce functionality that is not necessary for solving the problem

**Code Readability and Maintainability**

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] All new functionality is covered by tests
- [ ] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [ ] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

2020-05-12 10:56 UTC, frederikspang submitted a review, later dismissed

2020-05-12 11:13 UTC, joandrsn requested changes

2020-05-12 11:13 UTC, joandrsn commented on pubspec.lock
> +      ref: HEAD
I dont think this should be included in this PR.

2020-05-12 11:13 UTC, joandrsn commented on pubspec.lock
> +    version: "1.6.7"
Also this. Updating the packages is not part of the issue, am I correct?

2020-05-12 11:13 UTC, joandrsn commented on pubspec.lock
> +    version: "0.0.4+2"
See above.

2020-05-12 11:13 UTC, joandrsn commented on pubspec.lock
> +    version: "0.5.7+1"
See above.

2020-05-12 11:13 UTC, joandrsn commented on pubspec.lock
> +    version: "0.0.1+8"
See above.

2020-05-12 11:13 UTC, joandrsn commented on pubspec.lock
> +  flutter: ">=1.12.13+hotfix.5 <2.0.0"
See above.

2020-05-12 11:13 UTC, joandrsn commented on test/blocs/edit_weekplan_bloc_test.dart
> +      weekYear: 2021);
What happens when 2022 rolls over?
Maybe make the test such that it calculates current date + some arbitrary number of weeks?

2020-05-12 11:13 UTC, joandrsn commented on test/blocs/weekplans_bloc_test.dart
> -    weekNameModelList.add(weekNameModel3);
Why were these removed?

2020-05-12 11:13 UTC, joandrsn commented on lib/blocs/weekplan_selector_bloc.dart
> +
Remove whitespace please.

2020-05-12 11:13 UTC, joandrsn commented on test/screens/weekplan_selector_screen_test.dart
> +
Whitespace.

2020-05-12 11:13 UTC, joandrsn commented on ios/Runner/Runner.entitlements
> +<dict/>
Are you sure that this should be removed with this PR?

2020-05-12 11:13 UTC, joandrsn commented on test/blocs/weekplans_bloc_test.dart
> +
Whitespace

2020-05-12 11:13 UTC, joandrsn commented on test/blocs/weekplans_bloc_test.dart
> +
Whitespace

2020-05-12 11:18 UTC, Jakobzs requested changes

2020-05-12 11:18 UTC, Seraph2 commented on ios/Runner/Runner.entitlements
> +<dict/>
dict seems unused?

2020-05-12 11:18 UTC, Seraph2 commented on lib/blocs/weekplan_selector_bloc.dart
> +  /// This is a stream where all the FUTURE [WeekModel] are put in,
Why caps?

```suggestion
  /// This is a stream where all the future [WeekModel] are put in,
```

2020-05-12 11:18 UTC, Seraph2 commented on lib/blocs/weekplan_selector_bloc.dart
> +  /// This is a stream where all the OLD [WeekModel] are put in,
Why caps?

```suggestion
  /// This is a stream where all the old [WeekModel] are put in,
```

2020-05-12 11:18 UTC, Seraph2 commented on lib/blocs/weekplan_selector_bloc.dart
> +  /// Reformats [weekDetails] and [oldWeekDetails] in to an Observable List
```suggestion
  /// Reformats [weekDetails] and [oldWeekDetails] into an Observable List
```

2020-05-12 11:18 UTC, Seraph2 commented on lib/blocs/weekplan_selector_bloc.dart
> +    for (WeekNameModel weekPlanName in weekPlanNames) {
I'd like a brief comment on what this code does.

2020-05-12 11:18 UTC, Seraph2 commented on lib/blocs/weekplan_selector_bloc.dart
> +  bool isWeekDone(WeekNameModel weekPlan){
```suggestion
  bool isWeekDone(WeekNameModel weekPlan) {
```

2020-05-12 11:18 UTC, Seraph2 commented on lib/blocs/weekplan_selector_bloc.dart
> +       (weekPlan.weekYear == currentYear && weekPlan.weekNumber < currentWeek)){
```suggestion
       (weekPlan.weekYear == currentYear && weekPlan.weekNumber < currentWeek)) {
```

2020-05-12 11:18 UTC, Seraph2 commented on lib/blocs/weekplan_selector_bloc.dart
> +          if(localWeekModels != null && localWeekModels.contains(weekModel)){
```suggestion
          if(localWeekModels != null && localWeekModels.contains(weekModel)) {
```

2020-05-12 11:18 UTC, Seraph2 commented on lib/blocs/weekplan_selector_bloc.dart
> +    if (weekPlan.weekYear < currentYear ||
Can't this code be rewritten to:
```
if (weekPlan.weekYear <= currentYear && weekPlan.weekNumber < currentWeek) { ...
```
You are both testing whether it is less than, or equal to, so in my opinion it makes sense to use the <= operator.

2020-05-12 11:18 UTC, Seraph2 commented on lib/blocs/weekplan_selector_bloc.dart
> +  /// if its an old weekplan or an upcomming
```suggestion
  /// if it's an old weekplan or an upcoming
```

2020-05-12 11:18 UTC, Seraph2 commented on lib/blocs/weekplan_selector_bloc.dart
> +        oldLocalWeekModels.contains(weekModel)){
Indentation looks strange here to me.

2020-05-12 11:18 UTC, Seraph2 commented on lib/screens/weekplan_selector_screen.dart
> +      BuildContext context, Stream<List<WeekModel>> weekModels, bool current) {
"current" What?

2020-05-12 11:18 UTC, Seraph2 commented on pubspec.lock
> +      ref: HEAD
Is this intentional?

2020-05-12 11:18 UTC, Seraph2 commented on test/screens/weekplan_selector_screen_test.dart
> +
Remove newline

2020-05-12 11:18 UTC, Seraph2 commented on test/blocs/weekplans_bloc_test.dart
> +
Remove newline

2020-05-12 11:18 UTC, Seraph2 commented on lib/blocs/weekplan_selector_bloc.dart
> +
Remove newlines

2020-05-12 11:18 UTC, Seraph2 commented on lib/blocs/weekplan_selector_bloc.dart
> +    int weekNum = ((dayOfYear + 6) / 7).round();
In my opinion, don't use magic variables like 6 and 7 despite their purpose being semi-clear. Create a variable at that top that cannot be modified, and give it a relevant name.

2020-05-12 12:27 UTC, sabj17 commented on lib/blocs/weekplan_selector_bloc.dart
> +    if (weekPlan.weekYear < currentYear ||
weekPlan.weekYear <= currentYear && weekPlan.weekNumber < currentWeek
is not equivalent to
weekPlan.weekYear < currentYear || (weekPlan.weekYear == currentYear && weekPlan.weekNumber < currentWeek)

2020-05-12 12:39 UTC, Seraph2 commented on lib/blocs/weekplan_selector_bloc.dart
> +    if (weekPlan.weekYear < currentYear ||
I see it now yeah, it makes sense.

2020-05-12 13:02 UTC, joandrsn requested changes
Much better, but I still have some questions.

2020-05-12 13:02 UTC, joandrsn commented on test/blocs/edit_weekplan_bloc_test.dart
> +    bloc.onYearChanged.add('2021');
Okay. Please help me understand here. Previously this file had many changes.
I asked if the change to the `weekYear` was supposed to be hardcoded differently and suggesting if it instead should be dynamic.

Now you made the change, but only on 1 of the 2 places where this comment was relevant and minimized the changes to the file.

I assumed that this change was important for this PR, but since you did not catch it the 2nd time, I guess it's not that important after all?

Are any of the changes in this file relevant to the PR?
Are the tests failing without the change?

2020-05-12 13:02 UTC, joandrsn commented on pubspec.lock
> +    version: "0.6.6+1"
Previously in this PR, you had many changes to `pubspec.lock`. Now you have removed 90% of the changes to the file, but these still remain. 

Are any of the changes to `pubspec.lock` important to this PR?

2020-05-12 13:04 UTC, Seraph2 commented on test/blocs/edit_weekplan_bloc_test.dart
> +    bloc.onYearChanged.add('2021');
Will this test also fail if we are in year 2021?

2020-05-12 13:07 UTC, Seraph2 commented on pubspec.lock
> +  shared_preferences_web:
Is this package being used? I cannot find any reference to its utilization.

2020-05-13 07:41 UTC, fors0 commented on test/blocs/edit_weekplan_bloc_test.dart
> +    bloc.onYearChanged.add('2021');
Det er en smutter, at vi ikke fik den fixet i samme omgang

2020-05-13 07:42 UTC, fors0 commented on pubspec.lock
> +    version: "0.6.6+1"
It's completely unintentional - there should be no changes in the pubspec

2020-05-13 07:45 UTC, fors0 commented on pubspec.lock
> +  shared_preferences_web:
No idea how we added that. There should be no changes in pubspec

2020-05-13 08:55 UTC, joandrsn approved these changes

2020-05-13 08:58 UTC, Jakobzs approved these changes

2020-05-13 09:05 UTC, frederikspang approved these changes

2020-05-13 09:06 UTC, merged