Feature 495: Changed pictogram box changes
aau-giraf/weekplanner-OLDUI pull request #559
Opened 2020-09-24 13:10 UTC by Riasalit

fixes #495 
The Issue was that some text was cut off when it spanned multiple lines, as the box size was static. this has been solved by allowing the pictogram box to be as high as the elements within and set the max amount of lines for the text to 2.

this made smaller words split into 2 lines, which was further solved by only allowing the text to be 1 line of only 1 word was present in the string.

2020-09-29 06:47 UTC, AdrianPlesner requested changes
**Code Design**
​
- [x] The code is in the right place? (Both in terms of folder structure and class structure)
- [x] This code could not, to the best of my knowledge, have reused existing code
- [x] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [x] The code does not introduce functionality that is necessary for solving the problem
​
**Code Readability and Maintainability**
​
- [x] Names are meaningful and self-documenting
- [x] It is understandable, by reading the code, what it does
- [x] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] All new functionality is covered by tests
- [ ] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [x] Error messages in the code are understandable
- [x] Confusing sections of code are covered by comments
​
**Functionality**
​
For this part, open the app, and test:
​
- [ ] The features that the code claims to implement, are actually implemented
- [x] The code does not look like it has bugs
- [x] All the new screens are reachable through in-app navigation
​
**Points for Discussion and Reflection**
​
- [x] UI messages, that the user might meet, are actually helpful
- [x] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [x] There is well written code in this. Remember to tell the developer!

Hvis der er ét langt ord bliver den stadig ikke delt op, husk at tage højde for at bredden kan være forskellig på forskellige enheder. 
Desuden mangler der test.

2020-09-30 06:27 UTC, Riasalit commented
Ved virkelig ikke hvordan man skal kunne tæste at størelsen på en tekstbox vokser nedad, når et ord er for langt til en linje når det kommer an på størrelsen af skærmen, boksen, teksten. altså alt der er lavet er at max lines i elementet der auto justere det hele, er ændret til at være slightly dynamisk og så kan tekstboxen vokse

2020-10-01 08:03 UTC, AdrianPlesner commented on lib/widgets/pictogram_text.dart
> +int textLines(String pictogramText, BuildContext context) {
Jeg tænker godt at denne funktion kan testes. 🙂

2020-10-01 10:51 UTC, Riasalit commented on lib/widgets/pictogram_text.dart
> +int textLines(String pictogramText, BuildContext context) {
Problemet er bare at alle test i programmet lige nu er widget tests, det vil sige at der så skal laves det widget hvor det kode ligger i, så jeg kan muligvis godt sige at den har en bestemt størelse og så give det en lang nok test til at det bliver splittet. men expect metoden bruger så en fidner der kan lede efter elementer enten efter en tekst, et tag, eller en type. og de vil alle retunere true uanset om der er 2 eller 1 linje da teksten er der, uanset om det kan ses eller ej

2020-10-08 13:30 UTC, AdrianPlesner approved these changes

2020-10-19 07:46 UTC, Emil7370 approved these changes

2020-10-19 07:55 UTC, LivHolm commented
Please use the following checklist @Emil7370 . Please check it off as you go along.
​
**Code Design**
​
- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] The code does not introduce functionality that is unnecessary for solving the problem
​
**Code Readability and Maintainability**
​
- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] All new functionality is covered by tests
- [ ] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments
​
**Functionality**
​
For this part, open the app, and test:
​
- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation
​
**Points for Discussion and Reflection**
​
- [ ] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

2020-10-29 11:51 UTC, merged