feature #471: Created error messages for already existing users
aau-giraf/weekplanner-OLDUI pull request #561
Opened 2020-09-28 11:14 UTC by Riasalit

fixes #471 
fixes #428 
created an error handler in new_citizen_screen.dart to handle errors from the client_api
the error messages are in English as that is what the web_api suplies

2020-09-28 13:50 UTC, Oliversrensen submitted a review, later dismissed

2020-09-29 07:02 UTC, ggAlexS approved these changes
Looks fine to me, men test'ne er broken

2020-09-29 07:18 UTC, ggAlexS requested changes
Vil gerne have testene passer

2020-09-29 08:33 UTC, ggAlexS approved these changes
Seems good to me now

2020-09-29 09:16 UTC, Oliversrensen approved these changes

2020-09-30 06:16 UTC, merged