Releasefix 570: Created class for converting Error codes to Danish messages
aau-giraf/weekplanner-OLDUI pull request #574
Opened 2020-09-30 09:39 UTC by Riasalit

Fixes #570 
The class can be expanded with more of the error codes from the ErrorKey class such that it can be used with all communication with the api_client

![image](https://user-images.githubusercontent.com/28717453/94669384-73610e80-0311-11eb-8842-9f7100562542.png)

2020-09-30 10:14 UTC, kbwsoorensen commented
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] The code does not introduce functionality that is necessary for solving the problem

**Code Readability and Maintainability**

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] All new functionality is covered by tests
- [ ] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [ ] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

2020-09-30 10:32 UTC, twaxlol reviewed
Mangler tests.

2020-09-30 17:23 UTC, ggAlexS requested changes
Syntes godt der kunne være nogle tests

2020-10-01 07:58 UTC, twaxlol reviewed
Smukt!

2020-10-01 07:59 UTC, twaxlol approved these changes

2020-10-01 08:00 UTC, twaxlol approved these changes

2020-10-01 08:49 UTC, ggAlexS approved these changes

2020-10-01 11:09 UTC, merged