Feature/418 As a guardian i would like to be able to search for a specific weekplan so it is easier for me to find
aau-giraf/weekplanner-OLDUI pull request #593
Opened 2020-10-12 12:50 UTC by ggAlexS

2020-10-13 06:56 UTC, Determinatoro commented
Please use the following checklist, @LJensen0403. Feel free to check it off as you go along.

**Code Design**
- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is necessary for solving the problem

**Code Readability and Maintainability**
- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] All new functionality is covered by tests
- [ ] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [ ] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

2020-10-13 06:56 UTC, Determinatoro commented
Please use the following checklist, @ProgDaniel. Feel free to check it off as you go along.

**Code Design**
- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is necessary for solving the problem

**Code Readability and Maintainability**
- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] All new functionality is covered by tests
- [ ] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [ ] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

2020-10-13 07:42 UTC, LJensen0403 requested changes
Hard-coded test database connection

2020-10-13 08:02 UTC, JeppeKLau commented
> 
> 
> Hard-coded test database connection

Do elaborate

2020-10-13 09:14 UTC, LJensen0403 commented
Correct me if I'm wrong, but the line "SERVER_HOST": "http://10.0.2.2:5000" located in environment, means it connects to a database running locally. If I'm wrong, or if this is not an issue, I'd be more than happy to accept the pull request, as everything else looks good.

2020-10-13 09:21 UTC, ProgDaniel commented
The "pubspec.lock", "pubspec.yaml", and "environment.json" should not be changed if it is not necessary. You should remember to clear changes in those files before you commit.

2020-10-13 10:22 UTC, JeppeKLau commented
> 
> 
> The "pubspec.lock", "pubspec.yaml", and "environment.json" should not be changed if it is not necessary. You should remember to clear changes in those files before you commit.

I looked at the changes in `pubspec.yaml` and they are in order now. The added dependency `flappy_search_bar` is the implemented search bar used for the searching. `environment.json` should be reset. `pubspec.lock` automatically updates when running `flutter pub get` as this file tells which versions of the packages it was able to get a hold of.

2020-10-13 10:38 UTC, LJensen0403 submitted a review, later dismissed

2020-10-13 10:58 UTC, ProgDaniel commented
If a user has no "Overstående uger", that is Overstående uger has no items in it, then the searching won't progress, and it wont find any weekplans, even if there are any in the current week. (The loading symbol will remain swirling)

The created test, "search for weekplan", also does not pass.

2020-10-13 11:14 UTC, ProgDaniel commented on lib/widgets/giraf_app_bar_widget.dart
> +        preferredSize = const Size.fromHeight(53.0),
Is there a reason for this top-bar size change?

2020-10-15 07:54 UTC, ProgDaniel requested changes
Remember to discard "environments.json" before you commit, again 

Remove outcommented blocks of code

2020-10-15 10:14 UTC, ProgDaniel commented
The same bug as before still exists: if either new weeks or old weeks (overstående uger) does not have any weeks in it, you cannot search
![image](https://user-images.githubusercontent.com/43956461/96110232-de990c00-0edf-11eb-9537-39008b4477a0.png)

The refactoring of the Observable was part of another issue, so you shouldnt change it in this issue, unless its necessary for the code to work.

2020-10-15 11:04 UTC, JeppeKLau commented
> 
> 
> The same bug as before still exists: if either new weeks or old weeks (overstående uger) does not have any weeks in it, you cannot search
> ![image](https://user-images.githubusercontent.com/43956461/96110232-de990c00-0edf-11eb-9537-39008b4477a0.png)
> 
> The refactoring of the Observable was part of another issue, so you shouldnt change it in this issue, unless its necessary for the code to work.

Then you need to make sure you have recompiled the app after pulling the latest changes, because it works on my end when using a user with either no plans at all, only current plans, or both current and ended plans.

I only tried changing the Observable class to try and make the streams work better. It was simply part of the trial and error phase of getting this feature to work. If you would like I can change it back to Observable, but I don't really see a reason to given that it will be refactored by someone else.

2020-10-16 12:41 UTC, ProgDaniel submitted a review, later dismissed

2020-10-19 06:20 UTC, LJensen0403 submitted a review, later dismissed

2020-10-19 13:17 UTC, LJensen0403 submitted a review, later dismissed

2020-10-29 08:50 UTC, ProgDaniel approved these changes, later dismissed

2020-10-30 14:27 UTC, ProgDaniel approved these changes

2020-11-03 08:35 UTC, LJensen0403 approved these changes

2020-11-03 09:27 UTC, merged