Feature/529: Guardians should be able to mark activities as complete like the citizens can
aau-giraf/weekplanner-OLDUI pull request #602
Opened 2020-10-14 08:44 UTC by LJensen0403

Rendered complete activity button if user is a guardian.
Widget tests if the button is rendered.

closes #529

2020-10-14 08:46 UTC, Determinatoro commented
Please use the following checklist, @ZohraAmini. Feel free to check it off as you go along.

**Code Design**
- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is necessary for solving the problem

**Code Readability and Maintainability**
- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] All new functionality is covered by tests
- [ ] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [ ] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

2020-10-14 08:46 UTC, Determinatoro commented
Please use the following checklist, @JeppeKLau. Feel free to check it off as you go along.

**Code Design**
- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is necessary for solving the problem

**Code Readability and Maintainability**
- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] All new functionality is covered by tests
- [ ] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [ ] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

2020-10-14 09:32 UTC, JeppeKLau requested changes

2020-10-14 09:32 UTC, JeppeKLau commented on lib/screens/show_activity_screen.dart
> +                        key: const Key('CancelStateToggleButton'),
This seems hacky and overly engineered. Why not just stick to the old button?

2020-10-14 09:43 UTC, LJensen0403 commented on lib/screens/show_activity_screen.dart
> +                        key: const Key('CancelStateToggleButton'),
Can you please elaborate on what you mean by "stick to the old button"? 
To start, both citizens and guardians only had a single button each. To be able to return two buttons for guardians, we had to wrap them in a container.
The nested containers are a byproduct of a padding issue, but we are working on solving it

2020-10-15 06:32 UTC, JeppeKLau approved these changes

2020-10-16 12:20 UTC, ZohraAmini approved these changes

2020-10-16 12:23 UTC, merged