Feature/576
aau-giraf/weekplanner-OLDUI pull request #620
Opened 2020-10-19 10:27 UTC by ggAlexS

Renaming choiceboards have been implemented

2020-10-19 11:06 UTC, ggAlexS commented
needs the api-client to be updated for the linter to accept the new variable

2020-10-19 11:33 UTC, Determinatoro commented
Please use the following checklist, @Huften. Feel free to check it off as you go along.

**Code Design**

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability**

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] Error messages in the code are understandable

**Code Maintainability**

- [ ] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need be covered by tests
- [ ] The functionality needs to be covered by tests

Only use if the functionality needs to be covered by tests:
- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, open the app, and test:

- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

2020-10-19 11:33 UTC, Determinatoro commented
Please use the following checklist, @social2dk. Feel free to check it off as you go along.

**Code Design**

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability**

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] Error messages in the code are understandable

**Code Maintainability**

- [ ] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need be covered by tests
- [ ] The functionality needs to be covered by tests

Only use if the functionality needs to be covered by tests:
- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, open the app, and test:

- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

2020-10-20 08:17 UTC, ZohraAmini commented
please merge develop into this branch, so we can test.

2020-10-29 13:55 UTC, Huften reviewed
Is it working as intended for you guys?
Because for me, when I add a "valgmulighed" to the choice board, and return to weekplanner screen, the choiceboard activity is not correctly displayed. When I then return to the same activity, the choice board title is now deleted.

2020-10-30 07:22 UTC, ggAlexS commented
> 
> 
> Is it working as intended for you guys?
> Because for me, when I add a "valgmulighed" to the choice board, and return to weekplanner screen, the choiceboard activity is not correctly displayed. When I then return to the same activity, the choice board title is now deleted.

works for me

2020-10-30 08:31 UTC, AdrianPlesner commented
This solution does not fit the provided prototype for the issue:
![](https://user-images.githubusercontent.com/42242841/95089042-f88a6000-0723-11eb-863d-2bfd7790dbc6.png)

2020-10-30 08:37 UTC, ggAlexS commented
> This solution does not fit the provided prototype for the issue:

The design in the prototype, is not optimised for use on mobile units with touch. Due to fact that it is to big, and the on screen keyboard totally squashes it

2020-10-30 08:45 UTC, AdrianPlesner commented
> > This solution does not fit the provided prototype for the issue:
> 
> The design in the prototype, is not optimised for use on mobile units with touch. Due to fact that it is to big, and the on screen keyboard totally squashes it

Has this been approved by PO?
It should be possible to make a solution where the keyboard is added as an extension to the screen instead ike other screens, see example. Maybe make the screen scrollable?
![Simulator Screen Shot - iPad Air (4th generation) - 2020-10-30 at 09 41 56](https://user-images.githubusercontent.com/33195961/97678487-2b5e1480-1a94-11eb-8e91-135ae34feafb.png)

2020-10-30 08:49 UTC, JeppeKLau commented
> 
> 
> > The design in the prototype, is not optimised for use on mobile units with touch. Due to fact that it is to big, and the on screen keyboard totally squashes it
> 
> Has this been approved by PO?
> It should be possible to make a solution where the keyboard is added as an extension to the screen instead ike other screens, see example. Maybe make the screen scrollable?
> ![Simulator Screen Shot - iPad Air (4th generation) - 2020-10-30 at 09 41 56](https://user-images.githubusercontent.com/33195961/97678487-2b5e1480-1a94-11eb-8e91-135ae34feafb.png)

First a quick question, why are you even interested in this pull request? You aren't a reviewer or a developer, so your interest makes no sense to me. Second, we attempted to implement this but due to the stupid way the activity screen has been implemented it was not possible without a full refactor of the screen, which would be way out of the scope for the issue.

2020-10-30 08:53 UTC, AdrianPlesner commented
> First a quick question, why are you even interested in this pull request? 

I'm in the same group as reviewer @Huften who asked me to help him review this due to personal reasons.

2020-10-30 08:54 UTC, JeppeKLau commented
> 
> 
> > First a quick question, why are you even interested in this pull request?
> 
> I'm in the same group as reviewer @Huften who asked me to help him review this due to personal reasons.

Has this been cleared with the process group?

2020-10-30 08:58 UTC, AdrianPlesner commented
> > I'm in the same group as reviewer @Huften who asked me to help him review this due to personal reasons.
> 
> Has this been cleared with the process group?

Not yet, and this shouldn't really be necessary. We are just trying to give a review as soon as possible. 😃

2020-10-30 09:12 UTC, AdrianPlesner commented on lib/screens/show_activity_screen.dart
> +                onFieldSubmitted: (String text)
This field is never submitted, meaning that it is never actually saved, leaving to with a null-value. You should add a submit button, like suggested in the prototype, to actually save the given title. Further, this should either make sure that a title is given, or insert a default value if not.

2020-10-30 09:22 UTC, JeppeKLau commented
> 
> Has this been approved by PO?
> It should be possible to make a solution where the keyboard is added as an extension to the screen instead ike other screens, see example. Maybe make the screen scrollable?
> 

The design has been approved by PO and they recognized the need for a refactor of the activity screen.

>
>This field is never submitted, meaning that it is never actually saved
>

The field is submitted when the user hits the 'Enter' key on the keyboard. 

>
>You should add a submit button
>

You are right, this should be added and it will.

>
>leaving to with a null-value.
>

No null-values are assigned to the name of the choice board, as the web api gives the string "ChoiceBoard" as the base value for a choice board if it has no name. And remember that the empty string, aka "", and null are not the same.

2020-10-30 09:26 UTC, AdrianPlesner commented
>No null-values are assigned to the name of the choice board, as the web api gives the string "ChoiceBoard" as the base value for a choice board if it has no name

Have you made changes to the api to make this work?

2020-10-30 09:30 UTC, JeppeKLau commented
> 
> 
> > No null-values are assigned to the name of the choice board, as the web api gives the string "ChoiceBoard" as the base value for a choice board if it has no name
> 
> Have you made changes to the api to make this work?

Yes of course. This feature has been implemented all the way from front to back from the ground up as it wasn't in the original functionality.

2020-10-30 10:11 UTC, AdrianPlesner commented
> Yes of course. This feature has been implemented all the way from front to back from the ground up as it wasn't in the original functionality.

Okay then, this was the reason we couldn't get your solution to work properly. With the right version of the API it seems to be working fine. 
>
>>You should add a submit button
>
>You are right, this should be added and it will.
> 

Are you working on this within this pull request?

2020-11-03 09:17 UTC, social2dk submitted a review, later dismissed
Remember to also get the matching web-api thing, or this does not work

2020-11-19 13:08 UTC, LivHolm commented
@ggAlexS Du eller en i din gruppe er ansvarlig for at resolve de merge conflikter der er.
Der mangler også et review fra @AdrianPlesner.

2020-11-19 13:15 UTC, ggAlexS commented
> @ggAlexS Du eller en i din gruppe er ansvarlig for at resolve de merge conflikter der er.
> 
> Der mangler også et review fra @AdrianPlesner.

Tror det her er lagt lidt på is af PO

2020-11-19 13:16 UTC, AdrianPlesner requested changes
A save and revert button should be added, as suggested by the prototype, which also adds a way to submit that is not the enter button, which is illogical in apps.

2020-11-19 13:29 UTC, puchasa commented
> > @ggAlexS Du eller en i din gruppe er ansvarlig for at resolve de merge conflikter der er.
> > Der mangler også et review fra @AdrianPlesner.
> 
> Tror det her er lagt lidt på is af PO

Det mener PO ikke at det er.

> A save and revert button should be added, as suggested by the prototype, which also adds a way to submit that is not the enter button, which is illogical in apps.

Der er fejl i prototypen da PO har glemt at tage højde for et pop-up tastatur. Derfor ignorerer vi i dette tilfælde at prototypen ikke er blevet fulgt og fokuserer i stedet på at få ting til at virke, således at næste semester kan nøjes med at fokusere på designet. PO vil lave en ny prototype og oprette et issue med det nye design som kan blive inkuderet i handover.

2020-11-19 13:36 UTC, AdrianPlesner commented
Knappen behøver måske heller ikke se ud præcist som i prototypen, men derfor burde der stadig være en submit knap så man ikke skal gøre det igennem tasteturet. Desuden er fortryd/hent standard funktionalitet vel noget der skal til for at det "virker"

2020-11-19 13:43 UTC, ggAlexS commented
Merge conflicts er løst, så den er klar til merge

2020-11-19 13:50 UTC, Kaliahh commented
PO er enige med Adrian om at der i det mindste skal være en knap til at submitte. Vi fixer designet i et senere issue, men det kunne bare være rart med noget der virker.

2020-11-19 13:54 UTC, puchasa commented
> PO er enige med Adrian om at der i det mindste skal være en knap til at submitte. Vi fixer designet i et senere issue, men det kunne bare være rart med noget der virker.

@ggAlexS vil du lige kigge på det?

2020-11-19 14:40 UTC, ggAlexS commented
> 
> 
> PO er enige med Adrian om at der i det mindste skal være en knap til at submitte. Vi fixer designet i et senere issue, men det kunne bare være rart med noget der virker.



> 
> 
> > PO er enige med Adrian om at der i det mindste skal være en knap til at submitte. Vi fixer designet i et senere issue, men det kunne bare være rart med noget der virker.
> 
> @ggAlexS vil du lige kigge på det?

værsgo

2020-11-19 20:26 UTC, AdrianPlesner requested changes
Det lader til at virke nu, jeg kunne dog godt tænke mig som minimun at det bliver testet er der på weekplan_screen kan findes et choiceboard med et andet navn end "Choiceboard", og også gerne at det viste navn på weekplan_screen faktisk bliver ændret når man givet et choiceboard et nyt navn.

De eneste tests der er indtil videre tester kun at der er et tekstfelt når det er et choiceboard, og at det er muligt at indsætte tekst i det.

2020-11-19 20:35 UTC, AdrianPlesner commented
Desuden har jeg også observeret at når man tilføjer/slettet/kopierer aktiviteter i weekplanen, bliver alle choiceboard navne reset til "Choiceboard". Dette skyldes navnet ikke bliver taget med under aktiviteter kopieres under UpdateWeek i api'et. Synderen er en constructor i GirafRest/Shared/SharedMethods.cs linje 102. Api delen af det burde nok have været mere grundigt testet, så var denne fejl blevet fanget.

2020-11-25 11:27 UTC, ggAlexS commented
> 
> 
> Desuden har jeg også observeret at når man tilføjer/slettet/kopierer aktiviteter i weekplanen, bliver alle choiceboard navne reset til "Choiceboard". Dette skyldes navnet ikke bliver taget med under aktiviteter kopieres under UpdateWeek i api'et. Synderen er en constructor i GirafRest/Shared/SharedMethods.cs linje 102. Api delen af det burde nok have været mere grundigt testet, så var denne fejl blevet fanget.

der bør nok laves et nyt issue på web-api'en til det her

2020-11-26 08:03 UTC, AdrianPlesner requested changes
Testen virker lidt underligt for mig.

2020-11-26 08:03 UTC, AdrianPlesner commented on test/screens/show_activity_screen_test.dart
> +        find.byKey(const Key('ChoiceBoardNameText')), 'nametest');
Hvis jeg ikke tager helt fejl, så er titlen på det her choiceboard "nametest" i forvejen, så det at sætte den til "nametest" igen bekræfter ikke rigtigt at det virker at ændre den?

2020-11-26 10:10 UTC, puchasa commented
> > Desuden har jeg også observeret at når man tilføjer/slettet/kopierer aktiviteter i weekplanen, bliver alle choiceboard navne reset til "Choiceboard". Dette skyldes navnet ikke bliver taget med under aktiviteter kopieres under UpdateWeek i api'et. Synderen er en constructor i GirafRest/Shared/SharedMethods.cs linje 102. Api delen af det burde nok have været mere grundigt testet, så var denne fejl blevet fanget.
> 
> der bør nok laves et nyt issue på web-api'en til det her

@ggAlexS vil du ikke lige snakke med PO om det her? Hvis de er enige må du godt oprette issuet med alt den relevante information.

2020-11-27 07:28 UTC, ggAlexS commented
> > > Desuden har jeg også observeret at når man tilføjer/slettet/kopierer aktiviteter i weekplanen, bliver alle choiceboard navne reset til "Choiceboard". Dette skyldes navnet ikke bliver taget med under aktiviteter kopieres under UpdateWeek i api'et. Synderen er en constructor i GirafRest/Shared/SharedMethods.cs linje 102. Api delen af det burde nok have været mere grundigt testet, så var denne fejl blevet fanget.
> 
> > 
> 
> > der bør nok laves et nyt issue på web-api'en til det her
> 
> 
> 
> @ggAlexS vil du ikke lige snakke med PO om det her? Hvis de er enige må du godt oprette issuet med alt den relevante information.

Altså ligemeget hvad skal backend problemer ikke løses på en weekplaner pull request. client-api og web-api delene af det her issues er kørt igennem for længe siden.

2020-11-30 09:31 UTC, ggAlexS commented
> > > > Desuden har jeg også observeret at når man tilføjer/slettet/kopierer aktiviteter i weekplanen, bliver alle choiceboard navne reset til "Choiceboard". Dette skyldes navnet ikke bliver taget med under aktiviteter kopieres under UpdateWeek i api'et. Synderen er en constructor i GirafRest/Shared/SharedMethods.cs linje 102. Api delen af det burde nok have været mere grundigt testet, så var denne fejl blevet fanget.
> > 
> > 
> > > 
> > 
> > 
> > > der bør nok laves et nyt issue på web-api'en til det her
> > 
> > 
> > @ggAlexS vil du ikke lige snakke med PO om det her? Hvis de er enige må du godt oprette issuet med alt den relevante information.
> 
> Altså ligemeget hvad skal backend problemer ikke løses på en weekplaner pull request. client-api og web-api delene af det her issues er kørt igennem for længe siden.

Der er en pull request på web-api nu

2020-11-30 11:13 UTC, AdrianPlesner commented
> Der er en pull request på web-api nu
@ggAlexS Den kan jeg da ikke finde?

2020-11-30 11:14 UTC, ggAlexS commented
> 
> 
> > Der er en pull request på web-api nu
> 
> @ggAlexS Den kan jeg da ikke finde?

https://github.com/aau-giraf/web-api/pull/179

2020-11-30 11:15 UTC, AdrianPlesner commented
> > > Der er en pull request på web-api nu
> > 
> > 
> > @ggAlexS Den kan jeg da ikke finde?
> 
> [aau-giraf/web-api#179](https://github.com/aau-giraf/web-api/pull/179)

👍

2020-11-30 12:18 UTC, AdrianPlesner requested changes
Der er nogle problemer når man trykker enter eller lukker sit keyboard, og evt andre ting der for skærmen til at refresh

2020-11-30 12:18 UTC, AdrianPlesner commented on lib/screens/show_activity_screen.dart
> +    String inputtext = '';
Denne bliver reset til '' ved fx tryk på enter, eller hvis man kollapser sit onscreen keyboard

2020-11-30 12:18 UTC, AdrianPlesner commented on lib/screens/show_activity_screen.dart
> +                onChanged: (String text) {
Enten lad være med at bruge et FormField og ansæt en controller til at tilgå teksten ordentligt, eller rent faktisk brug Form funktionaliteten til noget e.g. wrap den i en Form hvorpå man kan kalde .save med gemknappen og bruge tekstfeltets onSave.

2020-12-09 14:00 UTC, AdrianPlesner commented
environments.json er vidst kommet med.

2020-12-09 16:22 UTC, JeppeKLau commented on lib/screens/show_activity_screen.dart
> +    String inputtext = '';
Har fixet problemet med enter knappen, men det med at collapse keyboarded er by design. Hvis du lukker dit keyboard skal titlen på choice board ikke ændres.

2020-12-09 16:27 UTC, JeppeKLau commented on lib/screens/show_activity_screen.dart
> +                onChanged: (String text) {
I det vi bruger form delen vil det at tilføje en controller være lidt overkill. Man kan sagtens nøjes med den tilgang vi har valgt, da Flutter automatisk tilføjer en controller i tilfælde hvor et `TextFormField` bliver lavet uden at give en controller, som det fremgår af dokumentationen: `If [controller] is null, then a [TextEditingController] will be constructed automatically and its text will be initialized to [initialValue] or the empty string.`

2020-12-09 17:03 UTC, AdrianPlesner commented on lib/screens/show_activity_screen.dart
> +    String inputtext = '';
Der er også fint, men hvis jeg trykker på Godkend knappen efter at jeg har lukket mit keyboard bliver titlen sat til `''` hvilket jeg ikke tænker var hensigten? Desuden giver det fejl så aktiviteten bliver rød når man vender tilbage til uge oversigten.

2020-12-09 17:06 UTC, AdrianPlesner commented on lib/screens/show_activity_screen.dart
> +                onChanged: (String text) {
Det er også helt fint, jeg tænker bare ikke at der er noget grund til at bruge et TextFormField i stedet for et TextField, hvis man alligevel ikke bruger Form delen af den?

2020-12-09 18:19 UTC, JeppeKLau commented on lib/screens/show_activity_screen.dart
> +                onChanged: (String text) {
Det er nemmest at bruge et `TextFormField` i forhold til at initialisere værdien af tekst feltet. Så selvom at al form funktionaliteten ikke bliver brugt, er det den nemmeste tilgang til at tilføje den her funktionalitet.

2020-12-09 18:27 UTC, JeppeKLau commented on lib/screens/show_activity_screen.dart
> +    String inputtext = '';
Det burde være fikset nu

2020-12-10 07:42 UTC, AdrianPlesner approved these changes

2020-12-10 08:42 UTC, social2dk commented
Jeg kan ikke få lov til at rename hvis jeg lige har tilføjet en valgmulighed, både hvis det er en som allerede har valgmuligheder, og en som ikke havde i forvejen. Er det et problem?

2020-12-10 09:28 UTC, JeppeKLau commented
> 
> 
> Jeg kan ikke få lov til at rename hvis jeg lige har tilføjet en valgmulighed, både hvis det er en som allerede har valgmuligheder, og en som ikke havde i forvejen. Er det et problem?
> Altså hvis jeg ligesom går ud fra aktiviteten, så jeg er ude og se alle ugeplaner igen, og så går ind på choiceboardet igen, så kan jeg godt

Lige umiddelbart, så virker det til at være et problem med måden at aktiviteter bliver opdateret når de bliver til choice boards eller får tilføjet nye valgmuligheder. Det er ikke noget der er direkte relateret til det vi har tilføjet. Overvej at oprette et issue på det, kunne forestille mig at det kan hjælpe hvis man implementerede en state og brugte den til at holde styr på aktiviteterne.

2020-12-10 09:42 UTC, social2dk commented on pubspec.lock
>        name: async
Den her skal ikke med, skal den?

2020-12-10 09:42 UTC, social2dk commented on pubspec.lock
>        name: async
Altså hele pubspec.lock

2020-12-10 09:47 UTC, JeppeKLau commented on pubspec.lock
>        name: async
Jo den skal med, for den bliver opdateret automatisk af `flutter pub get` og den beskriver bare hvilken specifikke version af packages som er blevet hentet da `flutter pub get` er blevet kørt.

2020-12-10 10:14 UTC, social2dk approved these changes

2020-12-10 10:15 UTC, merged