Feature/595 Used MediaQuery to adjust the layout for all screens (upload_image_from_phone)
aau-giraf/weekplanner-OLDUI pull request #655
Opened 2020-11-03 08:58 UTC by ZohraAmini

Closes #595 

Now it is possible to scroll in that screen  (upload_image_from_phone) so the textoverflow is eliminated.
It has been tested on (emulators) several devices such as:  mobile devices Pixel 2 and 3, Tablet (WXGA 10.1 API 30).

2020-11-03 09:00 UTC, Determinatoro commented
Please use the following checklist, @twaxlol. Feel free to check it off as you go along.

**Code Design** 

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems     
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability** 

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no \"hack\", or obscure solution   

**Code Maintainability**

- [ ] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need to be covered by tests
- [ ] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, open the app, and test:
- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

2020-11-03 09:00 UTC, Determinatoro commented
Please use the following checklist, @Mustafa-ALD. Feel free to check it off as you go along.

**Code Design** 

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems     
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability** 

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no \"hack\", or obscure solution   

**Code Maintainability**

- [ ] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need to be covered by tests
- [ ] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, open the app, and test:
- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

2020-11-03 10:38 UTC, twaxlol commented
Er du muligt at lave en Flutter test, for at sikrer at der ikke sker et overflow?
Kan se at pubspec.yaml og environments json er pushed med, er dette meningen?
Ellers ser det godt ud

2020-11-03 16:16 UTC, ZohraAmini commented
@twaxlol 
1. Med Flutter tests - mener du så unit tests? Hvis ja, så er det ikke nødvendigt i dette tilfælde, da det er kun UI ændringer. Det skal bare testes manuelt på emulatorer. 
2. pubspec og environment push er vist ikke meningen.

2020-11-03 17:31 UTC, Mustafa-ALD requested changes

2020-11-03 17:31 UTC, Mustafa-ALD commented on .gitignore
> +assets/environments.json
Looks good it works and has no problem.
But I'm not sure that adding the environments.json file is part of the fix 🤔

2020-11-04 07:37 UTC, twaxlol submitted a review, later dismissed

2020-11-10 08:26 UTC, ZohraAmini commented on .gitignore
> +assets/environments.json
@Mustafa-ALD  request for changes has been acted upon (made a commit revert)

2020-11-10 08:32 UTC, Mustafa-ALD approved these changes
Look good

2020-11-10 09:09 UTC, twaxlol approved these changes

2020-11-10 09:31 UTC, merged