Added api exeptions
aau-giraf/weekplanner-OLDUI pull request #658
Opened 2020-11-03 17:16 UTC by Emil-Linnebjerg

This adds api exeptions to the bloc.
This is the result of issue #431 
There has been created exeption handeling for api calls in the bloc.

2020-11-04 07:32 UTC, Determinatoro commented
Please use the following checklist, @Oliversrensen. Feel free to check it off as you go along.

**Code Design** 

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems     
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability** 

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no \"hack\", or obscure solution   

**Code Maintainability**

- [ ] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need to be covered by tests
- [ ] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, open the app, and test:
- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

2020-11-04 07:32 UTC, Determinatoro commented
Please use the following checklist, @ChristofferAaen. Feel free to check it off as you go along.

**Code Design** 

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems     
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability** 

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no \"hack\", or obscure solution   

**Code Maintainability**

- [ ] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need to be covered by tests
- [ ] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, open the app, and test:
- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

2020-11-09 09:53 UTC, Oliversrensen submitted a review, later dismissed

2020-11-09 12:49 UTC, ChristofferAaen submitted a review, later dismissed
Okay I see

2020-11-10 08:12 UTC, LivHolm commented
@Emil-Linnebjerg Det er dit job at resolve de merge konflikter der er.

2020-11-10 12:10 UTC, Oliversrensen approved these changes, later dismissed

2020-11-17 08:07 UTC, ChristofferAaen approved these changes

2020-11-17 08:16 UTC, ChristofferAaen requested changes
Det ser ud til du skriver error codes ud i consolen. Inde i API mappen i weekplanner med en error translater

2020-11-26 10:27 UTC, ChristofferAaen requested changes
I fanger ikke nogle API exceptions 
brug den her:
https://github.com/aau-giraf/weekplanner/blob/develop/lib/api/errorcode_translater.dart

2020-11-26 10:30 UTC, Emil-Linnebjerg commented
Jeg er ikke helt sikker på jeg forstår vi har testet det den fanger fejl

2020-11-26 10:38 UTC, ChristofferAaen commented
https://github.com/aau-giraf/api_client/blob/master/lib/api/api_exception.dart
er den type af exceptions i skal fange
https://github.com/aau-giraf/weekplanner/blob/develop/lib/api/errorcode_translater.dart
oversætter exceptions så brugeren kan forstå dem

Disse klasser fanger exceptions og oversætter dem til dansk, således brugeren kan forstå dem. I fanger ikke nogen af disse exceptions, hvilket er det i skal. (som nævnt til sprint 2 review)

2020-11-26 10:40 UTC, Emil-Linnebjerg commented
Jeg kan godt se i har lavet en metode til at smide fejlt det super men den kræver en "context" som man får når man er i screens
Api fejl skal smides i blocs og derfor har vi ingen "context" 
Denne metode der nu kommer til api er lavet til at teste på api kald i blocs

2020-11-26 10:54 UTC, Emil-Linnebjerg commented
"As of now A lot of the BloCs are not handling exceptions/errors thrown when doing an API call."
Jeg tror desværre i har misforstået den opgave der skal løses her.

2020-11-26 12:07 UTC, ChristofferAaen commented
I bruger også try, catch på det meste, hvilket også står i issuet man ikke skal. I er nød til at bruge onError, fra api exceptions. 

Er meget ked af det men tror det hele skal laves om forfra.

2020-11-26 12:07 UTC, ChristofferAaen commented
fordi i ikke får fanget de rigtige exceptions fra API

2020-11-26 12:09 UTC, ChristofferAaen requested changes

2020-11-26 12:09 UTC, ChristofferAaen commented on lib/screens/upload_image_from_phone_screen.dart
> +            color: theme.GirafColors.black,
what is this??? er det en del af jeres issue??

2020-11-26 12:11 UTC, ChristofferAaen commented
https://github.com/aau-giraf/wiki/blob/develop/docs/development/WeekplannerErrorHandlingGuidelines.md

Process fortalte det her til sprint review sidst

2020-11-26 12:20 UTC, Emil-Linnebjerg commented
Så vi bruger try{}on IKKE try catch 
Det gør at vi kan få en specifik fejl som man skal gøre dette gør man får at give en app som er responsive med specifikke fejl istedet for generiske fejl der ikke hjælper brugeren.
Eksempelvis en SocketException smider en fjel der promter brugeren med en besked der læser "kunne ikke få forbindelse til internettet" så ved brugeren præcis hvad problemet er og synes ikke at appen lagger eller er buggy.
Til koden er det her den nye version af weekplaner for at undgå merge conflicts.
Er glad for i vil se gode exeptions men tror stadig i misforstår problemet der skal løses her.

2020-11-26 12:47 UTC, ChristofferAaen commented
Kan i ikke tage at få dækket linjerne i jeres kode med test, fordi CI'en fejler. 

Vi kan godt se i fanger nogle exceptions, men kan i så ikke tilføje en onError på streams, vi kan se i har en context som i siger i ikke kan få fat i, kan i ikke bare bruge den. 

Men vigtigt i lige kan få dem igennem CI'en

2020-11-26 12:49 UTC, Emil-Linnebjerg commented
Vi er i gang med at gøre præcis det tænker det er fint hellere lidt flere test en at have for få

2020-11-26 14:14 UTC, Emil-Linnebjerg commented
Ok håber alle er glade nu. Vi fanger exceptions, hvis der kommer en error fanger vi også den tager den så igennem exception handleren og sender den til jeres error handler med en context. Altså er både exceptions og errors fanget og håndteret nu.

2020-11-30 08:07 UTC, ChristofferAaen commented
kan også se at mange linjer ikke er dækket af test. Er det muligt? Process mener også det skal testet

2020-11-30 16:39 UTC, Emil-Linnebjerg commented
Ok testen er blevet opdateret nu så codecov kan forstå den. Det burde dække den kode der giver mening at teste.

2020-12-02 14:15 UTC, LivHolm commented
@Emil-Linnebjerg husk at resolve merge konflikter

2020-12-07 13:56 UTC, Oliversrensen commented
Jeg er ved at kigge på det

2020-12-07 14:33 UTC, Oliversrensen requested changes

2020-12-07 14:33 UTC, Oliversrensen commented on lib/blocs/blocs_api_exeptions.dart
> +    ///switchen her er bare for at give nogle basale api fejl
Der er skrevet code comments på dansk, de skal gerne være på engelsk. Gælder flere steder.

2020-12-07 14:33 UTC, Oliversrensen commented on lib/blocs/blocs_api_exeptions.dart
> +class BlocsApiExeptions{
Exception er stavet forkert i klassens navn. "Exeption" skal være "Exception".

2020-12-07 14:33 UTC, Oliversrensen commented on lib/blocs/blocs_api_exeptions.dart
> +  void showMyDialog() {
Der kommer ikke en AlertDialog.

2020-12-07 14:33 UTC, Oliversrensen commented on lib/blocs/blocs_api_exeptions.dart
> +          return AlertDialog(
Designguiden kræver at man bruger GirafNotifyDialog og ikke AlertDialog :)

2020-12-07 15:14 UTC, Emil-Linnebjerg commented on lib/blocs/blocs_api_exeptions.dart
> +          return AlertDialog(
True stuff

2020-12-08 07:51 UTC, Oliversrensen requested changes
Hvor blev dine tests af? 😕

2020-12-08 07:51 UTC, Oliversrensen commented on lib/blocs/blocs_api_exceptions.dart
> +  void showMyDialog() {
Har du selv set om du kan fremtvinge en popup? Vi kan ikke få det til at virke 👎

2020-12-09 11:28 UTC, Oliversrensen requested changes
Jeg vil gerne henvise dig til mit tidligere review, hvor jeg er i tvivl om det overhovedet virker, og undrer mig over hvor dine tests er blevet af.

2020-12-15 09:22 UTC, closed without merging