Feature 683: Fixed server status check and made login async
aau-giraf/weekplanner-OLDUI pull request #686
Opened 2020-11-24 14:01 UTC by AdrianPlesner

Closes #683  
The check server status method did not request the correct api-endpoint, always resulting in 404 route not found. While fixing this, we also discovered that the login was completely backwards and not actually async. This, being related to the issue,  has been fixed as well.

2020-11-24 14:05 UTC, Determinatoro commented
Please use the following checklist, @JeppeKLau. Feel free to check it off as you go along.

**Assets**
- [ ] The ``environments.json`` file has the following default values:
```
{
  "SERVER_HOST": "https://srv.giraf.cs.aau.dk/DEV/API",
  "DEBUG": true,
  "USERNAME": "Graatand",
  "PASSWORD": "password"
}
```

**Code Design** 

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems     
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability** 

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no \"hack\", or obscure solution   

**Code Maintainability**

- [ ] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need to be covered by tests
- [ ] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, open the app, and test:
- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

2020-11-24 14:05 UTC, Determinatoro commented
Please use the following checklist, @Riasalit. Feel free to check it off as you go along.

**Assets**
- [ ] The ``environments.json`` file has the following default values:
```
{
  "SERVER_HOST": "https://srv.giraf.cs.aau.dk/DEV/API",
  "DEBUG": true,
  "USERNAME": "Graatand",
  "PASSWORD": "password"
}
```

**Code Design** 

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems     
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability** 

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no \"hack\", or obscure solution   

**Code Maintainability**

- [ ] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need to be covered by tests
- [ ] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, open the app, and test:
- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

2020-11-24 14:35 UTC, Riasalit reviewed
![image](https://user-images.githubusercontent.com/28717453/100108000-9835b600-2e6a-11eb-968c-790803ea15a7.png)

Altså ved ikke om det her skyldes den her branch... men kan ikke logge ind

2020-11-24 14:35 UTC, Riasalit commented on lib/blocs/auth_bloc.dart
> +    // ignore: always_specify_types
Hvorfor ikke bare specificere en type?

2020-11-24 15:15 UTC, AdrianPlesner commented
@Riasalit Jeg har brug for at se mere af loggen fra dit api for at kunne identificere hvad der er galt, men mit bud er at det nok har noget at gøre med den kombination af web-api og api_client du bruger. Det er testet og virker med den nyeste version af develop af begge.

2020-11-24 15:17 UTC, AdrianPlesner commented
Account controller I web-api er fornyligt ændret fra v1 til v2 så hvis man ikke får opdateret både web-api og api_client kan man ikke logge ind.

2020-11-25 07:43 UTC, JeppeKLau requested changes
Error handling er en stor mangel.

Udover kommentarene, kunne jeg forestille mig der var smartere måder at tjekke om vi har forbindelse til internettet, end blot at pinge Googles url. Ved godt det ikke er direkte relateret til issuet, men jeg vil nu stadig gerne se det ændret.

2020-11-25 07:43 UTC, JeppeKLau commented on lib/blocs/auth_bloc.dart
>      });
Umiddelbart vil jeg mene at det ikke er smart bare at gennemtvinge en færdiggørelse ved en fejl.

2020-11-25 07:43 UTC, JeppeKLau commented on lib/blocs/auth_bloc.dart
> +    } );
Igen med at gennemtvinge gennemførsel på en fejl.

2020-11-25 07:43 UTC, JeppeKLau commented on lib/screens/login_screen.dart
> +    final String loginUrl = environment.getVar<String>('SERVER_HOST') + '/v1/Status';
Jeg kan forestille mig at man kan tilgå statusen på en anden måde, fx. gennem api klienten. Ellers burde det tilføjes.

Udover dette, giver navnet på variablen ikke mening da det ikke er på det endpoint vi logger ind.

2020-11-25 08:25 UTC, AdrianPlesner commented on lib/blocs/auth_bloc.dart
> +    } );
Men .completeError(error) melder jo nettop færdig med fejl og sender fejlen videre til caller [completeError dokumentation](https://api.dart.dev/stable/2.10.2/dart-async/Completer/completeError.html). Hvis du ikke synes det er tilstrækkeligt kunne jeg godt tænke mig at du kommer med et konkret forslag til hvad der så skal ske.

2020-11-25 08:30 UTC, JeppeKLau commented on lib/blocs/auth_bloc.dart
> +    } );
Oh. Jeg har læst forkert, havde set det som at der blev kaldt `complete()`.

2020-11-25 08:47 UTC, Riasalit commented
```Welcome to Giraf REST Server.
        No program arguments were found - running in default configuration.
        Run with --list to list options
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\danie\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.1.8 initialized 'GirafDbContext' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: None
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (35ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT EXISTS (
          SELECT 1
          FROM `AspNetRoles` AS `a`)
Hosting environment: Development
Content root path: C:\Users\danie\Documents\GitHub\web-api\GirafRest
Now listening on: http://[::]:5000
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://10.0.2.2:5000/v1/Account/login application/json; charset=utf-8 45
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
      Successfully validated the token.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "StatusCodeEndpoint", controller = "Error"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.ActionResult StatusCodeEndpoint(Int32) on controller GirafRest.Controllers.ErrorController (GirafRest).
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Executing action method GirafRest.Controllers.ErrorController.StatusCodeEndpoint (GirafRest) - Validation state: Valid
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action method GirafRest.Controllers.ErrorController.StatusCodeEndpoint (GirafRest), returned result Microsoft.AspNetCore.Mvc.NotFoundObjectResult in 0.6537ms.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.1.8 initialized 'GirafDbContext' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: None
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (45ms) [Parameters=[@__userId_0='?' (Size = 255)], CommandType='Text', CommandTimeout='30']
      SELECT `a`.`Id`, `a`.`AccessFailedCount`, `a`.`ConcurrencyStamp`, `a`.`DepartmentKey`, `a`.`DisplayName`, `a`.`Email`, `a`.`EmailConfirmed`, `a`.`IsDepartment`, `a`.`LockoutEnabled`, `a`.`LockoutEnd`, `a`.`NormalizedEmail`, `a`.`NormalizedUserName`, `a`.`PasswordHash`, `a`.`PhoneNumber`, `a`.`PhoneNumberConfirmed`, `a`.`SecurityStamp`, `a`.`SettingsKey`, `a`.`TwoFactorEnabled`, `a`.`UserIcon`, `a`.`UserName`
      FROM `AspNetUsers` AS `a`
      WHERE `a`.`Id` = @__userId_0
      LIMIT 1
info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      Executing ObjectResult, writing value of type 'GirafRest.Models.Responses.ErrorResponse'.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action GirafRest.Controllers.ErrorController.StatusCodeEndpoint (GirafRest) in 515.0133ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 1039.9936ms 404 application/json; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://10.0.2.2:5000/v1/Status  0
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "Status", controller = "Status"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.ActionResult Status() on controller GirafRest.Controllers.StatusController (GirafRest).
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Executing action method GirafRest.Controllers.StatusController.Status (GirafRest) - Validation state: Valid
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action method GirafRest.Controllers.StatusController.Status (GirafRest), returned result Microsoft.AspNetCore.Mvc.OkObjectResult in 0.2426ms.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.1.8 initialized 'GirafDbContext' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: None
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT `a`.`Id`, `a`.`AccessFailedCount`, `a`.`ConcurrencyStamp`, `a`.`DepartmentKey`, `a`.`DisplayName`, `a`.`Email`, `a`.`EmailConfirmed`, `a`.`IsDepartment`, `a`.`LockoutEnabled`, `a`.`LockoutEnd`, `a`.`NormalizedEmail`, `a`.`NormalizedUserName`, `a`.`PasswordHash`, `a`.`PhoneNumber`, `a`.`PhoneNumberConfirmed`, `a`.`SecurityStamp`, `a`.`SettingsKey`, `a`.`TwoFactorEnabled`, `a`.`UserIcon`, `a`.`UserName`
      FROM `AspNetUsers` AS `a`
      WHERE FALSE = TRUE
      LIMIT 1
info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      Executing ObjectResult, writing value of type 'GirafRest.Models.Responses.SuccessResponse'.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action GirafRest.Controllers.StatusController.Status (GirafRest) in 41.8183ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 52.5691ms 200 application/json; charset=utf-8 ```

2020-11-25 09:13 UTC, Riasalit commented
Soooo flutter simply refuses to get the latest version of the api-client

2020-11-25 09:25 UTC, AdrianPlesner commented
> Soooo flutter simply refuses to get the latest version of the api-client

Yup det virker til at være problemet

2020-11-25 09:30 UTC, Riasalit commented
![image](https://user-images.githubusercontent.com/28717453/100208468-0b8e0500-2f09-11eb-8c66-258813ab91cd.png)

We in bois.
"flutter packages upgrade" og så slet den forkerte cachede versio...... igen igen... virkede

2020-11-25 09:33 UTC, JeppeKLau commented
> 
> 
> Soooo flutter simply refuses to get the latest version of the api-client

Jeg fik det til at virke ved at fjerne `api_client` fra `pubspec.yaml`, køre `flutter pub get`, tilføje den tilbage i `pubspec.yaml` og køre `flutter pub get` igen - ser ud til at `pubspec.lock` har en forkert `resolved-ref` for `api_client`

2020-11-25 09:34 UTC, AdrianPlesner commented
> > Soooo flutter simply refuses to get the latest version of the api-client
> 
> Jeg fik det til at virke ved at fjerne `api_client` fra `pubspec.yaml`, køre `flutter pub get`, tilføje den tilbage i `pubspec.yaml` og køre `flutter pub get` igen - ser ud til at `pubspec.lock` har en forkert `resolved-ref` for `api_client`

Jeg bruger samme methode

2020-11-25 09:38 UTC, Riasalit commented
> 
> 
> > > Soooo flutter simply refuses to get the latest version of the api-client
> > 
> > 
> > Jeg fik det til at virke ved at fjerne `api_client` fra `pubspec.yaml`, køre `flutter pub get`, tilføje den tilbage i `pubspec.yaml` og køre `flutter pub get` igen - ser ud til at `pubspec.lock` har en forkert `resolved-ref` for `api_client`
> 
> Jeg bruger samme methode

prøvede det. men det gjorde intet for mig

2020-11-25 09:38 UTC, Riasalit approved these changes, later dismissed

2020-11-25 10:16 UTC, Riasalit approved these changes

2020-11-25 10:16 UTC, Riasalit requested changes
CI actions failer

2020-11-25 10:24 UTC, Riasalit requested changes
Vil gerne have at der står hvad funktionen gør

2020-11-25 10:31 UTC, AdrianPlesner commented
> Vil gerne have at der står hvad funktionen gør

Ups. 😄

2020-11-25 10:32 UTC, Riasalit approved these changes, later dismissed

2020-11-25 10:51 UTC, JeppeKLau requested changes
Se kommentarer :)

2020-11-25 10:51 UTC, JeppeKLau commented on lib/screens/login_screen.dart
> +            checkServerConnection().then((bool hasServerConnection) {
Jeg tænker at hvis man får en `SocketException`, så må der være noget galt med enten internet forbindelsen eller forbindelsen til serveren. Så jeg tænker det måske er fint nok bare at kontrollere forbindelsen til serveren, da det ikke er nødvendigt at tjekke forbindelsen til internettet hvis man alligevel får en `SocketException`.

2020-11-25 10:51 UTC, JeppeKLau commented on test/screens/login_screen_test.dart
>      // Checking username/password
Når du har fjernet funktionen i koden, ser jeg ingen grund til at bringe funktionen tilbage til testen. Hvis testen er afhængig af funktionen, må testen skrives om så den ikke er afhængig af funktionen.

2020-11-25 10:51 UTC, JeppeKLau commented on lib/blocs/auth_bloc.dart
> +    // ignore: always_specify_types
Kan typen ikke tilføjes et sted eller er det bare linteren der er dum?

2020-11-25 10:53 UTC, AdrianPlesner commented on lib/blocs/auth_bloc.dart
> +    // ignore: always_specify_types
Det er en rigtig dum linter 🙂

2020-11-25 10:58 UTC, AdrianPlesner commented on lib/screens/login_screen.dart
> +            checkServerConnection().then((bool hasServerConnection) {
Det sørger jo bare for at håndtere fejl vi ikke regner med at der kommer. Det er bare for en sikkerheds skyld. Jeg tænker heller ikke at der kan være andet end manglede forbindelse til enten server eller internet, men man kan vel ikke være helt sikker. 🤷

2020-11-25 11:01 UTC, JeppeKLau commented on lib/screens/login_screen.dart
> +            checkServerConnection().then((bool hasServerConnection) {
Det er bare et spildt tjek. Desuden, som jeg også sagde før, er det virkelig ikke smart at tjekke om man har internet ved at pinge Google. Der er ikke noget der siger at deres service ikke kunne ske at gå ned på et tidpunkt i fremtiden.

2020-11-25 11:01 UTC, AdrianPlesner commented on test/screens/login_screen_test.dart
>      // Checking username/password
Fixed

2020-11-25 11:03 UTC, AdrianPlesner commented on lib/screens/login_screen.dart
> +            checkServerConnection().then((bool hasServerConnection) {
Det er da en meget standard måde at gøre det på, og så er det cross platform.

2020-11-25 11:04 UTC, Riasalit commented on lib/blocs/auth_bloc.dart
> +    // ignore: always_specify_types
er det ikke bare "Future.wait(<Future<void>>[completer.future]);"?

2020-11-25 11:05 UTC, JeppeKLau commented on lib/blocs/auth_bloc.dart
> +    // ignore: always_specify_types
Det er bare `Future.wait(<Future<void>>[completer.future]);`

2020-11-25 11:16 UTC, JeppeKLau commented on lib/screens/login_screen.dart
> +            checkServerConnection().then((bool hasServerConnection) {
Der er [det her](https://pub.dev/packages/connectivity#-readme-tab-) plugin som jeg kan se ville kunne short circuit at tjekke om man har internet, inden man begynder på at pinge rundt på nettet.
Dertil vil jeg så nævne at der også findes [det her](https://medium.com/@anilpandey071999/how-to-check-the-internet-connection-in-the-flutter-app-56b8be1fd057) plugin der automatisk pinger en række af hjemmesider og ikke blot en enkelt som vi gør her. Det giver en mindre chance for fejl da de alle skal misse før der konkluderes at man ingen forbindelse har. 

De to plugins i sammenhæng kunne jeg se gav en god sikkerhed for at tjekke om man har internet eller ej.

2020-11-25 11:42 UTC, AdrianPlesner commented on lib/blocs/auth_bloc.dart
> +    // ignore: always_specify_types
Jeg overgiver mig på den front, jeg synes bare at jeg havde prøvet, men min compiler var vidst forvirret. Det virker til at virke nu. 😄

2020-11-25 11:45 UTC, AdrianPlesner commented on lib/screens/login_screen.dart
> +            checkServerConnection().then((bool hasServerConnection) {
Oki doki så, hvis du insisterer.

2020-11-25 13:32 UTC, JeppeKLau requested changes
Vi er der næsten Adrian. Vil tilføje at det er dejligt at se du har rykket business logic om i BLOCen frem for at have det i screenen

2020-11-25 13:32 UTC, JeppeKLau commented on lib/blocs/auth_bloc.dart
> +      completer.complete(false);
Var det ikke den der skulle give en error tilbage når der skete en fejl?

2020-11-25 13:32 UTC, JeppeKLau commented on lib/screens/login_screen.dart
> +  }
Jeg kan godt se ideen, men virker bare lidt fjollet når den kun bruges tre gange, hvor man bare kunne indsætte `creatingNotifyDialog` med den passende key

2020-11-25 13:33 UTC, AdrianPlesner commented on lib/screens/login_screen.dart
> +  }
Jah, jeg synes 3 gange var for meget

2020-11-25 13:35 UTC, AdrianPlesner commented on lib/blocs/auth_bloc.dart
> +      completer.complete(false);
Joh, men det er egentligt nok at håndter fejler her. At smide fejler videre giver bare endnu et unødvendigt led med onError -> createErrorDialog, og i sidste ende giver det samme resultat

2020-11-25 13:42 UTC, AdrianPlesner commented on lib/screens/login_screen.dart
> +            checkServerConnection().then((bool hasServerConnection) {
Vi kan ikke bruge connectivity pakken, den giver build errors på android, jeg håber du kan nøjes med den anden.

2020-11-25 14:00 UTC, Riasalit approved these changes

2020-11-25 14:17 UTC, JeppeKLau commented on lib/screens/login_screen.dart
> +            checkServerConnection().then((bool hasServerConnection) {
Det må være nok så - tænkte bare der måske var et eller andet indbygget, men det her må være nok

2020-11-25 14:17 UTC, JeppeKLau approved these changes

2020-11-25 14:18 UTC, merged