Feature 587: only refresh affected weekdays when making changes
aau-giraf/weekplanner-OLDUI pull request #694
Opened 2020-12-01 22:42 UTC by AdrianPlesner

Closes #587

2020-12-02 07:52 UTC, Determinatoro commented
Please use the following checklist, @13uller. Feel free to check it off as you go along.

**Assets**
- [ ] The ``environments.json`` file has the following default values:
```
{
  "SERVER_HOST": "https://srv.giraf.cs.aau.dk/DEV/API",
  "DEBUG": true,
  "USERNAME": "Graatand",
  "PASSWORD": "password"
}
```

**Code Design** 

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems     
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability** 

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no \"hack\", or obscure solution   

**Code Maintainability**

- [ ] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need to be covered by tests
- [ ] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, open the app, and test:
- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

2020-12-02 07:52 UTC, Determinatoro commented
Please use the following checklist, @Riasalit. Feel free to check it off as you go along.

**Assets**
- [ ] The ``environments.json`` file has the following default values:
```
{
  "SERVER_HOST": "https://srv.giraf.cs.aau.dk/DEV/API",
  "DEBUG": true,
  "USERNAME": "Graatand",
  "PASSWORD": "password"
}
```

**Code Design** 

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems     
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability** 

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no \"hack\", or obscure solution   

**Code Maintainability**

- [ ] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need to be covered by tests
- [ ] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, open the app, and test:
- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

2020-12-02 07:55 UTC, AdrianPlesner commented
Vær opmærksom på at dette er linket sammen med aau-giraf/api_client#81 og aau-giraf/web-api#19 og det er derfor selvfølgelig nødvendigt at have de tilhørende branches af de repositories for at der virker ordentligt.

2020-12-02 07:57 UTC, AdrianPlesner commented
CI fejler og der er fordi at den tilhørende branch på api-client ikke er merged endnu, men jeg vil ikke pushe en pub-spec der peger på andet en develop. Vær venlig at review alligevel. ^_^

2020-12-02 09:09 UTC, Riasalit commented
Når jeg flytter en ugeplan for først egang bliver den ikke flyttet

Flytter jeg den samme igen forsvinder den originale ikke, men jeg kan duplikere den ind i andre dage

2020-12-02 09:39 UTC, Riasalit commented on pubspec.lock
> +      ref: "feature/81"
Gætter på at det ikke var meningen at pubspec skulle med?

2020-12-02 10:08 UTC, Riasalit commented on lib/widgets/weekplanner_choiceboard_selector.dart
>    final WeekplanBloc _weekplanBloc;
er den her brugt?

2020-12-02 10:08 UTC, Riasalit commented on lib/widgets/weekplanner_choiceboard_selector.dart
> +  final WeekdayModel _weekday;
og den her?

2020-12-02 10:09 UTC, Riasalit commented on lib/widgets/weekplanner_choiceboard_selector.dart
>    final WeekplanBloc _weekplanBloc;
min linter klager over unused imports

2020-12-02 10:15 UTC, Rosmarium commented on lib/widgets/weekplanner_choiceboard_selector.dart
>    final WeekplanBloc _weekplanBloc;
Hej, vi kigger lige på det :)

2020-12-03 08:07 UTC, Riasalit requested changes
Flytter jeg den samme igen forsvinder den originale ikke, men jeg kan duplikere den ind i andre dage

2020-12-04 12:12 UTC, AdrianPlesner commented
> Flytter jeg den samme igen forsvinder den originale ikke, men jeg kan duplikere den ind i andre dage

@Riasalit Prøv at se om det ikke er bedre nu

2020-12-04 13:48 UTC, Riasalit submitted a review, later dismissed

2020-12-08 08:52 UTC, Riasalit commented
Merge conflicts

2020-12-08 08:53 UTC, LivHolm commented
@AdrianPlesner husk at resolve conflicts ^^

2020-12-08 08:53 UTC, AdrianPlesner commented
Jeg er i gang. ^_^

2020-12-08 09:26 UTC, AdrianPlesner commented
2 sek der var problemer med den merge der. 🙃

2020-12-08 10:06 UTC, Riasalit commented
![image](https://user-images.githubusercontent.com/28717453/101469698-5cf4b600-3945-11eb-8746-055c8c3dc4c3.png)
eehhhhh
får en error hvis jeg trykker på noget?

2020-12-08 10:06 UTC, Riasalit commented
> 
> 
> ![image](https://user-images.githubusercontent.com/28717453/101469698-5cf4b600-3945-11eb-8746-055c8c3dc4c3.png)
> eehhhhh
> får en error hvis jeg trykker på noget?

Muligvis bare mig der mangler at gendanne databasen?

2020-12-08 10:08 UTC, AdrianPlesner commented
@Riasalit Ja der mangler titler på dine activiteter

2020-12-08 10:08 UTC, Riasalit commented
det hjalp... men 
![image](https://user-images.githubusercontent.com/28717453/101470029-c379d400-3945-11eb-8693-302ff6276706.png)

2020-12-08 10:09 UTC, Riasalit commented
kan se at 5 af billederne i min database er corrupte

2020-12-08 10:10 UTC, AdrianPlesner commented
aha

2020-12-08 10:11 UTC, Riasalit commented
det var ikke problemet... de starte med at loade ind rigtigt. men så bliver de alle røde og teksten forsvinder fra dem

2020-12-08 10:13 UTC, AdrianPlesner commented
Har de en titel?

2020-12-08 10:13 UTC, Riasalit commented
nope

2020-12-08 10:15 UTC, AdrianPlesner commented
Så er det problemet, giv følgende query til din database og se om det ikke hjælper:
```
with ackeynam as (select min(Pictograms.Title) as name, Activities.Key as acKey
from Pictograms, PictogramRelations, Activities
where Pictograms.id = PictogramRelations.PictogramId AND Activities.Key = PictogramRelations.ActivityId
GROUP BY Activities.Key)
update Activities
set Title = (
    select name 
    from ackeynam
    where acKey = Activities.Key
    );
```

2020-12-08 10:25 UTC, Riasalit commented
såååå. det virkede men hvis jeg prøver at indsætte  en ny, så kan jeg vælge et piktogram og så sætter den bare instantly den ind uden at lade mig give den en tittel og så bliver den rød

2020-12-08 10:27 UTC, AdrianPlesner commented
Reee

2020-12-08 10:27 UTC, Riasalit commented
jeg kan så derfefter trykke på den røde aktivitet og give den en tittel.. men burde den menu ikke komme frem af sig selv?

2020-12-08 10:28 UTC, AdrianPlesner commented
> jeg kan så derfefter trykke på den røde aktivitet og give den en tittel.. men burde den menu ikke komme frem af sig selv?

Jo det burde den helt sikkert. *suk*

2020-12-08 10:30 UTC, Riasalit commented
Det skal lige siges  at jeg bruger develop på api-client og web-api, ved ikke om det er det rigtige?

2020-12-08 10:31 UTC, AdrianPlesner commented
> Det skal lige siges at jeg bruger develop på api-client og web-api, ved ikke om det er det rigtige?

Jeg tror deter rigtigt nok, de er vidst merged

2020-12-08 10:59 UTC, AdrianPlesner commented
@Riasalit Så kører vi!

2020-12-08 11:00 UTC, Riasalit commented
nice, men øøøøh, environments.json ^^

2020-12-08 11:06 UTC, Riasalit commented
altså... hvis jeg allerede har flere der bruger samme piktogram men med flere navne tager den lidt en tilfeldig. men tror at det er okay?

2020-12-08 11:07 UTC, Riasalit requested changes

2020-12-08 11:07 UTC, Riasalit commented on assets/environments.json
> +  "SERVER_HOST": "http://localhost:5000",
this bad. men tror det er det sidste ^^

2020-12-08 11:09 UTC, AdrianPlesner commented on assets/environments.json
> +  "SERVER_HOST": "http://localhost:5000",
oops

2020-12-08 11:09 UTC, AdrianPlesner commented
> altså... hvis jeg allerede har flere der bruger samme piktogram men med flere navne tager den lidt en tilfeldig. men tror at det er okay?

Jeg er ikke helt sikker på at jeg ved hvad du mener

2020-12-08 11:11 UTC, Riasalit commented
> 
> 
> > altså... hvis jeg allerede har flere der bruger samme piktogram men med flere navne tager den lidt en tilfeldig. men tror at det er okay?
> 
> Jeg er ikke helt sikker på at jeg ved hvad du mener

Hvis jeg laver en ny aktivitet med piktogrammet "Gul" laver den en aktivitet der hedder Gul. men hvis jeg så laver den om til at have titlen "Middagsmad" og så laver en ny aktivitet med piktogrammet "Gul" kommer den også til at hedde "Middagsmad" i ugeplanen

2020-12-08 11:13 UTC, AdrianPlesner commented
>Hvis jeg laver en ny aktivitet med piktogrammet "Gul" laver den en aktivitet der hedder Gul. men hvis jeg så laver den om til at have titlen "Middagsmad" og så laver en ny aktivitet med piktogrammet "Gul" kommer den også til at hedde "Middagsmad" i ugeplanen.
Men igen. ved ikke om det overhovedet er et problem?

Nej det er lige præcis meningen med #266

2020-12-08 11:14 UTC, Riasalit approved these changes

2020-12-08 12:23 UTC, social2dk approved these changes

2020-12-08 12:25 UTC, merged