Added switch to citizen button on weekplan selector screen
aau-giraf/weekplanner-OLDUI pull request #740
Opened 2021-09-22 12:31 UTC by kristnaKris

The button switches the user to Citizen mode but there is no visual change as a citizen has no special screen for the overall weekplan. The citizen is therefore still able to select and add different weekplans until one has entered a weekplan.

2021-09-23 07:18 UTC, MathiasNielsen1206 commented on lib/screens/login_screen.dart
> -      resizeToAvoidBottomPadding: false,
jeg tænker det er ok for nu at dette bliver implenteret, og så opretter vi et issue som prøver at håndtere hvad end resizeToAvoidBottomPadding skulle gøre senere

2021-09-23 07:51 UTC, MathiasNielsen1206 requested changes
brug guiden på wikien i forhold til opstilling af PR da navngivningen ikke er helt som det skal være
derudover er der et problem med, opdatering af siden når man skifter til citizen mode(der sker ikke noget på siden når man skifter det er først når man skifter screen man har skiftet til citizen mode)  og knappen er placeret anderledes end på andre screens(se weekplan_screen) det må også gerne ændres.

**Assets**
- [x] The ``environments.json`` file has the following default values:
```
{
  "SERVER_HOST": "https://srv.giraf.cs.aau.dk/DEV/API",
  "DEBUG": true,
  "USERNAME": "Graatand",
  "PASSWORD": "password"
}
```

**Code Design** 

- [x] The code is in the right place? (Both in terms of folder structure and class structure)
- [x] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems     
- [x] This code could not, to the best of my knowledge, have reused existing code
- [x] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability** 

- [x] Names are meaningful and self-documenting
- [x] It is understandable, by reading the code, what it does
- [x] The code is simple and readable. i.e. it contains no \"hack\", or obscure solution   

**Code Maintainability**

- [x] Has all the added code been properly commented

Only check one of the items below:

- [x] The functionality does **not** need to be covered by tests
- [ ] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, open the app, and test:
- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [x] All the new screens are reachable through in-app navigation

2021-09-23 08:59 UTC, kristnaKris commented
> ...derudover er der et problem med, opdatering af siden når man skifter til citizen mode(der sker ikke noget på siden når man skifter det er først når man skifter screen man har skiftet til citizen mode) ...

Som jeg nævnte i min kommentar så er jeg klar over dette problem men løsningen til dette problem virker som et andet issue da det i bund og grund er fordi der ikke eksistere et citizen view til weekplan_selector_screen

2021-09-27 07:46 UTC, MathiasNielsen1206 requested changes
Fandt lige ud af at  man stadig kan lave en ny ugeplan efter at man er skiftet til borger, det forestiller jeg mig ikke er hensigten. 

Så der skal nok laves et check på om man er i guardian mode, når man trykker på lav ugeplan.
Eller at man fjerner den knap når man er i borger mode.

2021-09-28 06:48 UTC, MathiasNielsen1206 approved these changes

2021-09-29 10:52 UTC, closed without merging