Feature/713
aau-giraf/weekplanner-OLDUI pull request #743
Opened 2021-09-23 08:36 UTC by ChristofferAAU

Made it so that the buttons are unresponsive when a weekplan is not selected.

2021-09-28 12:37 UTC, JakobFaarGreg commented
- [ ] The environments.json file has the following default values:
{
  "SERVER_HOST": "https://srv.giraf.cs.aau.dk/DEV/API",
  "DEBUG": true,
  "USERNAME": "Graatand",
  "PASSWORD": "password"
}


Code Design 

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is unnecessary for solving the problem

Code Readability 

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution

Code Maintainability

- [ ] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does not need to be covered by tests
- [ ] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

Functionality

For this part, open the app, and test:
- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

2021-09-28 12:41 UTC, JakobFaarGreg commented
#713

2021-09-28 12:54 UTC, JakobFaarGreg approved these changes, later dismissed
Everything looks good to me.

2021-10-05 06:55 UTC, HowToYEET requested changes

2021-10-05 06:55 UTC, HowToYEET commented on lib/screens/weekplan_selector_screen.dart
> +    if(widget._weekBloc.getNumberOfMarkedWeekModels() < 1){
begge sider af condition mangler mellemrum

2021-10-05 07:04 UTC, ChristofferAAU commented on lib/screens/weekplan_selector_screen.dart
> +    if(widget._weekBloc.getNumberOfMarkedWeekModels() < 1){
Done

2021-10-07 09:01 UTC, HowToYEET submitted a review, later dismissed

2021-10-12 09:22 UTC, JakobFaarGreg commented on lib/screens/login_screen.dart
> +      //resizeToAvoidBottomPadding: false, --Fix this
```suggestion
    
```

2021-10-12 09:28 UTC, JakobFaarGreg commented on lib/screens/weekplan_selector_screen.dart
> +            }else {
```suggestion
            } else {
```

2021-10-12 09:28 UTC, JakobFaarGreg commented on lib/screens/weekplan_selector_screen.dart
> +                      onPressed: () async => _pushEditWeekPlan(context),
```suggestion
                      onPressed: () async => _pushEditWeekPlan(context)
```

2021-10-12 09:30 UTC, JakobFaarGreg requested changes
Jeg har et par små ændringer der gerne skal fixes.

2021-10-12 09:45 UTC, ChristofferAAU commented
> Jeg har et par små ændringer der gerne skal fixes.

Burde være fikset nu

2021-10-12 11:28 UTC, JakobFaarGreg approved these changes

2021-10-13 07:27 UTC, HowToYEET approved these changes

2021-10-13 07:29 UTC, merged