feature 702: Fixed  weeks  being "done" around new years
aau-giraf/weekplanner-OLDUI pull request #747
Opened 2021-09-27 13:10 UTC by Nima-Moayedzadeh

Fix to "overstående uger" around new year.

2021-09-29 07:13 UTC, kristnaKris commented on lib/blocs/weekplan_selector_bloc.dart
> +    if (weekPlan.weekYear < currentYear && weekPlan.weekNumber != currentWeek ||
currentWeek vil den første januar retunere uge 1 så hvis vi tager eksemplet fra issuen så vil jeres sætning stadig retuenere true da: weekPlan.weekYear = 2020, currentYear = 2021, weekPlan.weekNumber = 53 og currentWeek = 1. logikken bliver derfor "`2020 < 2021 && 53 != 1`" dette vil evaluere til true og vil derfor terminere ugen.

2021-09-29 07:16 UTC, kristnaKris requested changes
currentWeek vil den første januar retunere uge 1 så hvis vi tager eksemplet fra issuen så vil jeres sætning stadig retuenere true da: weekPlan.weekYear = 2020, currentYear = 2021, weekPlan.weekNumber = 53 og currentWeek = 1. logikken bliver derfor "`2020 < 2021 && 53 != 1`" dette vil evaluere til true og vil derfor terminere ugen.

2021-09-29 07:25 UTC, kristnaKris commented on lib/blocs/weekplan_selector_bloc.dart
> +    if (weekPlan.weekYear < currentYear && weekPlan.weekNumber != currentWeek ||
https://github.com/dotnet/runtime/blob/b41f1c5f2fde25d752d857a54c3af24145060cdd/src/libraries/System.Private.CoreLib/src/System/Globalization/ISOWeek.cs
Her er nogle functioner som .net bruger til at overholde ISO standarten

2021-11-12 07:46 UTC, goldflue requested changes
Bare en friendly reminder - Enig det andet review

2021-12-13 12:24 UTC, closed without merging