Flutter/feature 047 choose citizen
aau-giraf/weekplanner-OLDUI pull request #87
Opened 2019-03-20 12:55 UTC by Tricky12321

There is a lot of issues solved in this pull request:
#47 Choose Citizen
Loading screen (Not a issue, but a feature that was needed)
#83 Load configuration from file
#73 Auto-Login
#35 Login Screen (Remake of design)

![Screenshot_20190320-102314](https://user-images.githubusercontent.com/10461592/54685711-c69cb300-4b17-11e9-8bea-5e5dfff30175.jpg)
![Screenshot_20190320-102520](https://user-images.githubusercontent.com/10461592/54685712-c7354980-4b17-11e9-863e-747bc7ad2baf.jpg)
![Screenshot_20190320-102322](https://user-images.githubusercontent.com/10461592/54685713-c7354980-4b17-11e9-8b5f-ec1b8844f14e.jpg)
![Screenshot_20190320-102525](https://user-images.githubusercontent.com/10461592/54685715-c7354980-4b17-11e9-843d-8ce6d2219a22.jpg)

2019-03-20 13:00 UTC, boginw commented on lib/providers/api/api.dart
> +  Api(this.EnvVariables) {
The API should never know about the environment variables, therefore, it would be better to have to constructor look like this:
```dart
final String url;
final String port;

Api({this.url, this.port}) {
```

2019-03-20 13:01 UTC, boginw commented on lib/blocs/choose_citizen_bloc.dart
> +  }*/
This doesn't look necessary

2019-03-20 13:02 UTC, boginw commented on lib/bootstrap.dart
> +      return Api(i.getDependency<EnvoironmentBloc>());
See Api.dart for a comment on this

2019-03-21 08:12 UTC, TobiasPalludan requested changes
Needs tests. Will review after :)

2019-03-21 11:00 UTC, boginw requested changes

2019-03-21 11:00 UTC, boginw commented on lib/blocs/environment_bloc.dart
> +class EnvoironmentBloc extends BlocBase {
Is this really a BLoC? Isn't this a provider?

2019-03-21 11:00 UTC, boginw commented on lib/blocs/environment_bloc.dart
> +  T getVar<T>(String variableName) {
This method, with all the switching and casing, is very hacky. I suggest using the JSON decoder which is already used in the API and the models, to parse the file, which automatically gives us primary types. Loading of files from the asset folder is as simple as `String envString = await rootBundle.loadString('assets/environment.json);` and parsing is as simple as `json.decode(envString)`.

2019-03-21 11:00 UTC, boginw commented on assets/envoironments.env
> +SERVER_URL=web.giraf.cs.aau.dk
See comment on `getVar`

2019-03-21 11:00 UTC, boginw commented on assets/envoironments.prod.env
> +SERVER_URL=web.giraf.cs.aau.dk
See comment on `getVar`

2019-03-21 11:00 UTC, boginw commented on lib/providers/api/api.dart
> +    baseUrl = "http://" + serverUrl + ":" + serverPort;
Why keep `http` here? What if we update to https on a later point?

2019-03-21 11:00 UTC, boginw commented on lib/screens/choose_citizen_screen.dart
> +    bool Portrait = MediaQuery.of(context).orientation == Orientation.portrait;
naming convention

2019-03-21 11:00 UTC, boginw commented on lib/screens/choose_citizen_screen.dart
> +    _bloc.load();
This adds a new call for each rebuild! That's madness!

2019-03-21 11:00 UTC, boginw commented on lib/screens/choose_citizen_screen.dart
> +            image: AssetImage("assets/login_screen_background_image.png"),
could be const?

2019-03-21 11:00 UTC, boginw commented on lib/screens/login_screen.dart
> +    bool Portrait = MediaQuery.of(context).orientation == Orientation.portrait;
naming convention

2019-03-21 11:00 UTC, boginw commented on lib/screens/login_screen.dart
> +    bool Keyboard = MediaQuery.of(context).viewInsets.bottom > 100;
naming convention

2019-03-21 11:00 UTC, boginw commented on lib/screens/login_screen.dart
> +            image: AssetImage("assets/login_screen_background_image.png"),
const?

2019-03-21 11:00 UTC, boginw commented on lib/screens/login_screen.dart
> +                                child: Text(
const?

2019-03-21 11:00 UTC, boginw commented on lib/screens/login_screen.dart
> +                                      .getDependency<EnvoironmentBloc>()
This is the third time you get the same dependency. It would absolutely make sense to save your dependency for easier access, and performance.

2019-03-21 11:00 UTC, boginw commented on lib/blocs/environment_bloc.dart
> +class EnvoironmentBloc extends BlocBase {
Also it is spelled wrong

2019-03-21 11:00 UTC, boginw commented on lib/screens/login_screen.dart
> +        image: AssetImage("assets/giraf_splash_logo.png"),
const?

2019-03-21 11:00 UTC, boginw commented on lib/widgets/giraf_app_bar_simple_widget.dart
> +  // Adding this.variablename to the constructor automatically assigns the value to the right variable.
Commenting on nothing?

2019-03-21 11:00 UTC, boginw commented on lib/widgets/giraf_dialog_header.dart
> +  // Adding this.variablename to the constructor automatically assigns the value to the right variable.
Commenting on nothing?

2019-03-21 11:00 UTC, boginw commented on lib/widgets/giraf_dialog_header.dart
> +                  0.33,
Is it just me, but the indentation here?

2019-03-21 11:00 UTC, boginw commented on lib/widgets/giraf_notify_dialog.dart
> +  // Adding this.variablename to the constructor automatically assigns the value to the right variable.
Commenting on nothing

2019-03-21 11:00 UTC, boginw commented on lib/widgets/giraf_notify_dialog.dart
> +                        Text(
const?

2019-03-21 11:00 UTC, boginw commented on lib/widgets/giraf_notify_dialog.dart
> +                        Icon(
const?

2019-03-21 11:00 UTC, boginw commented on pubspec.yaml
> +  flutter_dotenv: ^2.0.1
See comment on  `getVar`

2019-03-21 13:28 UTC, Tricky12321 commented on lib/blocs/environment_bloc.dart
> +class EnvoironmentBloc extends BlocBase {
Fixed, corrected spelling, and changed to be a provider

2019-03-21 13:28 UTC, Tricky12321 commented on lib/blocs/environment_bloc.dart
> +  T getVar<T>(String variableName) {
This is now fixed, and instead of env, json is used

2019-03-21 13:29 UTC, Tricky12321 commented on lib/providers/api/api.dart
> +    baseUrl = "http://" + serverUrl + ":" + serverPort;
Added Protocol to JSON file, to allow for changes in protocol

2019-03-21 13:29 UTC, Tricky12321 commented on lib/widgets/giraf_dialog_header.dart
> +                  0.33,
Don't know, IntelliJ seems to format it this way?

2019-03-21 13:30 UTC, Tricky12321 commented on lib/widgets/giraf_notify_dialog.dart
> +                        Icon(
Added const, maybe colors should be a provider?

2019-03-21 13:31 UTC, Tricky12321 commented on pubspec.yaml
> +  flutter_dotenv: ^2.0.1
Fixed

2019-03-21 13:31 UTC, Tricky12321 commented on lib/widgets/giraf_notify_dialog.dart
> +                        Text(
Added const, maybe colors should be a provider?

2019-03-21 13:31 UTC, Tricky12321 commented on lib/widgets/giraf_notify_dialog.dart
> +  // Adding this.variablename to the constructor automatically assigns the value to the right variable.
Removed

2019-03-21 13:55 UTC, Tricky12321 commented on lib/screens/choose_citizen_screen.dart
> +    bool Portrait = MediaQuery.of(context).orientation == Orientation.portrait;
Fixed

2019-03-21 13:57 UTC, Tricky12321 commented on lib/screens/choose_citizen_screen.dart
> +            image: AssetImage("assets/login_screen_background_image.png"),
Done

2019-03-21 14:00 UTC, Tricky12321 commented on lib/screens/login_screen.dart
> +    bool Portrait = MediaQuery.of(context).orientation == Orientation.portrait;
Fixed

2019-03-21 14:00 UTC, Tricky12321 commented on lib/screens/login_screen.dart
> +    bool Keyboard = MediaQuery.of(context).viewInsets.bottom > 100;
Fixed

2019-03-21 14:01 UTC, Tricky12321 commented on lib/screens/login_screen.dart
> +            image: AssetImage("assets/login_screen_background_image.png"),
Fixed

2019-03-21 14:03 UTC, Tricky12321 commented on lib/screens/choose_citizen_screen.dart
> +    _bloc.load();
Fixed, the call is now done in the constructor of ChooseCitizenBloc

2019-03-21 14:04 UTC, Tricky12321 commented on lib/screens/login_screen.dart
> +                                child: Text(
This is not possible...

2019-03-21 14:05 UTC, Tricky12321 commented on lib/screens/login_screen.dart
> +                                      .getDependency<EnvoironmentBloc>()
This is changed with the JSON rewrite instead of ENV

2019-03-21 14:05 UTC, Tricky12321 commented on lib/screens/login_screen.dart
> +        image: AssetImage("assets/giraf_splash_logo.png"),
Fixed

2019-03-21 14:05 UTC, Tricky12321 commented on lib/widgets/giraf_app_bar_simple_widget.dart
> +  // Adding this.variablename to the constructor automatically assigns the value to the right variable.
Fixed

2019-03-21 14:05 UTC, Tricky12321 commented on lib/widgets/giraf_dialog_header.dart
> +  // Adding this.variablename to the constructor automatically assigns the value to the right variable.
Fixed

2019-03-21 14:16 UTC, boginw requested changes

2019-03-21 14:16 UTC, boginw commented on lib/providers/environment_provider.dart
> +class EnvironmentProvider extends BlocBase {
To follow the naming convention of the rest of the providers (except BlocProvider, which now is unused), please rename this provider to `Environment`. Also, does it really need to extend BlocBase?

2019-03-21 14:16 UTC, boginw commented on lib/providers/environment_provider.dart
> +import 'dart:convert' as JSON;
Why the `as`? The used function is already called `jsonDecode`?

2019-03-21 14:16 UTC, boginw commented on lib/providers/environment_provider.dart
> +  static void setFile(String FileLocation) async {
FileLocation: Naming convention

2019-03-21 14:16 UTC, boginw commented on lib/providers/environment_provider.dart
> +  static void setFile(String FileLocation) async {
also, it returns Future<void>, not void

2019-03-21 14:16 UTC, boginw commented on lib/providers/environment_provider.dart
> +  static Future<String> _getFileData(String path) async {
You're not saving anything with this function, and I don't see a reason for it existing

2019-03-21 14:16 UTC, boginw commented on lib/screens/choose_citizen_screen.dart
> +  final ChooseCitizenBloc _bloc;
```suggestion
  final ChooseCitizenBloc _bloc = di.getDependency<ChooseCitizenBloc>();
```

2019-03-21 14:16 UTC, boginw commented on lib/screens/choose_citizen_screen.dart
> +  ChooseCitizenScreen() : _bloc = di.getDependency<ChooseCitizenBloc>();
```suggestion
```

2019-03-21 14:16 UTC, boginw commented on lib/screens/choose_citizen_screen.dart
> +  Widget chooseCitizenDialog() {}
Empty method

2019-03-21 14:16 UTC, boginw commented on lib/widgets/giraf_app_bar_simple_widget.dart
> +  // Adding this.variablename to the constructor automatically assigns the value to the right variable.
Where?

2019-03-21 14:16 UTC, boginw commented on lib/widgets/giraf_notify_dialog.dart
> +                        Icon(
Cannot see that it is fixed

2019-03-21 14:17 UTC, Tricky12321 commented on lib/widgets/giraf_app_bar_simple_widget.dart
> +  // Adding this.variablename to the constructor automatically assigns the value to the right variable.
now... missed it

2019-03-21 14:20 UTC, Tricky12321 commented on lib/providers/environment_provider.dart
> +class EnvironmentProvider extends BlocBase {
Fixed

2019-03-21 14:20 UTC, Tricky12321 commented on lib/providers/environment_provider.dart
> +import 'dart:convert' as JSON;
Fixed

2019-03-21 14:30 UTC, Tricky12321 commented on lib/providers/environment_provider.dart
> +  static void setFile(String FileLocation) async {
Fixed

2019-03-21 14:30 UTC, Tricky12321 commented on lib/providers/environment_provider.dart
> +  static Future<String> _getFileData(String path) async {
Fixed

2019-03-21 14:30 UTC, Tricky12321 commented on lib/screens/choose_citizen_screen.dart
> +  final ChooseCitizenBloc _bloc;
Fixed

2019-03-21 14:30 UTC, Tricky12321 commented on lib/screens/choose_citizen_screen.dart
> +  ChooseCitizenScreen() : _bloc = di.getDependency<ChooseCitizenBloc>();
Fixed

2019-03-21 14:30 UTC, Tricky12321 commented on lib/screens/choose_citizen_screen.dart
> +  Widget chooseCitizenDialog() {}
Fixed

2019-03-21 15:04 UTC, boginw requested changes

2019-03-21 15:04 UTC, boginw commented on lib/widgets/giraf_dialog_header.dart
> +  final Size preferredSize;
move member to the correct place

2019-03-21 15:04 UTC, boginw commented on lib/widgets/giraf_notify_dialog.dart
> +  final Size preferredSize;
move member to the correct place

2019-03-21 15:04 UTC, boginw commented on lib/blocs/choose_citizen_bloc.dart
> +  void load() {
this method is *only* called in the constructor. Wouldn't it make sense then to put it in the constructor?

2019-03-21 15:04 UTC, boginw commented on lib/blocs/choose_citizen_bloc.dart
> +  BehaviorSubject<List<UsernameModel>> _citizens = BehaviorSubject();
final?

2019-03-21 15:04 UTC, boginw commented on lib/blocs/choose_citizen_bloc.dart
> +  Api _api;
final?

2019-03-21 15:04 UTC, boginw commented on lib/blocs/choose_citizen_bloc.dart
> +  BehaviorSubject<List<UsernameModel>> _citizens = BehaviorSubject();
and ordering

2019-03-21 15:04 UTC, boginw commented on assets/environments.json
> +  "SERVER_URL": "web.giraf.cs.aau.dk",
It does not make sense to have to call this ...URL if it does not include the scheme and port. Either change the value to "http://web.giraf.cs.aau.dk:5000" or change the name to "SERVER_HOST".

2019-03-21 15:04 UTC, boginw commented on lib/screens/login_screen.dart
> +                                child: Text(
Would it not be possible if the inner TextStyle is also made const?

2019-03-29 09:09 UTC, TobiasPalludan requested changes
We couldn't see any citizens. Have you added some, or do we have an erroneous setup?

2019-03-29 09:09 UTC, TobiasPalludan commented on lib/blocs/choose_citizen_bloc.dart
> +  final BehaviorSubject<List<UsernameModel>> _citizens = BehaviorSubject();
You need a seeding (default) value here, as the first access might otherwise give weird results.

2019-03-29 09:09 UTC, TobiasPalludan commented on lib/bootstrap.dart
> -      return Api('http://web.giraf.cs.aau.dk:5000');
Is this using the environments files? The server is not the same. Has it been changed, or is it an error?

2019-03-29 09:09 UTC, TobiasPalludan commented on lib/bootstrap.dart
> +    di.registerSingleton((Injector i) {
No need to include the injector, as it isn't used.

2019-03-29 09:09 UTC, TobiasPalludan commented on lib/bootstrap.dart
> -      return ToolbarBloc();
Why do you delete ToolbarBloc? Isn't it used by the giraf_app_bar_widget?

2019-03-29 09:09 UTC, TobiasPalludan commented on lib/screens/login_screen.dart
> +                                      Environment.getVar<String>("PASSWORD");
It's a small request, but could we make the auto-login button actually send the login request, instead of just filling the fields?

2019-03-29 09:09 UTC, TobiasPalludan commented on test/providers/environment_test.dart
> +  setUp(() {});
Empty setup?

2019-03-29 09:09 UTC, TobiasPalludan commented on test/widgets/choose_citizen_screen_test.dart
> +    await tester.pump(Duration(seconds: 3));
PumpAndSettle is probably a better function, since it simply waits until there is no more "new" frames to render, and thus there is no need for guesswork.

2019-03-29 09:09 UTC, TobiasPalludan commented on test/widgets/choose_citizen_screen_test.dart
> +    await tester.pump(Duration(seconds: 3));
Same point as before with pumpAndSettle.

2019-03-29 09:09 UTC, TobiasPalludan commented on test/widgets/choose_citizen_screen_test.dart
> +  //TODO: Test if the correct weekplanner screen is shown
Don't create todo's. Either do it, or add it as an issue, if you don't think it's part of your scope.

2019-03-29 09:09 UTC, TobiasPalludan commented on test/widgets/login_screen_test.dart
> +      "Logging in with correct information works, and should show a ChooseCitizenScreen",
This passes if we run all tests, but if we run it individually this test fails with:
```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following FormatException was thrown running a test:
Unexpected end of input (at character 1)

^

When the exception was thrown, this was the stack:
#0      _ChunkedJsonParser.fail (dart:convert/runtime/libconvert_patch.dart:1357:5)
#1      _ChunkedJsonParser.close (dart:convert/runtime/libconvert_patch.dart:510:7)
#2      _parseJson (dart:convert/runtime/libconvert_patch.dart:30:10)
#3      JsonDecoder.convert (dart:convert/json.dart:491:36)
#4      JsonCodec.decode (dart:convert/json.dart:149:41)
#5      jsonDecode (dart:convert/json.dart:89:10)
#6      Environment.getVar (package:weekplanner/providers/environment_provider.dart:11:12)
#7      new LoginScreen (package:weekplanner/screens/login_screen.dart:16:40)
#8      main.<anonymous closure> (file:///home/tobias/repos/weekplanner/test/widgets/login_screen_test.dart:106:47)
<asynchronous suspension>
#9      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:82:23)
#10     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:571:19)
<asynchronous suspension>
#13     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:555:14)
#14     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:898:24)
#20     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:895:15)
#21     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:81:22)
#22     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:27)
<asynchronous suspension>
#23     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:250:15)
<asynchronous suspension>
#28     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:247:5)
#29     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:166:33)
#34     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:165:13)
<asynchronous suspension>
#35     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:400:25)
<asynchronous suspension>
#49     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#50     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#51     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
(elided 28 frames from class _FakeAsync, package dart:async, and package stack_trace)

The test description was:
Logging in with correct information works, and should show a ChooseCitizenScreen
════════════════════════════════════════════════════════════════════════════════════════════════════

```

2019-03-29 09:09 UTC, TobiasPalludan commented on test/widgets/login_screen_test.dart
> +  testWidgets('Renders LoginScreen', (WidgetTester tester) async {
This passes if we run all tests, but if we run it individually this test fails with:
```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following FormatException was thrown running a test:
Unexpected end of input (at character 1)

^

When the exception was thrown, this was the stack:
#0      _ChunkedJsonParser.fail (dart:convert/runtime/libconvert_patch.dart:1357:5)
#1      _ChunkedJsonParser.close (dart:convert/runtime/libconvert_patch.dart:510:7)
#2      _parseJson (dart:convert/runtime/libconvert_patch.dart:30:10)
#3      JsonDecoder.convert (dart:convert/json.dart:491:36)
#4      JsonCodec.decode (dart:convert/json.dart:149:41)
#5      jsonDecode (dart:convert/json.dart:89:10)
#6      Environment.getVar (package:weekplanner/providers/environment_provider.dart:11:12)
#7      new LoginScreen (package:weekplanner/screens/login_screen.dart:16:40)
#8      main.<anonymous closure> (file:///home/tobias/repos/weekplanner/test/widgets/login_screen_test.dart:70:47)
<asynchronous suspension>
#9      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:82:23)
#10     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:571:19)
<asynchronous suspension>
#13     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:555:14)
#14     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:898:24)
#20     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:895:15)
#21     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:81:22)
#22     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:27)
<asynchronous suspension>
#23     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:250:15)
<asynchronous suspension>
#28     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:247:5)
#29     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:166:33)
#34     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:165:13)
<asynchronous suspension>
#35     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:400:25)
<asynchronous suspension>
#49     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#50     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#51     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
(elided 28 frames from class _FakeAsync, package dart:async, and package stack_trace)

The test description was:
Renders LoginScreen
════════════════════════════════════════════════════════════════════════════════════════════════════
```

2019-03-29 09:09 UTC, TobiasPalludan commented on test/widgets/login_screen_test.dart
> +      "Logging in with wrong information should show a GirafNotifyDialog",
This passes if we run all tests, but if we run it individually this test fails with:
```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following FormatException was thrown running a test:
Unexpected end of input (at character 1)

^

When the exception was thrown, this was the stack:
#0      _ChunkedJsonParser.fail (dart:convert/runtime/libconvert_patch.dart:1357:5)
#1      _ChunkedJsonParser.close (dart:convert/runtime/libconvert_patch.dart:510:7)
#2      _parseJson (dart:convert/runtime/libconvert_patch.dart:30:10)
#3      JsonDecoder.convert (dart:convert/json.dart:491:36)
#4      JsonCodec.decode (dart:convert/json.dart:149:41)
#5      jsonDecode (dart:convert/json.dart:89:10)
#6      Environment.getVar (package:weekplanner/providers/environment_provider.dart:11:12)
#7      new LoginScreen (package:weekplanner/screens/login_screen.dart:16:40)
#8      main.<anonymous closure> (file:///home/tobias/repos/weekplanner/test/widgets/login_screen_test.dart:128:47)
<asynchronous suspension>
#9      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:82:23)
#10     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:571:19)
<asynchronous suspension>
#13     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:555:14)
#14     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:898:24)
#20     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:895:15)
#21     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:81:22)
#22     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:27)
<asynchronous suspension>
#23     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:250:15)
<asynchronous suspension>
#28     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:247:5)
#29     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:166:33)
#34     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:165:13)
<asynchronous suspension>
#35     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:400:25)
<asynchronous suspension>
#49     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#50     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#51     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
(elided 28 frames from class _FakeAsync, package dart:async, and package stack_trace)

The test description was:
Logging in with wrong information should show a GirafNotifyDialog
════════════════════════════════════════════════════════════════════════════════════════════════════
```

2019-04-02 06:23 UTC, Tricky12321 commented on lib/blocs/choose_citizen_bloc.dart
> +  final BehaviorSubject<List<UsernameModel>> _citizens = BehaviorSubject();
This has been fixed, there was a problem in the Login API, which is now fixed. This was not an issue for us to solve, and was solved in #101

2019-04-02 06:24 UTC, Tricky12321 commented on lib/bootstrap.dart
> -      return Api('http://web.giraf.cs.aau.dk:5000');
There are currently 2 servers
The original 
http://web.giraf.cs.aau.dk:5000
and
http://srv.giraf.cs.aau.dk/API

This is part of the new servers, and http://srv.giraf.cs.aau.dk/API should be used from this point forward

2019-04-02 06:30 UTC, Tricky12321 commented on lib/bootstrap.dart
> +    di.registerSingleton((Injector i) {
It has been removed

2019-04-02 06:30 UTC, Tricky12321 commented on lib/bootstrap.dart
> -      return ToolbarBloc();
There was some merge issues, this has been fixed

2019-04-02 06:30 UTC, Tricky12321 commented on lib/screens/login_screen.dart
> +                                      Environment.getVar<String>("PASSWORD");
Sure 🥇

2019-04-02 06:35 UTC, Tricky12321 commented on test/widgets/choose_citizen_screen_test.dart
> +  //TODO: Test if the correct weekplanner screen is shown
This has been fixed, Linter was also angry

2019-04-02 06:35 UTC, Tricky12321 commented on test/widgets/login_screen_test.dart
> +      "Logging in with correct information works, and should show a ChooseCitizenScreen",
This has been fixed, this was a problem with Environments

2019-04-02 06:35 UTC, Tricky12321 commented on test/widgets/login_screen_test.dart
> +  testWidgets('Renders LoginScreen', (WidgetTester tester) async {
This has been fixed, this was a problem with Environments

2019-04-02 06:35 UTC, Tricky12321 commented on test/widgets/login_screen_test.dart
> +      "Logging in with wrong information should show a GirafNotifyDialog",
This has been fixed, this was a problem with Environments

2019-04-02 09:15 UTC, TobiasPalludan submitted a review, later dismissed

2019-04-02 11:01 UTC, boginw requested changes
To all methods and classes added by you, you should document their purpose

2019-04-02 11:01 UTC, boginw commented on assets/environments.json.dist
> +{
what's the point of these `.dist` files?

2019-04-02 11:01 UTC, boginw commented on .gitignore
> +assets/environments.json
Why?

2019-04-02 11:01 UTC, boginw commented on lib/main.dart
> +              snapshot.data ? ChooseCitizenScreen() : LoginScreen())));
Why remove the descriptive comment?

2019-04-02 11:01 UTC, boginw commented on lib/models/response_model.dart
> +        (ErrorKey f) => f.toString() == json['errorKey'],
Please see [api_client](https://github.com/aau-giraf/api_client)'s version of this line. This line will not work

2019-04-02 11:01 UTC, boginw commented on lib/providers/environment_provider.dart
> +    return jsonDecode(_content)[variableName];
No need to decode every time we get a variable

2019-04-02 11:01 UTC, boginw commented on lib/screens/login_screen.dart
> +  AuthBloc get authBloc => di.getDependency<AuthBloc>();
does this have to be a getter? Couldn't it just be `final AuthBloc authBloc = di.getDependency<AuthBloc>();` ?

2019-04-02 11:01 UTC, boginw commented on lib/screens/login_screen.dart
> -/// Logs the user in
Why do you remove documentation?

2019-04-02 11:01 UTC, boginw commented on lib/screens/login_screen.dart
> +  static bool loggedInSuccessfull = false;
This is a major no-no. A stateless widget is a widget that can be constructed at any time and is expected to give the same result. You just introduced a state. Also, this is business logic, and should probably be put in a bloc

2019-04-02 11:01 UTC, boginw commented on lib/screens/login_screen.dart
> +      if (status) {
```dart
loggedInSuccessfull = status;
```

achieves the same

2019-04-02 11:01 UTC, boginw commented on lib/screens/login_screen.dart
> +    authBloc.loggedIn.listen((bool status) async {
You're listening to all updates. This subscription should be killed on dispose

2019-04-02 11:01 UTC, boginw commented on lib/screens/login_screen.dart
> +  Future<bool> loginAction() async {
Why bool?

2019-04-02 11:01 UTC, boginw commented on lib/screens/login_screen.dart
> +    return true;
Since you always return true we can rewrite this to be of void

2019-04-02 11:01 UTC, boginw commented on lib/screens/login_screen.dart
> +    final bool keyboard = MediaQuery.of(context).viewInsets.bottom > 100;
Is this certain that this would be a keyboard? Also, what if I have a lower keyboard than 100?

2019-04-02 11:01 UTC, boginw commented on lib/screens/login_screen.dart
> +      scale: portrait ? 1.0 : 0.5,
These portrait ternaries seem very tailored to a single device. Shouldn't this be scalable no matter if portrait or not? What about maxWidth & maxHeight?

2019-04-02 11:01 UTC, boginw commented on lib/screens/login_screen.dart
> +  static void showLoadingScreen(BuildContext context, bool dismissible,
Unused function, please remove

2019-04-02 11:01 UTC, boginw commented on lib/widgets/citizen_avatar_widget.dart
> +  final BuildContext parentContext;
Unused context, please remove

2019-04-02 11:01 UTC, boginw commented on lib/widgets/citizen_avatar_widget.dart
> +                      child: AutoSizeText(
wouldn't it better to cut with ellipsis instead of resizing? Think of a user with a very long username

2019-04-02 11:01 UTC, boginw commented on lib/widgets/citizen_avatar_widget.dart
> +          Routes.push(context, WeekplanScreen());
First, is it the widget's responsibility to navigate, or should it tell its parent, with a callback, that it was tapped? Second, shouldn't it feed some information of the choice to the WeekplanScreen?

2019-04-02 11:01 UTC, boginw commented on lib/widgets/giraf_app_bar_widget.dart
> +                    icon: const Icon(Icons.edit),
Please use icons from the design guide

2019-04-02 11:01 UTC, boginw commented on test/blocs/choose_citizen_bloc_test.dart
> +      if (response.length == 1) {
you should expect(response.length, 1)

2019-04-02 11:01 UTC, boginw commented on test/blocs/choose_citizen_bloc_test.dart
> +        if (rsp.name == 'test1' && rsp.role == 'test1' && rsp.id == '1') {
These should be expectations

2019-04-02 11:01 UTC, boginw commented on test/providers/environment_test.dart
> +    if (Environment.getVar<String>('SERVER_HOST') ==
I'm not going to comment on every file, but you shouldn't use if as expect.

2019-04-02 11:01 UTC, boginw commented on test/screens/choose_citizen_screen_test.dart
> +  testWidgets('Click Citizen (Avatar)', (WidgetTester tester) async {
remove if unused

2019-04-02 11:22 UTC, Tricky12321 commented on assets/environments.json.dist
> +{
I talked with Tobias, as to the files should not be commited, since people make changes to them, therefore the dist files, for people to copy and edit

2019-04-02 11:22 UTC, Tricky12321 commented on .gitignore
> +assets/environments.json
They should not be pushed to the git, only the dist files

2019-04-02 11:24 UTC, Tricky12321 commented on lib/main.dart
> +              snapshot.data ? ChooseCitizenScreen() : LoginScreen())));
Readded

2019-04-02 11:24 UTC, boginw commented on .gitignore
> +assets/environments.json
why? is there anything sensitive in these files?

2019-04-02 11:25 UTC, boginw commented on assets/environments.json.dist
> +{
I see, but that adds an extra step for all beginners, AND that breaks the CI.

2019-04-02 11:26 UTC, Tricky12321 commented on lib/models/response_model.dart
> +        (ErrorKey f) => f.toString() == json['errorKey'],
This is not related to this PR, this is an issue in the API?

2019-04-02 11:28 UTC, boginw commented on lib/models/response_model.dart
> +        (ErrorKey f) => f.toString() == json['errorKey'],
You're right it's not. But you claimed the line, so I'm giving you the information needed to fix it

2019-04-02 11:30 UTC, Tricky12321 commented on lib/providers/environment_provider.dart
> +    return jsonDecode(_content)[variableName];
Fixed

2019-04-02 11:30 UTC, Tricky12321 commented on lib/widgets/giraf_app_bar_widget.dart
> +                    icon: const Icon(Icons.edit),
This is not a file related to this PR, this is in another PR.

2019-04-02 11:31 UTC, boginw commented on lib/providers/environment_provider.dart
> +    return jsonDecode(_content)[variableName];
Why are you always commenting "fixed" on the line when it is clear that it hasn't been fixed yet?

2019-04-02 11:31 UTC, Tricky12321 commented on test/blocs/choose_citizen_bloc_test.dart
> +      if (response.length == 1) {
But there is more than that

2019-04-02 11:31 UTC, Tricky12321 commented on test/blocs/choose_citizen_bloc_test.dart
> +      if (response.length == 1) {
But there is more

2019-04-02 11:32 UTC, boginw commented on lib/widgets/giraf_app_bar_widget.dart
> +                    icon: const Icon(Icons.edit),
These are lines you've added, and you should follow the design guide

2019-04-02 11:33 UTC, Tricky12321 commented on test/blocs/choose_citizen_bloc_test.dart
> +        if (rsp.name == 'test1' && rsp.role == 'test1' && rsp.id == '1') {
There can only be one expect?

2019-04-02 11:33 UTC, boginw commented on test/blocs/choose_citizen_bloc_test.dart
> +      if (response.length == 1) {
So? The test should fail if the length is not 1, and therefore we `expect` response.length to be 1

2019-04-02 11:34 UTC, boginw commented on test/blocs/choose_citizen_bloc_test.dart
> +        if (rsp.name == 'test1' && rsp.role == 'test1' && rsp.id == '1') {
of course not! 
```dart
expect(rsp.name, "test1");
expect(rsp.role, "test1");
```
just did 2 for you

2019-04-02 11:50 UTC, TobiasPalludan commented on .gitignore
> +assets/environments.json
No, but this is specific for every user. Much like Laravel's .env files.

2019-04-02 11:54 UTC, boginw requested changes
This awaiting changes from the last time. Here are a few more. Please notify me when you've fixed everything and not just a subset

2019-04-02 11:54 UTC, boginw commented on lib/blocs/choose_citizen_bloc.dart
> +  final BehaviorSubject<List<UsernameModel>> _citizens =
Defining a default behaviour is good, and therefore this should be seeded

2019-04-02 11:54 UTC, boginw commented on lib/bootstrap.dart
> +  static Future<void> register() async {
Why is this function async? there is nothing to await?

2019-04-02 11:54 UTC, boginw commented on lib/providers/api/api.dart
> -  /// `/search` will resolve to `http://google.com/search`
why remove?

2019-04-02 11:54 UTC, boginw commented on lib/providers/environment_provider.dart
> +// ignore: avoid_classes_with_only_static_members
this should not be ignored. Your class DOES only contain static members, and then should not be a class at all.

2019-04-02 12:00 UTC, boginw commented on .gitignore
> +assets/environments.json
Laravels' .env files are not added to git because they contain sensitive data. Ours don't

2019-04-03 15:36 UTC, boginw submitted a review, later dismissed

2019-04-03 16:12 UTC, TobiasPalludan requested changes

2019-04-03 16:12 UTC, TobiasPalludan commented on .gitignore
> +assets/environments.prod.json
After talking to @boginw this shouldn't be ignored, because the production setup shouldn't be developer-specific.

2019-04-03 16:12 UTC, TobiasPalludan commented on .gitignore
> +assets/environments.json
@boginw I think we agreed that this should in fact be ignored, right? This both allows for a default option that is set when cloning the repository, thus giving easy setup for new developers, while it still allows for configuration of a local environment.

2019-04-03 19:24 UTC, TobiasPalludan submitted a review, later dismissed

2019-04-04 10:30 UTC, boginw approved these changes

2019-04-04 10:32 UTC, TobiasPalludan approved these changes

2019-04-04 10:34 UTC, merged