Feature/346
aau-giraf/weekplanner-OLDUI pull request #877
Opened 2022-10-12 09:19 UTC by Taoshix

# Description

*Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.*

Fixes #346

## Type of change
*Delete unchecked boxes (only for Type of change)*

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration*

**Development Configuration**
*Type "flutter --version" and "dart --version" in your CMD to check versions.*

* Flutter version:
* Dart version:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas, if necessary
- [ ] I have made corresponding changes to the documentation, if necessary
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works, if necessary
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] I have Acceptance Tested this on an iOS device
- [x] I have Acceptance Tested this on an Android device

2022-11-24 13:04 UTC, Soupaa submitted a review, later dismissed

2022-11-24 14:03 UTC, andreaslborg requested changes
- Make the placeholder image static (consider just using: assets/login_screen_background_image.png) and not have it be the picture of the citizen
- Add margin/padding to the placeholder picture so it matches the left side.
- Remember to make an issue request for the functionality of the guardian picture.

![image](https://user-images.githubusercontent.com/72602768/203801978-0c5457cd-8dd8-4062-918b-62a3a7e237a2.png)

2022-11-24 14:21 UTC, Soupaa approved these changes
Redone the test. LGTM

2022-11-25 09:17 UTC, Bisgaard01 approved these changes
LGTM works on my machine

2022-11-25 09:18 UTC, andreaslborg approved these changes

2022-11-25 09:19 UTC, merged