With new comments
aau-giraf/weekplanner-OLDUI pull request #878
Opened 2022-10-12 13:08 UTC by YusufIA99

# Description

*The issue was a Trustee could create a new citizen which should not be possible*

Fixes #866 

## Type of change
*Delete unchecked boxes (only for Type of change)*

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

**Development Configuration**
*Type "flutter --version" and "dart --version" in your CMD to check versions.*

* Flutter version:
* Dart version:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas, if necessary
- [ ] I have made corresponding changes to the documentation, if necessary
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works, if necessary
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have Acceptance Tested this on an iOS device
- [ ] I have Acceptance Tested this on an Android device

2022-10-13 08:04 UTC, mikejensen0 requested changes
Fix kode så checks passer

2022-10-13 11:04 UTC, andreaslborg commented
Husk at i bare kan bruge `flutter test --coverage` i terminalen. Så får i hurtigt svar på om nogle af jeres checks failer. @YusufIA99

2022-10-19 11:02 UTC, YusufIA99 commented
@mikejensen0 & @JonasStjerne check passer nu, der var 3 unit test som begyndte at fejle pga. vores løsning på issuet. Vi har prøvet at løse de unit test uden held derfor har vi kommenteret dem ud indtil videre.

2022-10-19 13:54 UTC, mikejensen0 commented
> @mikejensen0 & @JonasStjerne check passer nu, der var 3 unit test som begyndte at fejle pga. vores løsning på issuet. Vi har prøvet at løse de unit test uden held derfor har vi kommenteret dem ud indtil videre.

Men, at have unit tests er jo meningen. Det er bl.a. en del af pensum, så føler det ville være _bad practice_ at slette tests, hvis de stadig er relevante, bare fordi man ikke kan justere dem.

2022-10-27 07:02 UTC, mikejensen0 approved these changes, later dismissed
LGTM++

2022-11-01 09:45 UTC, andreasalstrup commented on lib/screens/choose_citizen_screen.dart
> +    _api.user.me();
Hvorfor er denne linje nødvendig? (evt. skriv kommentar)

2022-11-01 09:49 UTC, andreasalstrup requested changes
Looks good! Tag stilling til kommentar og løs "Conflicting files" så vi kan få det accepteret

2022-11-01 12:54 UTC, andreasalstrup commented on lib/main.dart
> +              return ChooseCitizenScreen(_api);
Efter at havde undersøgt nærmere lader det til at `_api` som parameter ikke har betydning for at løse issue'et. Er dette korrekt?

2022-11-01 14:44 UTC, ThomsenTop commented on lib/main.dart
> +              return ChooseCitizenScreen(_api);
Den forrige linje du nævnte er bliver ikke brugt. Da det ikke fungerede uden _api parameteren, så lod vi den blive, men den krævede at blive refereret, hvorfor den første linje blev brugt. 
Men du har ret i, at _api som parameter ikke har betydning for at løse issuet

2022-11-01 15:11 UTC, andreasalstrup commented on lib/main.dart
> +              return ChooseCitizenScreen(_api);
Okay så forslår jeg at i få fjernet `_api` parameteret fra `ChooseCitizenScreen` kaldet (linje 64), samt der hvor parameteret bruges i `choose_citizen_screen.dart`

2022-11-01 15:17 UTC, ThomsenTop commented on lib/main.dart
> +              return ChooseCitizenScreen(_api);
Yes, får lige fikset det inden for kort tid

2022-11-01 16:02 UTC, ThomsenTop commented on lib/main.dart
> +              return ChooseCitizenScreen(_api);
Det skulle gerne være fikset nu

2022-11-02 11:46 UTC, andreasalstrup commented on lib/screens/choose_citizen_screen.dart
> -                    'Tilføj Bruger',
Her har i slettet 'Tilføj Bruger' og erstattet med 'Tilføj Borger' - Det skal forblive 'Tilføj Bruger'

2022-11-02 11:49 UTC, andreasalstrup commented on lib/screens/choose_citizen_screen.dart
> -            onPressed: () => _pushWeekplanSelector(user),
Pas på med sådan ændringer rundtomkring

2022-11-02 11:54 UTC, andreasalstrup commented on lib/screens/choose_citizen_screen.dart
> -                    'Tilføj Bruger',
Måske skete det i forbindelse med jeres merge for at løse "Conflicting files".

2022-11-02 12:12 UTC, ThomsenTop commented on lib/screens/choose_citizen_screen.dart
> -                    'Tilføj Bruger',
Pas, ikke noget jeg har ændret på i hvert fald.

2022-11-03 07:37 UTC, andreasalstrup commented on lib/screens/choose_citizen_screen.dart
> -                    'Tilføj Bruger',
Jeg tror det er fordi git ser det som om i har slette et stykke kode, også indsat et nyt identisk et af slagsen.

2022-11-03 09:50 UTC, andreasalstrup approved these changes
LGTM

2022-11-03 11:33 UTC, mikejensen0 approved these changes
LGTM, works on my machine

2022-11-03 12:14 UTC, merged