Feature/625
aau-giraf/weekplanner-OLDUI pull request #879
Opened 2022-10-14 13:11 UTC by andreasalstrup

# Description

Converted <code>new_citizen_screen.dart</code> from <code>StatelessWidget</code> to <code>StateFulWidget</code>, in order to change state of role variable at the click of radio buttons. The horizontal radio buttons are made to give users the choice of role when registering.

**The pull request is related to pull request: https://github.com/aau-giraf/web-api/pull/271  - Please merge both**

Fixes #625 

## Type of change
*Delete unchecked boxes (only for Type of change)*

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Test have been added to ensure that rendering of radio buttons happens when registering.
Tests when registration of a new guardian and trustee have been added.

**Development Configuration**

* Flutter version: 2.0.5
* Dart version: 2.12.3

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas, if necessary
- [ ] I have made corresponding changes to the documentation, if necessary
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works, if necessary
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [ ] I have Acceptance Tested this on an iOS device
- [X] I have Acceptance Tested this on an Android device

2022-10-21 07:40 UTC, NikolajKrogh submitted a review, later dismissed
Looks good

2022-10-21 07:53 UTC, Lildhansen requested changes
Looks good, but we are unsure why the "create trustee" and "create guardian" are situated within "tilføj borger" and not some kind of seperate button.

Moreover, we tried creating a trustee, but were unable to, getting the error "The getter 'department' was called on null."

2022-10-21 07:53 UTC, Lildhansen commented on lib/screens/new_citizen_screen.dart
> +                                    _role = value;
Could these 3 "Expanded" not be made into functions with the parameters role (fx 'citizen') and value (fx Roles.citizen)
As far as i can see that is the only difference between the 3.

2022-10-21 07:53 UTC, Lildhansen commented on lib/screens/new_citizen_screen.dart
> +                          }})
could line 217-220 not be made into a function - since it is the same as the other 3 ones.
If possible it would be nice to encapsulate more into the function

2022-10-21 09:13 UTC, lasse2507a commented on lib/screens/new_citizen_screen.dart
> +                                    _role = value;
Vi har fulgt Flutters dokumentation med hensyn til at lave radio buttons (https://api.flutter.dev/flutter/material/Radio-class.html).

2022-10-21 09:31 UTC, andreasalstrup commented on lib/screens/new_citizen_screen.dart
> +                          }})
Fixed

2022-10-24 12:11 UTC, andreasalstrup commented
> Looks good, but we are unsure why the "create trustee" and "create guardian" are situated within "tilføj borger" and not some kind of seperate button.

"borger" er nu ændret til "bruger" de steder hvor guardian/trustee/citizen er en fællesbetegnelse.

Vores tilgang til #625 er at tilføje muligheden for at oprette en guardian/trustee/citizen, med den nuværende simple funktionalitet. Vores tanke er at "Tilføj Bruger" reelt set kun skal vises for guardian rollen for at få den effect i efterspørg med en seperate knap. Vi har ikke fjernet "Tilføj Bruger" for trustee/citizen, da denne funktionalitet er uden for scopet i dette issue.

> Moreover, we tried creating a trustee, but were unable to, getting the error "The getter 'department' was called on null."

Kører I https://github.com/aau-giraf/web-api/pull/271 localt med nyeste dotnet-ef (6.0.10)?
Har ikke selv haft problemet - Har i en error log jeg kan kigge på?

2022-10-24 12:27 UTC, Lildhansen commented
Fin løsning til det med borger/bruger.
Den seperate knap kunne måske være en issue request, da det er lidt uintuitivt at man under "vælg borger" kan se en masse borgere og så kan man trykke "tilføj _bruger_", men ja, det er nok lidt uden for scope at begynde at kigge på det nu.

2022-10-24 13:23 UTC, KasperBahrentzAAU commented
Vi får følgende fejl når vi kører web-api#271, og forsøger at lave en trustee: 
![image](https://user-images.githubusercontent.com/74188293/197535697-eec6f5fa-2799-4131-b51c-8f82ffd97618.png)

2022-10-25 11:27 UTC, lasse2507a commented
> Vi får følgende fejl når vi kører web-api#271, og forsøger at lave en trustee: ![image](https://user-images.githubusercontent.com/74188293/197535697-eec6f5fa-2799-4131-b51c-8f82ffd97618.png)

Kørte web-api (https://github.com/aau-giraf/web-api/pull/271) på windows 10 med: 
* .NET 6.0.42
* .NET EF 6.0.10
* `appsettings.Development.json` opsat til lokalt miljø (samt `environments.local.json` opsat i weekplanner)

Med dette kunne jeg oprette en trustee med radio button "trustee" afkrydset, navn "t", brugernavn "t" og password "t"  uden nogen fejl.

Får I fejlen med samme opsætning?

2022-10-27 07:57 UTC, andreasalstrup commented
> Vi får følgende fejl når vi kører web-api#271, og forsøger at lave en trustee:

Følgende fejl kommer når i kører web-api#271, men error loggen ser ud til at være fra weekplanner?
(`../weekplaner/lib/main.dart`)

2022-10-27 08:11 UTC, Lildhansen commented
Ja, vi kører webapi _på den branch_, og så kører vi weekplanner og prøver at lave en trustee derpå

2022-10-27 08:24 UTC, Lildhansen commented
Men vi er 2 der har prøvet at køre webapi nu inde på branch 625 - og får nu denne fejl:
System.AggregateException: 'One or more errors occurred. (Table 'giraf.AspNetUsers' doesn't exist)'
på linje 297 i Startup.cs

2022-10-27 08:47 UTC, NikolajKrogh approved these changes

2022-10-27 08:48 UTC, Lildhansen approved these changes
lgtm

2022-10-27 11:03 UTC, merged