Pictogram Search (#46)
aau-giraf/weekplanner-OLDUI pull request #90
Opened 2019-03-22 00:27 UTC by boginw

This closes #46

2019-03-22 08:09 UTC, TobiasPalludan commented
@Tricky12321 and @ralled96 would you review this?
Here's the [review checklist](https://github.com/aau-giraf/wiki/blob/master/process_manual/code_workflow.md#code-review)

2019-03-22 08:59 UTC, HaZzM22 commented on pubspec.yaml
> +    git: git@github.com:ptope/async_test.git
This returns an error when trying to get packages

"Could not find a file named "pubspec.yaml" in git@https://github.com/ptope/async_test 8661d8aecd626f7f57ccbcb735553edc05a2e713."

A simple fix would be to use this instead
    git: 
      url: https://github.com/ptope/async_test

2019-03-22 09:57 UTC, boginw commented on pubspec.yaml
> +    git: git@github.com:ptope/async_test.git
This has been fixed

2019-03-22 10:20 UTC, thomaslhansen submitted a review, later dismissed
We should setup some protection with regards to search time. I just ran the app locally and the API crashed doe to an flood of http requests. Perhaps @aau-giraf/sw610f19 will make an issue out of this. I do not know how this could be fixed.

2019-03-22 10:35 UTC, Moesgaarda commented
@thomaslhansen We can make an issue out of it - it depends on whether the group has an idea for a fix that can be easily implemented in this PR

2019-03-22 10:43 UTC, boginw commented
> @thomaslhansen We can make an issue out of it - it depends on whether the group has an idea for a fix that can be easily implemented in this PR

A fix could be implemented here, but I see it as a Back-end and API-client issue. It seems that the back-end is unable to keep up with the requests sent.

2019-03-22 10:51 UTC, Moesgaarda commented
> 
> 
> > @thomaslhansen We can make an issue out of it - it depends on whether the group has an idea for a fix that can be easily implemented in this PR
> 
> A fix could be implemented here, but I see it as a Back-end and API-client issue. It seems that the back-end is unable to keep up with the requests sent.

Agreed. A new issue will be created on the API asap.

2019-03-22 10:58 UTC, ralled96 submitted a review, later dismissed

2019-03-26 12:31 UTC, MStenkaer submitted a review, later dismissed
I have found a bug, that the pictograms change as you scroll the search results. To recreate the bug, search for "kat" wait for it to be done loading. Delete "t" and try to scroll the view.

The bug can be seen in the attached video:
https://drive.google.com/file/d/16bleafzDT7-jhNdEEvLYcT3CfUTdp2g9/view?usp=sharing

Additionally the pictogramSearch crashes sometimes following the bug described before, but this cannot be recreated.

2019-03-28 08:56 UTC, Tekrus requested changes

2019-03-28 08:56 UTC, Tekrus commented on lib/screens/pictogram_search_screen.dart
> +        appBar: GirafAppBar(title: "Pictogram"),
Title should probably in Danish (piktogram)

2019-03-28 11:01 UTC, Tekrus submitted a review, later dismissed

2019-03-28 11:29 UTC, ralled96 approved these changes

2019-03-28 11:31 UTC, Tekrus approved these changes

2019-03-28 11:31 UTC, merged

2019-03-28 11:38 UTC, boginw commented
@Moesgaarda only the author should merge!