Feature/856v2
aau-giraf/weekplanner-OLDUI pull request #900
Opened 2022-11-18 10:13 UTC by JonasStjerne

# Description
This PR makes progress toward solving the issue https://github.com/aau-giraf/weekplanner/issues/856

The work done on this branch extends the previous progress made on the branches:

Weekplanner branch: https://github.com/aau-giraf/weekplanner/tree/feature/856
Api_client branch: https://github.com/aau-giraf/api_client/tree/feature/856

### The branches had completed the following subtasks:

- [x] Add "Tilføj billede" button on the "Ny borger" page
- [x] Add "Tag billede" button on the "Ny borger" page
- [x] Add preview of the selected picture on the "Ny borger" page
- [x] When picture is added, still able to change to another picture

This PR is linked to two other PRs:
Web-api: [PR](https://github.com/aau-giraf/web-api/pull/302)
Api-client: #pr

### The progress made on this branch are the following subtasks:
- [x] Retrieve picture from new_citizen_bloc and send to server
- [x] upload picture to database
- [x] retrieve user pictures from server
- [x] display user pictures on the Choose Citizen screen

This feature adds the ability for a user to contain a profile picture. The profile picture is optional and will be null by default.

When a citizen is created in the Weekplan app, there will be an optional field to upload a picture. 
![image](https://user-images.githubusercontent.com/73853586/202673454-7c6733ed-0a8f-4b25-b1b3-37b2749890a1.png)
The endpoints that have changed with this feature are:
/v2/Account/register
/v1/User
/v1/User/21/citizens

The citizen's pictures will also be displayed on the user-select screen of the guardian if a picture is available.
![image](https://user-images.githubusercontent.com/73853586/202674558-92981ff2-0980-4311-bef2-e881d0c75998.png)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Tested manually. Tests are yet to be implemented.

## How to test for yourself
This should be tested together with the web-api (https://github.com/aau-giraf/web-api/tree/feature/856v2) in this way:
- Get these changes to the web-api locally, then set up the database locally with these changes.
- change line 16 in pubspec.yaml in the weekplanner from `develop ` to `feature/856v2`
- run the database
- start the weekplanner
- Create a new citizen and upload a profile picture
- See the picture on the choose citizen screen

**Development Configuration**
* Flutter version: 2.0.5
* Dart version: 2.12.3

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas, if necessary
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works, if necessary
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have Acceptance Tested this on an iOS device
- [x] I have Acceptance Tested this on an Android device

2022-11-18 10:36 UTC, Taoshix commented
Consider removing commented out code

2022-11-18 11:18 UTC, JonasStjerne commented
> Consider removing commented out code

Fixed in b35d33d88ad54fb68e9cb7de1726fd50e0868805

2022-11-18 12:02 UTC, andreaslborg requested changes
Linter failer. Kan ikke lige se om det er fordi I mangler at få opdateret api_client og web-api'en til develop. Prøv at rerun jeres checks når de er merged ind.
```
Run flutter analyze
Analyzing weekplanner...                                        

  error • Too many positional arguments: 3 expected, but 4 found • lib/blocs/new_citizen_bloc.dart:123:33 • extra_positional_arguments
  error • Too many positional arguments: 3 expected, but 4 found • lib/blocs/new_citizen_bloc.dart:[13](https://github.com/aau-giraf/weekplanner/actions/runs/3496441191/jobs/5854355368#step:8:14)5:33 • extra_positional_arguments
  error • Too many positional arguments: 3 expected, but 4 found • lib/blocs/new_citizen_bloc.dart:[14](https://github.com/aau-giraf/weekplanner/actions/runs/3496441191/jobs/5854355368#step:8:15)7:33 • extra_positional_arguments
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: NewCitizenScreen.screenHeight, NewCitizenScreen.screenWidth • lib/screens/new_citizen_screen.dart:19:7 • must_be_immutable
   info • The value of the field '_translator' isn't used • lib/screens/new_citizen_screen.dart:31:28 • unused_field
   info • The label 'body' isn't used • lib/screens/new_citizen_screen.dart:72:5 • unused_label
  error • The getter 'nrOfDaysToDisplayPortrait' isn't defined for the type 'SettingsModel' • lib/screens/settings_screens/number_of_days_selection_screen.dart:45:38 • undefined_getter
  error • The getter 'nrOfDaysToDisplayLandscape' isn't defined for the type 'SettingsModel' • lib/screens/settings_screens/number_of_days_selection_screen.dart:46:38 • undefined_getter
  error • The setter 'displayDaysRelativePortrait' isn't defined for the type 'SettingsModel' • lib/screens/settings_screens/number_of_days_selection_screen.dart:93:33 • undefined_setter
  error • The setter 'displayDaysRelativeLandscape' isn't defined for the type 'SettingsModel' • lib/screens/settings_screens/number_of_days_selection_screen.dart:94:25 • undefined_setter
  error • The setter 'nrOfDaysToDisplayPortrait' isn't defined for the type 'SettingsModel' • lib/screens/settings_screens/settings_screen.dart:131:35 • undefined_setter
  error • The getter 'nrOfDaysToDisplayPortrait' isn't defined for the type 'SettingsModel' • lib/screens/settings_screens/settings_screen.dart:141:35 • undefined_getter
  error • The setter 'nrOfDaysToDisplayLandscape' isn't defined for the type 'SettingsModel' • lib/screens/settings_screens/settings_screen.dart:148:33 • undefined_setter
  error • The getter 'nrOfDaysToDisplayLandscape' isn't defined for the type 'SettingsModel' • lib/screens/settings_screens/settings_screen.dart:[15](https://github.com/aau-giraf/weekplanner/actions/runs/3496441191/jobs/5854355368#step:8:16)8:34 • undefined_getter
  error • The getter 'nrOfDaysToDisplayPortrait' isn't defined for the type 'SettingsModel' • lib/screens/weekplan_screen.dart:355:44 • undefined_getter
  error • The getter 'displayDaysRelativePortrait' isn't defined for the type 'SettingsModel' • lib/screens/weekplan_screen.dart:357:44 • undefined_getter
  error • The getter 'nrOfDaysToDisplayLandscape' isn't defined for the type 'SettingsModel' • lib/screens/weekplan_screen.dart:360:44 • undefined_getter
  error • The getter 'displayDaysRelativeLandscape' isn't defined for the type 'SettingsModel' • lib/screens/weekplan_screen.dart:362:44 • undefined_getter
  error • The getter 'icon' isn't defined for the type 'DisplayNameModel' • lib/widgets/citizen_avatar_widget.dart:49:63 • undefined_getter
  error • The getter 'icon' isn't defined for the type 'DisplayNameModel' • lib/widgets/citizen_avatar_widget.dart:51:68 • undefined_getter
   info • Avoid defining unused parameters in constructors • lib/widgets/giraf_button_widget.dart:24:27 • avoid_unused_constructor_parameters
  error • Too many positional arguments: 3 expected, but 4 found • test/blocs/new_citizen_bloc_test.dart:44:30 • extra_positional_arguments
  error • The named parameter 'nrOfDaysToDisplayPortrait' isn't defined • test/mock_data.dart:89:9 • undefined_named_parameter
  error • The named parameter 'displayDaysRelativePortrait' isn't defined • test/mock_data.dart:90:9 • undefined_named_parameter
  error • The named parameter 'nrOfDaysToDisplayLandscape' isn't defined • test/mock_data.dart:91:9 • undefined_named_parameter
  error • The named parameter 'displayDaysRelativeLandscape' isn't defined • test/mock_data.dart:92:9 • undefined_named_parameter
  error • 'MockAccountApi.register' ('Stream<GirafUserModel> Function(String, String, String, Uint8List, {int departmentId, Role role})') isn't a valid override of 'AccountApi.register' ('Stream<GirafUserModel> Function(String, String, String, {int departmentId, Role role})') • test/screens/new_citizen_screen_test.dart:33:26 • invalid_override
  error • The named parameter 'nrOfDaysToDisplayPortrait' isn't defined • test/screens/settings_screens/number_of_days_selection_screen.dart:33:9 • undefined_named_parameter
  error • The named parameter 'displayDaysRelativePortrait' isn't defined • test/screens/settings_screens/number_of_days_selection_screen.dart:34:9 • undefined_named_parameter
  error • The named parameter 'nrOfDaysToDisplayLandscape' isn't defined • test/screens/settings_screens/number_of_days_selection_screen.dart:35:9 • undefined_named_parameter
  error • The named parameter 'displayDaysRelativeLandscape' isn't defined • test/screens/settings_screens/number_of_days_selection_screen.dart:36:9 • undefined_named_parameter
  error • The setter 'nrOfDaysToDisplayLandscape' isn't defined for the type 'SettingsModel' • test/screens/weekplan_screen_test.dart:605:[18](https://github.com/aau-giraf/weekplanner/actions/runs/3496441191/jobs/5854355368#step:8:19) • undefined_setter
  error • The setter 'nrOfDaysToDisplayLandscape' isn't defined for the type 'SettingsModel' • test/screens/weekplan_screen_test.dart:618:18 • undefined_setter
  error • The setter 'nrOfDaysToDisplayLandscape' isn't defined for the type 'SettingsModel' • test/screens/weekplan_screen_test.dart:631:18 • undefined_setter
  error • The setter 'nrOfDaysToDisplayLandscape' isn't defined for the type 'SettingsModel' • test/screens/weekplan_screen_test.dart:654:18 • undefined_setter
  error • The setter 'nrOfDaysToDisplayLandscape' isn't defined for the type 'SettingsModel' • test/screens/weekplan_screen_test.dart:757:18 • undefined_setter
  error • The setter 'nrOfDaysToDisplayLandscape' isn't defined for the type 'SettingsModel' • test/screens/weekplan_screen_test.dart:9[23](https://github.com/aau-giraf/weekplanner/actions/runs/3496441191/jobs/5854355368#step:8:24):18 • undefined_setter

[37](https://github.com/aau-giraf/weekplanner/actions/runs/3496441191/jobs/5854355368#step:8:38) issues found. (ran in 23.9s; 7 public members lack documentation)
Error: Process completed with exit code 1.
```

2022-11-20 15:52 UTC, andreaslborg commented on test/screens/new_citizen_screen_test.dart
> +  // ignore: lines_longer_than_80_chars
Consider using "Reformat with 'dart format'" instead of ignoring the lines longer than 80 chars.
Just right-click in android studio.
![image](https://user-images.githubusercontent.com/72602768/202911909-123812c4-4f5c-4f5b-a32a-6b43ee444151.png)

2022-11-21 17:26 UTC, andreaslborg requested changes
Kan tests fixes, eller skal de slettes?
Opdate: 2 tests bliver slettet da de ikke længere har relevans for kode basen. Godkendt af sw-3 og bait-1

2022-11-21 17:26 UTC, andreaslborg commented on test/screens/new_citizen_screen_test.dart
> +  // testWidgets('"Brugernavnet eksisterer allerede" error message',
Kunne denne test ikke fixes? Hvis ikke, så synes jeg at den skal slettes.
Det samme gælder for den sidste test på linje 275.

2022-11-21 17:26 UTC, andreaslborg commented on test/screens/new_citizen_screen_test.dart
> +  // testWidgets('Unexpected error from the api_client',
Samme med denne test

2022-11-22 07:26 UTC, JonasStjerne commented on test/screens/new_citizen_screen_test.dart
> +  // testWidgets('"Brugernavnet eksisterer allerede" error message',
Vi har prøvet og kan ikke få det til at virke. Vi åbner et nyt issue med det, som nogen, måske til næste år, kan forhåbentlig fixe. Derfor vil det være ærgerligt at slette det helt, da vi stadig mener de her test kan være relevant. Hvad tænker du om det? 😄

2022-11-22 08:28 UTC, andreasalstrup commented
Hej! Jeg har opdaget en fejl, når man skifter til 'citizen mode' fra en ugeplan. Processen for at få fejlen er vist på nedenstående billeder.

![image](https://user-images.githubusercontent.com/24495854/203260673-5c3f883a-2719-48ed-9b93-ad35a8b9a6b2.png)
![image](https://user-images.githubusercontent.com/24495854/203260780-8d05e658-3ccb-44ad-9d06-1b82bec020ed.png)
![image](https://user-images.githubusercontent.com/24495854/203260829-4c73a62c-4cf8-4b6b-8d9a-8ced8b000dc9.png)

2022-11-22 08:41 UTC, JonasStjerne commented
> Hej! Jeg har opdaget en fejl, når man skifter til 'citizen mode' fra en ugeplan. Processen for at få fejlen er vist på nedenstående billeder.
> 
> ![image](https://user-images.githubusercontent.com/24495854/203260673-5c3f883a-2719-48ed-9b93-ad35a8b9a6b2.png) ![image](https://user-images.githubusercontent.com/24495854/203260780-8d05e658-3ccb-44ad-9d06-1b82bec020ed.png) ![image](https://user-images.githubusercontent.com/24495854/203260829-4c73a62c-4cf8-4b6b-8d9a-8ced8b000dc9.png)

Det får vi lige undersøgt

2022-11-22 09:02 UTC, andreasalstrup commented
> > Hej! Jeg har opdaget en fejl, når man skifter til 'citizen mode' fra en ugeplan. Processen for at få fejlen er vist på nedenstående billeder.

> Det får vi lige undersøgt

Ups! Jeg havde glemt jeres nyeste commits!

Har lige rettet det sidste billed: Fejlen er sikkert den samme, nu bare en blank side.

2022-11-22 09:19 UTC, andreaslborg commented on test/screens/new_citizen_screen_test.dart
> +  // testWidgets('"Brugernavnet eksisterer allerede" error message',
Hvis vi får oprettet et nyt issue omkring det, er jeg åben for at vi beholder dem begge.
For ja, de virker nemlig relevante, men vi havde også problemer med dem begge, da vi sad med issuet.
Skal vi ikke bare aftale at i opretter et issue request når det her er merged, så er det på plads.

2022-11-22 09:20 UTC, JonasStjerne commented on test/screens/new_citizen_screen_test.dart
> +  // testWidgets('"Brugernavnet eksisterer allerede" error message',
Ja det får vi gjort

2022-11-22 09:24 UTC, JonasStjerne commented
> > > Hej! Jeg har opdaget en fejl, når man skifter til 'citizen mode' fra en ugeplan. Processen for at få fejlen er vist på nedenstående billeder.
> 
> > Det får vi lige undersøgt
> 
> Ups! Jeg havde glemt jeres nyeste commits!
> 
> Har lige rettet det sidste billed: Fejlen er sikkert den samme, nu bare en blank side.

Vi kan ikke reproduce din error. Er du sikker på du kører den rigtige version af api-clienten og web-api'en?

2022-11-22 09:54 UTC, andreasalstrup commented
> > > > Hej! Jeg har opdaget en fejl, når man skifter til 'citizen mode' fra en ugeplan. Processen for at få fejlen er vist på nedenstående billeder.
> > 
> > 
> > > Det får vi lige undersøgt
> > 
> > 
> > Ups! Jeg havde glemt jeres nyeste commits!
> > Har lige rettet det sidste billed: Fejlen er sikkert den samme, nu bare en blank side.
> 
> Vi kan ikke reproduce din error. Er du sikker på du kører den rigtige version af api-clienten og web-api'en?

Skulle DROP/CREATE database fra ny - My bad, det virker som det skal 👍

2022-11-22 10:09 UTC, andreaslborg approved these changes
Super godt arbejde!
Er acceptance tested og virker korrekt samt har ikke flere kode kommentarer.

2022-11-22 10:10 UTC, andreasalstrup approved these changes
LGTM

2022-11-22 10:13 UTC, TorbjoernH approved these changes
Ser fint ud og kører uden problemer for mig

2022-11-22 10:18 UTC, merged