issue 633
aau-giraf/weekplanner-OLDUI pull request #904
Opened 2022-11-21 13:11 UTC by mariusgardshodn

# Description
It is now possible to change password and username of Guardians and Trustees.
It is also possible to change the username of a citizen.

NB. The settings menu consists of two buttons which just lead to the respective screens. It is *not* built using the settings_bloc like the citizens settings screen.

sub tasks completed:
- Create a guardian settings menu
- Have Guardians and Trustees be able to change their own username.
- Have Guardians and Trustees be able to change their own password.
- Have Guardians and Trustees be able to change the username of citizens.

Fixes #633 

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
Unit tests

We have tested, using widgettester, that the widgets build correctly. Moreover, we have tested the logic of authentication of a user to ensure that it is correct.

**Development Configuration**
* Flutter version: Flutter 2.0.5
* Dart version: Dart SDK version: 2.12.3

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas, if necessary
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works, if necessary
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have Acceptance Tested this on an iOS device
- [ ] I have Acceptance Tested this on an Android device

2022-11-23 11:15 UTC, djepse20 requested changes
please look at my two comments and fix the issues related to those.
Otherwise LGTM!!

2022-11-23 11:15 UTC, djepse20 commented on assets/environments.dev.json
> +  "SERVER_HOST": "http://10.0.2.2:5000",
is this on purpose?
Please change back if its not!!

2022-11-23 11:15 UTC, djepse20 commented on lib/blocs/choose_citizen_bloc.dart
> +  //Stream<GirafUserModel> get guardian => _currentUser.stream;
Why did you add this as a uncommented line?
If its not intended to be there, remove it :), otherwise uncomment it.

2022-11-23 11:21 UTC, manfredhod commented
It works fine when testing the functionality locally.

2022-11-24 09:29 UTC, mariusgardshodn commented on assets/environments.dev.json
> +  "SERVER_HOST": "http://10.0.2.2:5000",
We have changed it back. Thank you for pointing it out! :D

2022-11-24 09:30 UTC, mariusgardshodn commented on lib/blocs/choose_citizen_bloc.dart
> +  //Stream<GirafUserModel> get guardian => _currentUser.stream;
Thank you for pointing it out! We have deleted the line :D

2022-11-24 10:29 UTC, djepse20 approved these changes
Every is great now guys 👨‍👦‍👦 very good job! 🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳

2022-11-24 11:34 UTC, Taoshix approved these changes
I was able to create a guardian and trustee and change their password successfully

2022-11-24 11:38 UTC, merged