Feature/851
aau-giraf/weekplanner-OLDUI pull request #908
Opened 2022-11-22 12:20 UTC by henr9533

# Description

A new folder containing custom exceptions has been added, which currently contains three different exceptions. They are however similar and can later be changed to be much more unique if so required. Furthermore, multiple try-catch statements have been implemented in various areas of the code, to ensure a stable launch.

Fixes #\851

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

A new test file has been created which includes three tests to make sure that the new custom exceptions exist and are thrown correctly.

**Development Configuration**

* Flutter version: 2.0.5
* Dart version: 2.12.3

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas, if necessary
- [ ] I have made corresponding changes to the documentation, if necessary
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works, if necessary
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have Acceptance Tested this on an iOS device
- [ ] I have Acceptance Tested this on an Android device

2022-11-25 09:34 UTC, JJTM20 requested changes
1 comment, the rest looks fine:)

2022-11-25 09:34 UTC, JJTM20 commented on lib/main.dart
> +  environment.setFile('assets/environments.local.json').whenComplete(() {
Shouldn't this be changed back to `environment.setFile('assets/environments.dev.json')`?

2022-11-25 10:05 UTC, KasperBahrentzAAU reviewed
Looks good, har bare lige et par spørgsmål

2022-11-25 10:05 UTC, ghost commented on lib/main.dart
> +  environment.setFile('assets/environments.local.json').whenComplete(() {
Dette skal forblive `dev`, right?

2022-11-25 10:05 UTC, ghost commented on lib/screens/login_screen.dart
> +          //Er ikke sikker på den her try-catch nogen sinde "catcher"
I guess this comment should be in English

2022-11-25 10:05 UTC, KasperBahrentzAAU commented on test/exceptions/custom_exceptions_test.dart
> +    expect(throwServerException, throwsA(isA<ServerException>()));
Hvad er det lige `throwsA` og `isA` gør? 😅

2022-11-25 10:05 UTC, KasperBahrentzAAU commented on test/widgets/pictogram_image_test.dart
> +      onPressed: () {},
Behøver `onPressed` at være der?

2022-11-25 10:11 UTC, henr9533 commented on lib/main.dart
> +  environment.setFile('assets/environments.local.json').whenComplete(() {
Har du ret i. Den er blevet fikset :)

2022-11-25 10:12 UTC, henr9533 commented on lib/main.dart
> +  environment.setFile('assets/environments.local.json').whenComplete(() {
Yes, den er lige blevet ændret tilbage :) Havde du ellers problemer med noget andet i branchen :o?

2022-11-25 10:13 UTC, henr9533 commented on lib/screens/login_screen.dart
> +          //Er ikke sikker på den her try-catch nogen sinde "catcher"
Rettet til engelsk

2022-11-25 10:15 UTC, henr9533 commented on test/exceptions/custom_exceptions_test.dart
> +    expect(throwServerException, throwsA(isA<ServerException>()));
throwsA er en funktion, som tjekker om der bliver smidt en specifik exception hvorimod isA definerer hvilken type af exception det er 😃

2022-11-25 10:16 UTC, henr9533 commented on test/widgets/pictogram_image_test.dart
> +      onPressed: () {},
Den er der fra develop branch af, så har ikke ændret i den. Bare automatisk formatting der er blevet lavet 🙂

2022-11-25 10:54 UTC, YusufIA99 approved these changes, later dismissed
Looks good to me 👍

2022-11-25 10:58 UTC, JJTM20 approved these changes, later dismissed
lgtm+

2022-11-29 11:07 UTC, YusufIA99 submitted a review, later dismissed

2022-11-30 13:05 UTC, KasperBahrentzAAU approved these changes, later dismissed
Sgutm

2022-12-01 08:14 UTC, karlbarnholdt approved these changes
Super

2022-12-01 08:17 UTC, J2KJonas approved these changes

2022-12-01 08:18 UTC, merged