Flutter/feature 023
aau-giraf/weekplanner-OLDUI pull request #91
Opened 2019-03-25 11:22 UTC by TobiasPalludan

Solves #23.

2019-03-25 14:50 UTC, sipman requested changes

2019-03-25 14:50 UTC, sipman commented on lib/blocs/toolbar_bloc.dart
> +  BehaviorSubject<bool> _editVisible = new BehaviorSubject();
Lack of initial value will lead to the first streamed value being `null`. This can lead to unwanted behaviors, please add a initial value. If no initial value is needed please ensure that a BehaviorSubject is the correct Subject for the intended behavior.

Add initial value by

```dart
  BehaviorSubject<bool> _editVisible = new BehaviorSubject().seeded(false/true);
```

2019-03-25 14:50 UTC, sipman commented on test/widgets/widget_test.dart
> +import 'package:flutter_test/flutter_test.dart';
what ? :D

2019-03-26 10:53 UTC, boginw commented on test/widgets/giraf_app_bar_widget_test.dart
> +  String keyOfVisibilityForEdit = "visibilityEditBtn";
Then it should be stored as a `const` somewhere

2019-03-26 10:53 UTC, Sworgon commented on lib/blocs/toolbar_bloc.dart
> +  BehaviorSubject<bool> _editVisible = new BehaviorSubject();
As a response to this comment, we seeded the BehaviorSubject to be false.

2019-03-26 10:53 UTC, Sworgon commented on test/widgets/widget_test.dart
> +import 'package:flutter_test/flutter_test.dart';
We deleted the standard Flutter test as a response to this comment.

2019-03-26 10:53 UTC, Sworgon commented on lib/blocs/toolbar_bloc.dart
> +  BehaviorSubject<bool> _editVisible = new BehaviorSubject();
As a response to this comment, we seeded the BehaviorSubject to be false.

`BehaviorSubject<bool> _editVisible = new BehaviorSubject<bool>.seeded(false);`

2019-03-26 10:54 UTC, Sworgon commented on test/widgets/widget_test.dart
> +import 'package:flutter_test/flutter_test.dart';
As a response to this comment, we deleted the auto-generated standard Dart Test for the template app.

2019-03-26 14:50 UTC, jenspetur94 requested changes
Dont know if this is only for me but the edit button is never visible. 
Shouldn't the change mode button change it from false to true ? 
i even tried seeding the stream with true instead of false and the button still wasn't visible.
![image](https://user-images.githubusercontent.com/22811843/55005503-6658b600-4fdc-11e9-9658-1d49320c2a88.png)

2019-03-26 14:50 UTC, jenspetur94 commented on lib/widgets/giraf_app_bar_widget.dart
> +            Navigator.pushNamed(context, '/settings');
Shouldn't this be changed to :
`Routes.push(context, SettingsScreen());`
after the core update were they changed routing ? 
As it is right now it throws an exception every time it is pressed.

2019-03-28 07:45 UTC, Jacob6565 commented on lib/widgets/giraf_app_bar_widget.dart
> +            Navigator.pushNamed(context, '/settings');
To our knowledge the edit-button shold become visible when some task are being marked. It should work when you send a true value through the stream editVisible by calling setEditVisible(true). Atleast our tests show that it should  work.

2019-03-28 07:51 UTC, Jacob6565 commented
> 
> 
> Dont know if this is only for me but the edit button is never visible.
> Shouldn't the change mode button change it from false to true ?
> i even tried seeding the stream with true instead of false and the button still wasn't visible.
> ![image](https://user-images.githubusercontent.com/22811843/55005503-6658b600-4fdc-11e9-9658-1d49320c2a88.png)

2019-03-28 08:16 UTC, Jacob6565 commented on lib/widgets/giraf_app_bar_widget.dart
> +            Navigator.pushNamed(context, '/settings');
You are right, this is now changed.

2019-03-28 08:27 UTC, jenspetur94 commented
> > Dont know if this is only for me but the edit button is never visible.
> > Shouldn't the change mode button change it from false to true ?
> 
> To our knowledge the edit-button shold become visible when some tasks are being marked. It should work when you send a true value through the stream editVisible by calling setEditVisible(true). Atleast our tests show that it should work. I think the reason it doesn't work when seeding the stream with true, is because in the giraf_app_bar_widget.dart file, the intial value for the stream is set to false, so maybe it overrides it. I will look into this.

yeah i see that now. it worked when i called setEditVisible(true);
just disregard that part of my comment then. But my comment about routing still stands

2019-03-28 10:40 UTC, sipman submitted a review, later dismissed

2019-03-28 10:42 UTC, Tekrus submitted a review, later dismissed

2019-03-28 10:43 UTC, Moesgaarda commented on test/blocs/toolbar_bloc_test.dart
> +  test('tream should emit false', () {
```suggestion
  test('Stream should emit false', () {
```

2019-03-28 10:43 UTC, jenspetur94 submitted a review, later dismissed

2019-03-28 10:44 UTC, Tekrus approved these changes

2019-03-28 10:44 UTC, jenspetur94 approved these changes

2019-03-28 10:59 UTC, merged