Flutter/feature 049 logout
aau-giraf/weekplanner-OLDUI pull request #94
Opened 2019-03-26 09:59 UTC by thomaslhansen

Fixes #49 

A screen has been added so that a user is prompted to confirm logout.

2019-03-26 10:08 UTC, MathiasLybech commented on lib/screens/logout_screen.dart
> +      child: Container(
Kig på indentation igen

2019-03-26 10:17 UTC, thomaslhansen commented on lib/screens/logout_screen.dart
> +      child: Container(
Indentation is IntelliJ standard for Dart and has been used throughout the project. See all files ending with .dart

2019-03-27 09:59 UTC, Moesgaarda commented
This seems very overly complicated - is it really necessary with an entire screen with background and everything, why not use [alertDialog](https://docs.flutter.io/flutter/material/AlertDialog/content.html) which is the normal way to do it for apps?

In addition to this, why is `Widget GetLogo(bool Keyboard, bool Portrait) {
  if (Keyboard) {
    return Container();
  }
` needed in this? Will you ever have a keyboard present on the logout page?


As PO I would like to request it as an alert dialog that's an overlay on the current page instead, as this will be more clean.

2019-03-28 09:37 UTC, thomaslhansen commented
![image](https://user-images.githubusercontent.com/6441910/55146790-848df580-5145-11e9-804c-e7fa5673f360.png)

2019-03-28 11:12 UTC, Tekrus requested changes

2019-03-28 11:12 UTC, Moesgaarda commented on lib/widgets/giraf_app_bar_widget.dart
> +                desc: 'Vil du at logge ud?',
```suggestion
                desc: 'Vil du logge ud?',
```

2019-03-29 10:32 UTC, Tekrus requested changes

2019-03-29 10:32 UTC, Moesgaarda commented on lib/widgets/giraf_app_bar_widget.dart
> +            icon: const Icon(Icons.lock),
This icon is not consistent with the [Design guide](https://github.com/aau-giraf/wiki/blob/master/design_guide/icons.md)

2019-03-29 11:42 UTC, thomaslhansen commented
![image](https://user-images.githubusercontent.com/6441910/55230443-23872000-5220-11e9-964c-70b0562e50cd.png)

2019-03-29 11:48 UTC, Tekrus requested changes

2019-03-29 11:48 UTC, Moesgaarda commented on lib/widgets/giraf_app_bar_widget.dart
> +          icon: Image.asset('assets/changeToGuardian.png'),
This should be change to citizen, logging out and such is only available when you're in guardian view.

2019-03-29 11:48 UTC, Moesgaarda commented on lib/widgets/giraf_app_bar_widget.dart
> +          icon: Image.asset('assets/changeToGuardian.png'),
also, is it possible to use the .svg files instead? It should scale better than the pngs

2019-03-29 11:55 UTC, thomaslhansen commented on lib/widgets/giraf_app_bar_widget.dart
> +          icon: Image.asset('assets/changeToGuardian.png'),
Flutter does not currently support SVG. Follow issue https://github.com/flutter/flutter/issues/1831 for updates.

If you absolutely need vector drawing you can see the Flutter Logo widget(https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/flutter_logo.dart) as an example of how to draw using the Canvas API, or rasterize your image on the native side and pass it to Flutter as a bitmap, but for now your best bet is probably to embed high-resolution rasterized asset images.
https://stackoverflow.com/questions/44087400/flutter-svg-rendering

2019-03-29 11:58 UTC, Moesgaarda commented on lib/widgets/giraf_app_bar_widget.dart
> +          icon: Image.asset('assets/changeToGuardian.png'),
How about (this?)[https://pub.dartlang.org/packages/flutter_svg ?]

2019-03-29 12:00 UTC, boginw commented on lib/widgets/giraf_app_bar_widget.dart
> +          icon: Image.asset('assets/changeToGuardian.png'),
That lib has many TODOs which haven't been resolved, such as text. Are we sure we want that lib?

2019-03-29 12:04 UTC, Moesgaarda commented on lib/widgets/giraf_app_bar_widget.dart
> +          icon: Image.asset('assets/changeToGuardian.png'),
Not sure, it was just the first result on Google - I'm just not sure how well a 35x35px image will scale for different devices.

Someone should probably look into that

2019-03-29 12:08 UTC, Moesgaarda commented on lib/widgets/giraf_app_bar_widget.dart
> +          icon: Image.asset('assets/changeToGuardian.png'),
Is there any downside to using a larger image for the icons?

2019-03-29 12:49 UTC, thomaslhansen commented on lib/widgets/giraf_app_bar_widget.dart
> +          icon: Image.asset('assets/changeToGuardian.png'),
It does work, but not with all icons and all colours are overwritten. So overall its not very useful at this moment.

2019-03-29 12:50 UTC, thomaslhansen commented on lib/widgets/giraf_app_bar_widget.dart
> +          icon: Image.asset('assets/changeToGuardian.png'),
icon: SvgPicture.asset('assets/changeToCitizen.svg'), 
![image](https://user-images.githubusercontent.com/6441910/55233703-9ba61380-5229-11e9-9be2-d993c8694b4e.png)

2019-03-29 21:18 UTC, Moesgaarda commented
I just noticed an additional thing:

According to the [design guide section about buttons](https://github.com/aau-giraf/wiki/blob/master/design_guide/buttons.md) the confirming action should be on the left and cancel on the right.

Again, refer to prototype:
![image](https://user-images.githubusercontent.com/21969475/55263201-81dbef00-5270-11e9-862c-6f4233173b6e.png)

2019-03-30 10:13 UTC, Moesgaarda commented on lib/widgets/giraf_app_bar_widget.dart
> +          icon: Image.asset('assets/changeToGuardian.png'),
> 
> 
> It does work, but not with all icons and all colours are overwritten. So overall its not very useful at this moment.

Yeah, that's not amazing - png it is!
Do you recon the 35x35 size is good enough for large resolution screens?

2019-03-30 11:24 UTC, thomaslhansen commented on lib/widgets/giraf_app_bar_widget.dart
> +          icon: Image.asset('assets/changeToGuardian.png'),
We have received two of the new Ipads yesterday so we can test it on Monday.

2019-03-31 13:22 UTC, Moesgaarda commented
Alright two last things, and then I think we're OK with the PR:
1) The icons should probably be in an icons folder under assets, so they don't flood the whole folder
1.1) The icon is weirdly exported, and has a white dot under the arrow, this should probably be fixed (shouldn't take more than a minute, you can even ping us if you want us to do it)
![image](https://user-images.githubusercontent.com/21969475/55289572-b367ce00-53c8-11e9-9d4d-1f5880a311f8.png)

2) Is it possible to disable the animation for the alert? And if not, we would prefer the animation to be set to AnimationType.grow instead, since it's less distracting

2019-04-01 07:50 UTC, thomaslhansen commented
I can not disable the animation but I can make it grow. Will you please export the icon again and ping me once it is ready? @Moesgaarda

2019-04-01 10:15 UTC, Moesgaarda commented
> 
> 
> I can not disable the animation but I can make it grow. Will you please export the icon again and ping me once it is ready? @Moesgaarda

The icons are now updated, both as svg and png and are available in the design guide.
If the size isn't good enough, it's easy to export it with Inkscape.

2019-04-01 11:50 UTC, LukasRH reviewed
@aau-giraf/sw613f19 review
Unless the downgrade in packages was intentional, there might be a dependency or something changing it.  

When creating a new branch and running flutter get, these two dependencies will be downgraded, im not sure what the course for this is

2019-04-01 11:50 UTC, LukasRH commented on pubspec.lock
> +    version: "1.4.0"
Why have you downgraded this package?

2019-04-01 11:50 UTC, LukasRH commented on pubspec.lock
> +    version: "1.5.4"
Same as above?

2019-04-01 12:10 UTC, thomaslhansen commented on pubspec.lock
> +    version: "1.4.0"
Since the .lock file is only used as a local cache when compiling this file is not relevant for review.

2019-04-01 12:10 UTC, thomaslhansen commented on pubspec.lock
> +    version: "1.5.4"
Same as above

2019-04-01 12:29 UTC, LukasRH commented on pubspec.lock
> +    version: "1.4.0"
Okay, this was just something that was commented on in one of our pull requests.

2019-04-01 12:30 UTC, ralled96 approved these changes

2019-04-01 12:43 UTC, Tekrus approved these changes

2019-04-01 13:51 UTC, merged