Flutter/feature 050
aau-giraf/weekplanner-OLDUI pull request #96
Opened 2019-03-26 12:54 UTC by Alechj

Solves issue #50

2019-03-26 13:09 UTC, ralled96 commented
@TobiasPalludan I have been assigned to review my own groups PR.

2019-03-26 14:36 UTC, thomaslhansen requested changes
Initial read through

2019-03-26 14:36 UTC, thomaslhansen commented on lib/screens/weekplan_selector_screen.dart
> +//import 'package:weekplanner/screens/new_weekplan_screen.dart';
Why is this commented out?

2019-03-26 14:36 UTC, thomaslhansen commented on lib/screens/weekplan_selector_screen.dart
> +      //onTap: () => Navigator.push(context, NewWeekplanScreen),
There should be no TODO's in your pull request also the Navigator.push will not work if you rebase from develop first since we have changed to dependency injection.

2019-03-26 14:36 UTC, thomaslhansen commented on lib/screens/weekplan_selector_screen.dart
> +        //onTap: () => Navigator.push(context, //insert weekplan screen here with user in constructor ?),
Same as above

2019-03-26 14:36 UTC, thomaslhansen commented on lib/screens/weekplan_selector_screen.dart
> +              ))
What has happened to the indentation here?

2019-03-26 14:36 UTC, thomaslhansen commented on pubspec.lock
> +    version: "1.4.0"
Why have you down graded this package?

2019-03-26 14:36 UTC, thomaslhansen commented on pubspec.lock
> +    version: "1.5.4"
Same as above?

2019-03-28 07:48 UTC, TobiasPalludan commented
> @TobiasPalludan I have been assigned to review my own groups PR.

My bad :)

2019-03-28 08:49 UTC, Moesgaarda commented on lib/screens/weekplan_selector_screen.dart
> +      //onTap: () => Navigator.push(context, NewWeekplanScreen),
In addition to @thomaslhansen s comment, please make the todo into an issue instead, so it will be done later.

2019-03-28 11:06 UTC, thomaslhansen requested changes

2019-03-28 11:06 UTC, thomaslhansen commented on lib/main.dart
> +import 'package:weekplanner/screens/weekplan_selector_screen.dart';
These two lines should not be in the main.dart file, they are not used

2019-04-02 07:51 UTC, thomaslhansen submitted a review, later dismissed

2019-04-02 11:14 UTC, thomaslhansen approved these changes

2019-04-02 11:15 UTC, thomaslhansen requested changes
Fix linter errors

2019-04-02 11:46 UTC, thomaslhansen approved these changes

2019-04-02 11:47 UTC, andpaacoke approved these changes
It seems to be working correctly, and I couldn't find any problems in the code

2019-04-02 12:06 UTC, merged