54 - Change usermode.
aau-giraf/weekplanner-OLDUI pull request #97
Opened 2019-03-29 08:02 UTC by Jacob6565

Closes #54

2019-04-01 12:25 UTC, LukasRH requested changes
@aau-giraf/sw613f19 review.
Looks fine, there is some inconsistency in whitespace in the files. Such as several empty lines between code, or empty lines in the bottom of the file, but above the last closing bracket.

2019-04-01 12:25 UTC, LukasRH commented on lib/screens/weekplan_screen.dart
> +            ),
Could these Streambuilders maybe be made into a function to reduce code? 
As far as we can see, only three things changes in the code. (snapshot.data.item2, color,  _day)

2019-04-01 12:25 UTC, LukasRH commented on lib/widgets/giraf_app_bar_widget.dart
> +  //
Empty comment?

2019-04-01 12:25 UTC, LukasRH commented on lib/bootstrap.dart
> +import 'package:weekplanner/blocs/toolbar_bloc.dart';
Duplicate import of toolbar_bloc

2019-04-01 12:25 UTC, LukasRH commented on pubspec.yaml
> +  mockito: ^4.0.0
mockito is also in dev dependency, which is unnecessary when in normal dependencies. Might be the reason why the build failed.

2019-04-02 11:15 UTC, LukasRH approved these changes

2019-04-02 11:41 UTC, TobiasPalludan commented
Closed due to conflict with #100

2019-04-02 11:41 UTC, closed without merging