Flutter/feature 55
aau-giraf/weekplanner-OLDUI pull request #99
Opened 2019-04-01 11:53 UTC by B97theFallen

This fixes issue #55 
This fixes issue #56

2019-04-01 12:36 UTC, Moesgaarda commented
This should probably be merged into develop instead of master

2019-04-02 06:20 UTC, TobiasPalludan commented
@aau-giraf/sw602f19 and @aau-giraf/sw609f19 on this one.
Here's the [review checklist](https://github.com/aau-giraf/wiki/blob/master/process_manual/code_workflow.md#code-review)

2019-04-02 06:23 UTC, Moesgaarda commented
The icon was already added with #94 and is in a different location, please update to fit.

2019-04-02 06:24 UTC, Tekrus requested changes

2019-04-02 06:24 UTC, Moesgaarda commented on lib/screens/confirm_password_screen.dart
> +                  Container(
shouldn't this only be available in debugging mode?

2019-04-02 07:43 UTC, Moesgaarda commented
Generally: All public members should be documented.
Consider if passwordCtrl and authBloc should be private instead of public.


For some reason I can't log into the app right now, so I can't see the GUI part, so I will check that later.

2019-04-02 07:45 UTC, Tekrus requested changes

2019-04-02 07:45 UTC, Moesgaarda commented on lib/screens/confirm_password_screen.dart
> -                  Container(
This feature would still be nice to have, but it should just be available in debug mode (like the login screen)

2019-04-02 09:35 UTC, Sworgon submitted a review, later dismissed
The UI looks good after the comments, and the functionality seems sound. They just need
@Moesgaarda's review to merge.

2019-04-02 09:41 UTC, Sworgon submitted a review, later dismissed
This only fixes the visibility of the hint text, so I will approve it

2019-04-03 11:34 UTC, Tekrus approved these changes

2019-04-03 11:35 UTC, thomaslhansen commented
![image](https://user-images.githubusercontent.com/6441910/55475840-472dda00-5615-11e9-96e4-fb1b302e6734.png)

2019-04-03 11:43 UTC, Sworgon approved these changes
It looks good.

2019-04-03 11:45 UTC, merged